### ISSUE TITLE
Credenziali SPID di test per accesso alla App (modo sviluppatore)

### ISSUE THREAD

**Issue by massimobiagioli** [pagopa/io-app#1534]
Una volta lanciata la app sul device per test (modo sviluppatore), dovrei potermi loggare con le credenziali SPID corrispondenti al codice fiscale "dummy" rilasciato per utilizzo del backend.
Inoltre, servirebbe poter utilizzare importo superiore a 0cents. E' possibile?
Grazie

**Comment by Undermaken** [comment]
Ciao. Il profilo creato per il backend non è una identità SPID per questo non è possibile usarlo per fare login.

Per entrare è necessaria una identità digitale oppure puoi eseguire l'app con [backend simulato](https://github.com/pagopa/io-dev-api-server). In questo ultimo caso però non puoi visualizzare alcun messaggio "vero" inviato con l'accound dummy.
