### ISSUE TITLE
Tokens in environment files

### ISSUE THREAD

**Issue by bfabio** [pagopa/io-app#1539]
`MIXPANEL_TOKEN` and `INSTABUG_TOKEN` in [.env.example](/pagopa/io-app/blob/master/.env.example) and [.env.production](/pagopa/io-app/blob/master/.env.production) are probably best kept hidden.

**Comment by pp-ps** [comment]
This is a deliberate design.

We want to track "events" generated by anonymous users, lacking a valid session with our backend.
This design could help diagnose, troubleshoot and respond to pre-login problems. As long as we want to do this from a business perspective, there isn't much difference between a public token and an unathenticated API.

**Comment by bfabio** [comment]
@pp-ps makes sense, thanks.
