### ISSUE TITLE
Icona di notifica Android: dovrebbe essere bianca su sfondo trasparente

### ISSUE THREAD

**Issue by thearaks** [pagopa/io-app#1715]
**Descrivi il problema**
L'icona di notifica Android è erroneamente colorata di blu.

**Expected behavior**
Da linee guida deve essere bianca su sfondo trasparente.

**Screenshots**
![Screenshot_2020-04-22-12-54-13-205_com miui home](https://user-images.githubusercontent.com/5188791/79974168-1aa36500-8499-11ea-882b-55a0e4abfa5b.jpg)

**Versione dell'app**
1.1.34717

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi Note 10
 - OS: Android 9 MIUI Global 11.0.16

**Comment by Undermaken** [comment]
https://www.pivotaltracker.com/story/show/173529091
