### ISSUE TITLE
Dialog permessi con messaggio tagliato 

### ISSUE THREAD

**Issue by vincenzo-petronio** [pagopa/io-app#1725]
**Descrivi il problema**
La dialog con la richiesta di abilitazione dei permessi del calendario contiene un messaggio di testo con l'ellipsize, quindi illeggibile.

**To Reproduce**
Con i permessi del calendario disabilitati, aprire Profilo -> Preferenze -> Calendario preferito

**Expected behavior**
C'è spazio per espandere il testo su più righe.

**Screenshots**
![Screenshot_20200425](https://user-images.githubusercontent.com/4283382/80273857-3e072380-86d6-11ea-80ff-e8dd7e545cac.jpg)

**Versione dell'app**
1.1.36624

**Smartphone (please complete the following information):**
HUAWEI P10 lite

**Comment by Undermaken** [comment]
https://www.pivotaltracker.com/story/show/173529079

**Comment by Undermaken** [comment]
fixed https://github.com/pagopa/io-app/pull/2110
