### ISSUE TITLE
@pagopa/react-native-cie should be available without authentication

### ISSUE THREAD

**Issue by bfabio** [pagopa/io-app#1740]
io-app depends on @pagopa/react-native-cie, which is available only on Github Packages.

This forces the developer to go through the annoying procedure generating the token and setting it up just for that dependency, adding complexity to an already complex setup procedure.

@pagopa/react-native-cie should available on ~~npm.org~~ npmjs.com (and possibly have it's own github repo).

**Comment by Undermaken** [comment]
We are considering to move to npm in place of github packages.
Meanwhile the repo of react-native-cie is open from the day one
https://github.com/pagopa/io-cie-android-sdk

**Comment by bfabio** [comment]
@Undermaken Thanks, I missed that!

**Comment by strk** [comment]
Following the instructions in the README brings you to the `yarn install` step, which fails installing the `cie` module for this authentication issue:
> error An unexpected error occurred: "https://npm.pkg.github.com/download/@pagopa/react-native-cie/0.2.2/5594a38025e8a0ea446e1b933a966f767679975bee47707234585bd9598b092f: Request failed \"401 Unauthorized\"".

Shall instructions be updated to avoid the auth wall ?

**Comment by bfabio** [comment]
@strk 

The documentation already states:
> **Dependencies**
> [...]
> The configuration is pretty simple and fast, you can follow [these instructions](https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-npm-for-use-with-github-packages) If you don't do this step you can't download and install the cie module.

But I'd argue the simplest and fastest configuration is the one that doesn't exist, hence this issue.

**Comment by strawberry-code** [comment]
I am still facing this authorization issue, probably it's unclear to me how to configure `.npmrc`. I generated a personal TOKEN on GitHub giving *repo*, *read:packages* and *workflow* scopes. I configured my `~/.npmrc` as follows:

```
//npm.pkg.github.com/:_authToken=TOKEN
```

replacing obviously the TOKEN in `~/.npmrc`. Then I logged successfully to *npm* by:

```
$ npm login --registry=https://npm.pkg.github.com
> Username: USERNAME
> Password: TOKEN
> Email: PUBLIC-EMAIL-ADDRESS
```

Finally, I created a new `<io-app>/.npmrc` as follows:

```
registry=https://npm.pkg.github.com/download/@pagopa
```

I tried also: `registry=https://npm.pkg.github.com/download/pagopa`, without success.

Running `yarn install` I still give:

```
yarn install v1.22.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "https://npm.pkg.github.com/download/@pagopa/react-native-cie/0.2.2/5594a38025e8a0ea446e1b933a966f767679975bee47707234585bd9598b092f: Request failed \"401 Unauthorized\"".
info If you think this is a bug, please open a bug report with the information provided in "/Users/shinigami/pwc/io-app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Please, help

**Comment by Undermaken** [comment]
This is how my file looks like `~/.npmrc `

`//npm.pkg.github.com/:_authToken=my_github_token% `

**Comment by Undermaken** [comment]
https://github.com/pagopa/io-app/pull/2754
