### ISSUE TITLE
Errore comando 'pod install'

### ISSUE THREAD

**Issue by priami93** [pagopa/io-app#1749]
**Problema**
Nel lanciare il comando 'pod install' dentro la cartella 'ios', ho questo errore:
"[!] No podspec found for `ReactNativePermissions` in `../node_modules/react-native-permissions`"
**To Reproduce**
1. cd ios
2. pod install

**Screenshots**
![Schermata 2020-05-01 alle 11 16 32](https://user-images.githubusercontent.com/56170549/80795626-44e1da80-8b9d-11ea-9056-a7afcf028cdd.png)

**Comment by Undermaken** [comment]
ti consiglio di eliminare la cartella dei pod files e rieseguire il comando.
dalla root del progetto
`cd ios && rm -r Pods && rm Podfile.lock && cd .. && pod install`

**Comment by fabriziofff** [comment]
With the latest updates from react-native it should be easy to install pods without problems, feel free to open another issue if you still run into problems!
