### ISSUE TITLE
Inconsistency in PIN inputs screens

### ISSUE THREAD

**Issue by bfabio** [pagopa/io-app#1754]
The CIE PIN input screen uses different components than the app lock PIN input, it would be nice to have the same look for both.

Also, the backspace button in the custom PIN input is at the bottom right, where usually there's the "Enter" button on a standard Android pinpad.

Android 9, v1.1.36624.

**CIE PIN input**
![IMG_20200504_115213](https://user-images.githubusercontent.com/788293/80960393-0d776600-8e09-11ea-94bc-68ea57fd4314.jpg)

**Lock PIN input**
![Screenshot_20200504-115325_IO](https://user-images.githubusercontent.com/788293/80960415-1700ce00-8e09-11ea-8785-37f23a154fd8.png)
![Screenshot_20200504-121319_IO](https://user-images.githubusercontent.com/788293/80960416-1831fb00-8e09-11ea-87ca-d7005e0fe3be.png)

**Comment by bfabio** [comment]
@fabriziofff this was closed for being stale but IMO is still valid (up to you to decide if it's a wontfix or not though)

**Comment by fabriziofff** [comment]
Maybe @thisisjp could give us a feedback about this topic.
My (totally) personal point of view is that the CIE pin and the app pin are two different things and it is right that their use is characterized by a different interface ( I see the CIE pin more likely a non-blocking input that should be inserted, like the credit card number).

**Comment by thisisjp** [comment]
@bfabio thanks for your feedback. However, our goal is not to mix different codes used for different use cases. All the "external" credentials (such as SPID or CIE) have a different visual treatment compared to our "native" credentials (aka "codice di sblocco").

**Comment by bfabio** [comment]
@fabriziofff @thisisjp sounds fair, thanks for the explanation :+1:
