### ISSUE TITLE
cambio password obbligatorio: SPID Poste Italiane

### ISSUE THREAD

**Issue by strk** [pagopa/io-app#2068]
Ogni volta che inserisco nome e password dello SPID di Poste Italiane dall'interno della IO App mi viene chiesto di cambiare password. In qualche modo l'operazione invalida la vecchia password, come se Poste Italiane non si fidasse del modo in cui IO app invia la password (lo fa forse in chiaro?)

**Comment by simgunz** [comment]
Confermo il problema.

**Comment by strk** [comment]
Con l'aggiornamento della app alla versione 1.21.0.5.10072700 il problema per me non c'e' piu' (non so se a causa dell'aggiornamento della IO app o del servizio delle poste). Chiudo il ticket. @simgunz riaprilo pure se hai ancora il problema

**Comment by simgunz** [comment]
Confermo che il problema sembra essersi risolto.
