### ISSUE TITLE
[Android] Riautenticazione ad ogni cambio schermata

### ISSUE THREAD

**Issue by djechelon** [pagopa/io-app#2108]
Stamattina pagavo il bollettino TARI. Ho notato che la procedura è stata leggermente macchinosa, ma non ho avuto in mente di fare screen recording.

Premessa 1: **ero costretto** a usare nuova carta di credito
Premessa 2: uso l'autocompletamento con Keepass2 Android (e Keepass magari la usiamo in 3, di cui solo io uso Io app)
Premessa 3: altri utenti vorrebbero poter usare Google Wallet per autocompletare numeri di carta

Nella schermata di inserimento del numero di carta (non trovo la mia vecchissima issue sui dati che scompaiono), **devo** aprire una seconda app per recuperare il numero di carta e fare auto completamento.

Apro Keepass2, cerco i dati della carta e l'intent mi fa rientrare su Io. Io mi chiede nuovamente la password/impronta.

Ho già scritto alcune volte relativamente alla sicurezza, che va bilanciata con la usability. Ho distolto il focus dalla schermata di Io per meno di 10 secondi, già mi chiede di riautenticarmi?

Abbiamo detto che sicurezza va benissimo, magari però leggermente meno spinta a questi livelli.

## Proposta

Anzichè richiedere la riautenticazione ad ogni perdita del focus sulla activity, propongo di considerare almeno un timer di qualche minuto.

Casi d'esempio: le stesse app di home banking ti permettono di cambiare schermata e rientrare senza riautenticare.

Riformulo la proposta: analizzare il caso d'uso in cui l'utente usa Google Wallet per fare autocompletamento dei dati della carta di credito per migliorare l'esperienza utente

## Come replicare

- Andare sulla schermata di inserimento della nuova carta di credito per PagoPA
- Uscire col tasto home o cambiare app col task manager
- Dal task maanger rientrare in Io
- Viene chiesta di nuovo la login

**Comment by monga** [comment]
Aggiungo che con la nuova versione io non riesco più a fare login: l'app per spid e il mio keychain (uso pass) risiedono entrambi sul telefono e dovrei cambiare schermata 2 volte. Il meccanismo attuale rende il sistema *meno* sicuro, infatti potrei forse riuscire a loggarmi di nuovo se facessi le seguenti cose:
- usassi una password breve e memorizzabile facilmente per SPID (attualmente è di 20 caratteri generati casualmente da pass)
- generassi il pin otp SPID prima di tentare di loggarmi in IO (molto sconveniente)

**Comment by monga** [comment]
Nella nuova versione (1.6.0.2, con Android 9) il problema sembra essere risolto.

**Comment by Undermaken** [comment]
In beta interna stiamo testando una versione che non richiede l'autenticazione quando l'app va in background/foreground in fase di inserimento carta di credito. Ed inoltre abbiamo esteso la possibilità di fare screenshots (Android) ovunque tranne che nella schermata inserimento carta di credito

https://github.com/pagopa/io-app/pull/2250
https://github.com/pagopa/io-app/pull/2237

**Comment by monga** [comment]
Il problema è riemerso. In questo momento con l'app IO e lo spid di Inforcert sullo stesso dispositivo non c'è verso di fare di login.

**Comment by monga** [comment]
Confermo, il problema rimane.
