### ISSUE TITLE
[Android] Screen brightness remains locked after watching the codice fiscale screen

### ISSUE THREAD

**Issue by slinkydeveloper** [pagopa/io-app#2112]
**Descrivi il problema**
After watching the codice fiscale screen, if I lock the screen and I unlock it again, the screen brightness control remains locked as soon as i remain inside the app

**To Reproduce**
1. Go to codice fiscale screen
1. The screen brightness changes and locks to a fixed value
1. Lock the screen
1. Unlock the screen
1. Go back to any other screen of the application
1. Brightness doesn't go back to the previous value and, if you try to change the brightness from the system ui top bar controls, it doesn't work

If I close the application using the system ui, then i get back the control of brightness

**Expected behavior**
The brightness control unlocks (or better, the brightness goes back to the original one) when I change screen after unlocking the phone.

**Versione dell'app**
Copia i due numeri che appaiono in alto a destra nello schermo dell'app.

**Smartphone (please complete the following information):**
 - Device: Sony Xperia G8231
 - OS: Android 8.0

**Additional context**
I experience the same issue with Huawei P8 Lite 2017, Android 8.0

**Comment by fabriziofff** [comment]
Thanks for the report and sorry for the delay! 
The bug is fixed in https://github.com/pagopa/io-app/pull/3313
