### ISSUE TITLE
Tracker nell'app Android

### ISSUE THREAD

**Issue by giocomai** [pagopa/io-app#2162]
Secondo questo servizio dedicato - https://reports.exodus-privacy.eu.org/en/reports/143723/#trackers - l'app android attualmente disponibile sul Play Store include quattro tracker:

- Google AdMob
- Google Firebase Analytics
- Instabug
- MixPanel

In particolare, secondo lo stesso servizio, Google AdMob sarebbe presente solo a partire dalla versione 1.5.0.3, ma non nelle precedenti - https://reports.exodus-privacy.eu.org/en/reports/search/it.pagopa.io.app/.

_Se_ sono tutti effettivamente necessari, e _se_ non è possibile renderli opzionali, mi sembrerebbe quantomeno utile spiegarne molto concisamente la funzione e quali dati vengono condivisi con relativi enti terzi al primo avvio, come parte del processo di accettazione delle condizioni di utilizzo. 

Rimuovere o rendere "opt-in" questi tracker (ad esempio, per chi vuole contribuire allo sviluppo della beta) sarebbe comunque la soluzione preferibile.

**Comment by pietro909** [comment]
A partire da Giugno 2021 sono state introdotte delle schermate informative sulla privacy e la possibilita' di escludere la condivisione di dati personali. 
Informazioni estese sono disponibili qui https://io.italia.it/app-content/tos_privacy.html
