### ISSUE TITLE
circolo vizioso non permette accesso alla App

### ISSUE THREAD

**Issue by GPaso** [pagopa/io-app#2213]
**Descrivi il problema**
Non riesco ad accedere alla app, quando confermo l' accesso da PosteID e torno sulla App IO mi richiede le credenziali di accesso per poi richiedermi la conferma, creando un circolo vizioso.

**To Reproduce**
1. Start the app
2. Login with email and passw (PosteID)
3. Go to PosteID app and allow the login
4. Back to IO app 

**Versione dell'app**
1.6.0.2

**Smartphone (please complete the following information):**
 - Device: Moto C Plus
 - OS: Android 7.0

**Comment by Undermaken** [comment]
@raicastino riesci a fornire qualche consiglio?

**Comment by raicastino** [comment]
Dalla descrizione del problema sembra un caso molto particolare, come se l'app venisse chiusa e riavviata quando viene messa in background perdendo ciò che si stava facendo. La causa del problema potrebbe essere riconducibile a un comportamento che si manifesta su quel particolare tipo di device o dovuto a un problema con l'account di PosteID quando utilizzato per entrare su una app.

Per capire quale è la causa del problema, sarebbe utile capire se problemi analoghi si verificano eseguendo una procedura di accesso su un'app diversa da IO con le stesse credenziali SPID (Livello 2). Ad esempio provando ad autenticarsi con le credenziali SPID nella app "INPS mobile".

**Comment by GPaso** [comment]
Ho provato ad effettuare l'accesso con SPID anche tramite l'app "INPS mobile" ed il problema persiste.
A quanto capisco, l'app deve rimanere aperta in background per poter proseguire con l'accesso, quindi la memoria del dispositivo potrebbe essere il problema. Preciso che il mio dispositivo dispone di 0.88 GB della quale 80% sembra essere costantemente usato dall' OS.

**Comment by pasqualedevita** [comment]
Quando torni su "IO" o "INPS Mobile" vedi la schermata di inserimento delle credenziali di PosteID oppure l'app riparte come se fosse stata chiusa e quindi devi selezionare "Entra con SPID" -> "PosteID" -> ecc?

**Comment by GPaso** [comment]
Il comportamento è diverso per le due app!

Nel caso di "IO" la app riparte come se fosse stata chiusa.

Nel caso di "INPS mobile" rimane la schermata delle credenziali, come se le chiedesse nuovamente (campi vuoti).

**Comment by pasqualedevita** [comment]
A questo punto ti consigliamo di aprire un ticket di supporto a Poste Italiane e segnalare che hai problemi di accesso sia su "IO" che su "INPS Mobile". Nel ticket è importante che tu segnali che il problema si verifica per entrambe le applicazioni.

Se dopo il ticket con Poste riesci a risolvere il problema, sarebbe molto utile un tuo feedback soprattutto su cosa è stato fatto da Poste per "sbloccare" il tuo profilo.

Grazie per la collaborazione.

**Comment by GPaso** [comment]
Grazie a voi!
Ho inviato una mail a Poste come consigliato. Nel frattempo sono riuscito a provare con due dispositivi, uno con la app "IO" ed il secondo con "PosteID", in questo caso la conferma avviene correttamente e sono riuscito ad accedere all'app.

**Comment by raicastino** [comment]
Perfetto, vediamo se l'assistenza di PosteID riesce a fornire una soluzione. Nella prova che hai fatto ci confermi di essere riuscito ad autenticarti con SPID sull'app IO che avevi sul tuo dispositivo (Moto C Plus) avendo installato ed utilizzato l'app PosteID per autorizzare l'accesso su un altro dispositivo? Con questa modalità riesci quindi ad autenticarti su tutte le app che richiedono SPID Livello 2 di Poste (es. app IO, app INPS mobile) mentre se durante procedura di login viene effettuato lo "swap" tra le due app (ad esempio perché installate sullo stesso dispositivo) non funziona.

**Comment by GPaso** [comment]
@raicastino Confermo, sono riuscito ad autenticarmi e ad usare la app IO!

**Comment by pasqualedevita** [comment]
Da quello che ci descrivi ipotizziamo un comportamento particolare del tuo dispositivo Moto C Plus nella gestione dei processi in background.

Ti forniamo alcuni step che puoi eseguire per aiutarci a capire:
1. assicurati di aver abbastanza spazio sul tuo dispositivo (spazio di archiviazione e memoria interna)
1. disattiva il risparmio energetico del tuo dispositivo
1. disattiva l'ottimizzazione della batteria per App IO e PosteID
1. disattiva tutte le limitazioni in background per App IO e PosteID (dovrebbero essere disponibili in "Impostazioni" > "App" > "IO" e "PosteID")
1. se hai attivato le "Opzioni Sviluppatore", nella sezione "Applicazioni" assicurati di aver disabilitato "Non mantenere le attività" e "Limite di processi in background" impostato su "Predefinito"
1. appena vedi il messaggio "Torna al servizio" su PosteID torna subito su IO senza aspettare

Gli step suggeriti potrebbero cambiare o non essere presenti in base alla versione di Android.
Quando hai tempo, facci sapere l'esito dei test

**Comment by GPaso** [comment]
Scusate, mi sono preso un po di tempo per provare diverse volte.

Ho seguito gli step forniti per le app menzionate (IO, PosteID, INPS mobile).
Info riguardo la memoria:
> Storage: 12.59 GB of 23.15GB used
> Memory: Avg 766 MB of 0.88 GB memory used 

Per la app "INPS mobile" sono riuscito immediatamente seguendo esattamente gli stessi steps sopra menzionati.
Per la app "IO" sono riuscito ad effettuare la autenticazione solo dopo diversi tentativi, alla fine ha funzionato effettuando l'accesso subito dopo un reboot del telefono.

Direi che è proprio un problema dovuto al dispositivo.

**Comment by pasqualedevita** [comment]
Grazie @GPaso proprio qualche giorno fa abbiamo trovato lo stesso workaround per un altro dispositivo Android, lo Xiaomi Mi A2 Lite aggiornato ad Android 10. 

https://www.reddit.com/r/Xiaomi/comments/gt07s8/mi_a2_lite_switching_between_apps_causes_app_to/?utm_source=amp&utm_medium=&utm_content=post_body
