### ISSUE TITLE
Feature Request ISSUE template

### ISSUE THREAD

**Issue by bhack** [pagopa/io-app#2353]
Can you add a Feature Request ISSUE template other than BUG template?

**Comment by pietro909** [comment]
Not sure what you mean with _Feature Request ISSUE template_ @bhack
 
There are currently 3 templates available [here](https://github.com/pagopa/io-app/issues/new/choose) including _Feature Request_ and _Bug Report_. Does it answer your question?

**Comment by bhack** [comment]
Yes
