### ISSUE TITLE
Errore quando interroga PagoPA e non consente di inserire metodi di pagamento.

### ISSUE THREAD

**Issue by sasadangelo** [pagopa/io-app#2468]
**Descrivi il problema**
Quando accedo all'app per aggiungere un pagamento inizia a fare una query verso PagoPA che ci mette un vita e se non va mi dice:

Non è stato possibile caricare i metodi di pagamento, riprova per piacere.

Ora a me non interessa vedere le transazioni PagoPA, voglio solo inserire un metodo di pagamento ma non me lo fa fare semplicemente perché il bottone non appare. Appare solo quello di Bonus e Sconti.

**To Reproduce**
1. Login nell'app con lo SPID.
2. Cliccare su Portafoglio
3. Bisogna aspettare che l'app interroghi PagoPA per poter vedere il bottone di aggiungi pagamento.
4. Il bottone non appare nel caso di errore sopra.

**Expected behavior**
Il Bottone di aggiunta pagamento sia scorrelato alla query verso PagoPA. Se io voglio inserire un metodo di pagamento potrei non essere interessato alle transazioni già fatte.

**Screenshots**
n/a

**Versione dell'app**
1.9.0.4

**Smartphone (please complete the following information):**
 - Huawai P30 Lite
 - Android

**Additional context**
n/a

**Comment by giuliaok** [comment]
Ho riscontrato lo stesso identico problema.

**Comment by edo0** [comment]
Ho riscontrato il medesimo problema
Device: Pocophone F1
OS: LineageOS 16 (Android 9) con microG
![Screenshot_20201201-234630_IO](https://user-images.githubusercontent.com/16632292/100805878-be8dbf80-342f-11eb-8953-77de343dbaf8.png)

**Comment by thisisjp** [comment]
**Grazie per le segnalazioni!**
Abbiamo pubblicato su Twitter [questo thread](https://twitter.com/IOitaliait/status/1334089466957471744) per spiegare cosa sta succedendo, e cosa stiamo facendo per risolvere questo problema temporaneo.

**Comment by sasadangelo** [comment]
Sembra risolto.
Grazie

**Comment by sasadangelo** [comment]
Purtroppo sembrava risolto ma il problema di tanto in tanto riappare.
Ho letto i twitter, quindi attendo con fiducia.

**Comment by LupoBianco** [comment]
se può aiutare il logcat torna questo errore

`E/t.pagopa.io.ap: Invalid ID 0x00000087.
E/ResolverController: No valid NAT64 prefix (102, <unspecified>/0)`

sia quando si tenta di salvare la carta, sia quando si clicca su Riprova

**Comment by sasadangelo** [comment]
A me sembra risolto.
