### ISSUE TITLE
Changelog poco comprensibile

### ISSUE THREAD

**Issue by vincenzo-petronio** [pagopa/io-app#2494]
**Descrivi il problema**
Secondo l'Accademia della Crusca il gergo informatico utilizzato nel changelog è poco comprensibile.

[Gruppo Incipit, Comunicato n. 15: L’applicazione IO della Pubblica Amministrazione](https://accademiadellacrusca.it/it/contenuti/gruppo-incipit-comunicato-n-15-emlapplicazione-io-della-pubblica-amministrazioneem/8094)

**Expected behavior**
Una descrizione più comprensibile ai non addetti ai lavori.

**Versione dell'app**
1.10.0.5

**Comment by pietro909** [comment]
I changelog piu' recenti sono scritti in un Italiano piu' comprensibile al grande pubblico (puoi controllare ad esempio: https://play.google.com/store/apps/details?id=it.pagopa.io.app)
