### ISSUE TITLE
Tastiera sovrapposta a input form IBAN 

### ISSUE THREAD

**Issue by aaandri98** [pagopa/io-app#2505]
**Descrivi il problema**
Quando attivo il form per inserire il codice IBAN nella sezione Cashback, la tastiera si sovrappone al form, rendendo impossibile selezionarla a mano per procedere all'azione di incollare il codice. La scrittura manuale non è impedita da questo bug.

**To Reproduce**
1. Apri la sezione portafoglio
2. Attiva il servizio di cashback
3. Ritorna ai metodi di pagamento
4. Apri la sezione cashback
5. Clicca il bottone aggiungi IBAN
6. Attiva l'input form

**Expected behavior**
Il movimento della tastiera verso l'alto, non dovrebbe impedire la visualizzazione dell'input form, ma dovrebbe farlo scorrere verso l'alto. inoltre dovrebbe essere possibile compiere l'azione di incollare il codice IBAN.

**Screenshots**
[IMG_2832](https://user-images.githubusercontent.com/36881388/101324310-52192300-386a-11eb-8fbb-c1693050995d.PNG)
[IMG_2833](https://user-images.githubusercontent.com/36881388/101324317-53e2e680-386a-11eb-8537-4a6fabfd98d8.PNG)

**Versione dell'app**
1.11.0.2

**Smartphone (please complete the following information):**
 - Device: iPhone SE 2016
 - OS: iOS 14.3

**Comment by fabriziofff** [comment]
Ciao, grazie per la segnalazione.
La problematica è tracciata nella story https://www.pivotaltracker.com/story/show/176025252

**Comment by pietro909** [comment]
Duplica https://github.com/pagopa/io-app/issues/2510 che e' stata chiusa da https://github.com/pagopa/io-app/pull/2511
