### ISSUE TITLE
Impossibile andare "indietro" in schermata cashless

### ISSUE THREAD

**Issue by djechelon** [pagopa/io-app#2509]
**Descrivi il problema**
Dalla schermata principale di cashless non è possibile usare il tasto hardware "indietro" o lo swipe per tornare alla schermata precedente, ma solo il testo indietro in alto nella schermata.

**To Reproduce**
1. Accedere alla schermata di gestione del cashless
2. Usare il tasto hardware per tornare indietro. Fallisce

**Screenshots**
![Screenshot_20201207-123636.png](https://user-images.githubusercontent.com/3042285/101347039-bdbeb880-3889-11eb-8760-f6da267322eb.png)

**Versione dell'app**
1.11.0.2

**Smartphone (please complete the following information):**
 - Device: Pixel 5 5g
 - OS: AOSP 11

**Additional context**
Il Pixel 5 introduce una nuova funzionalità tale per cui "indietro" si va (in tutte le applicazioni) con un rapido swipe del bordo destro o sinistro dello schermo.

**Comment by CrisTofani** [comment]
Issue will be resolved by #2489 😄  thx for reporting!
