### ISSUE TITLE
iPhone SE 1st - form inserimento IBAN - tastiera e pulsanti coprono campo di test

### ISSUE THREAD

**Issue by mirchaemanuel** [pagopa/io-app#2510]
**Descrivi il problema**
App iOS v 1.11.0

Nella schermata di inserimento IBAN, utilizzando un iPhone SE 1st, il campo di testo viene coperto dai pulsanti di salvataggio e dalla tastiera e diventa impossibile incollare del testo.

**To Reproduce**
1. cashback
2. inserimento IBAN
3. cliccare sul campo di testo

**Expected behavior**
Il campo di testo dovrebbe essere in primo piano, cliccabile e con la possibilità di incollare del testo

**Screenshots**

![IMG_A3F7D0FDC944-1](https://user-images.githubusercontent.com/1971953/101348830-987f7980-388c-11eb-8226-aba55a2e6b5b.jpeg)

**Versione dell'app**
1.11.0

**Smartphone (please complete the following information):**
 - Device: iPhone SE 1st
 - OS: iOS 14

**Comment by fabriziofff** [comment]
Grazie per la segnalazione, il bug viene risolto in https://github.com/pagopa/io-app/pull/2511
