### ISSUE TITLE
Schermata Carta di credito allegata a richiesta supporto senza consenso dell'utente

### ISSUE THREAD

**Issue by alancivita** [pagopa/io-app#2520]
Durante l'inserimento del metodo di pagamento mi va in errore e quando clicco il ? per chiedere supporto, si apre una schermata di aiuto e noto che viene allegato lo screenshot della mia carta di credito, con i numeri da me precedentemente digitati, la scadenza e fortunatamento NON il CVV. 
Perlomeno l'utente dovrebbe essere avvisato che la sua carta di credito sta per essere inoltrata da qualche parte.

Per riprodurre la situazione:
Aggiungi metodo di pagamento
Carta di credito, debito o prepagata
Nel tentativo di salvare la carta, va in errore; Si è verificato un errore temporaneo nel salvataggio di questa carta, riprova.
Cliccare su Annulla
Cliccare sul punto di domanda in alto a Destra
Andare nella sezione Hai bisogno di Aiuto?
e cliccare su Scrivi al team di IO
a quel punto viene automaticamente allegata l'ultima schermata aperta, appunto quella della Carta di credito con tutti i dettagli inseriti.

**Comment by Undermaken** [comment]
Ciao. Grazie per la segnalazione.
Abbiamo valutato la tua proposta e abbiamo reso l'app configurabile in tal senso.
Nella prossima versione gli screenshots sono disabilitati nella schermata di inserimento carta di credito.
Stiamo valutando su dove altro estendere questa configurazione

https://github.com/pagopa/io-app/pull/2537

**Comment by fabriziofff** [comment]
Implemented in https://github.com/pagopa/io-app/pull/2537
