### ISSUE TITLE
Non è stato possibile caricare i metodi di pagamento, riprova per piacere

### ISSUE THREAD

**Issue by davtorgh** [pagopa/io-app#2522]
**Descrivi il problema**
Sezione *portafoglio*: nella parte in alto compare la scritta "Non è stato possibile caricare i metodi di pagamento, riprova per piacere", seguita da un pulsante riprova. Nessun metodo di pagamento visualizzato.

**To Reproduce**
 1. vai nella sezione *portafoglio*;
 2. click su *AGGIUNGI*;
 3. aggiunto "Caschback" con esito positivo;
 4. saltato inserimento IBAN;
 5. inserimento carta circuito VISA;
 6. al momento della verifica della carta appare un messaggio che segnala l'impossibilita a procedere ed invita a riprovare;
 7. riprovato più volte sempre con esito negativo;
 8. rientro nell'app, dopo alcune ore, con digitazione codice di sblocco;
 9. nella sezione *portafoglio*, nella parte in alto compare la scritta "Non è stato possibile caricare i metodi di pagamento, riprova per piacere", seguita da un pulsante riprova;
 10. riprovato più volte sempre con esito negativo.

**Expected behavior**
La carta viene aggiunta al portafoglio e viene visualizzata tra i metodi di pagamento.

**Versione dell'app**
Versione 1.11.0.2

**Smartphone (please complete the following information):**
 - device Huaway P Smart;
 - OS Android 9 (EMUI 9.1.0, build 9.1.0.175).

**Comment by NiccoloSegato** [comment]
Il problema è stato risolto con la versione 1.14.0.1
