### ISSUE TITLE
iPhone SE 1st - view "Le tue transazioni" - testo guida non scrollabile

### ISSUE THREAD

**Issue by mirchaemanuel** [pagopa/io-app#2547]
**Descrivi il problema**
App iOS v. 1.13.0

**To Reproduce**
portafoglio -> Cashback -> Dettaglio transazioni
La Scrollview con le indicazioni che le transazioni saranno disponibili entro 72 ore non è scrollabile in alto e quindi non è possibile leggere tutto il testo.

**Expected behavior**
La Scrollview dovrebbe permettere lo scroll di tutto il testo in modo da poterlo leggere.

**Screenshots**
![IMG_3462B68FA030-1](https://user-images.githubusercontent.com/1971953/101690984-4dbd5780-3a6e-11eb-8823-327d5b3dd31a.jpeg)

**Versione dell'app**
1.13.0

**Smartphone (please complete the following information):**
 - Device: iPhone SE 1st
 - OS: iOS 14

**Comment by mirchaemanuel** [comment]
È possibile forzare lo scroll di qualche riga effettuando uno swype senza alzare il dito... ma non è possibile leggere tutto il testo.

**Comment by CrisTofani** [comment]
Hello we included the fix on this issue in the PR #2550 I'm going to close this issue 🙂  thx!
