### ISSUE TITLE
Mancata visualizzazione card dei pagamenti su android 11

### ISSUE THREAD

**Issue by ste71m** [pagopa/io-app#2549]
Spulciando i log si vedono vari errori
In allegato il log completo
[Io.txt](https://github.com/pagopa/io-app/files/5671149/Io.txt)

12-10 08:23:08.060 26128 26224 W ReactNativeJS: Animated.event now requires a second argument for options
12-10 08:23:08.172 26128 26128 W FrescoIoBoundEx: type=1400 audit(0.0:1573): avc: granted { execute } for path="/data/user/0/it.pagopa.io.app/lib-0/libimagepipeline.so" dev="sda13" ino=807993 scontext=u:r:untrusted_app_29:s0:c46,c257,c512,c768 tcontext=u:object_r:app_data_file:s0:c46,c257,c512,c768 tclass=file app=it.pagopa.io.app
12-10 08:23:08.206 26128 26224 W ReactNativeJS: Animated.event now requires a second argument for options
12-10 08:23:08.338 26128 26224 W ReactNativeJS: Animated.event now requires a second argument for options
12-10 08:23:08.370 26128 26224 W ReactNativeJS: Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false`

12-10 08:27:59.222 26128 26128 E t.pagopa.io.ap: Invalid ID 0x00000095.

12-10 08:34:43.189 27268 27268 E SoLoader: couldn't find DSO to load: libjscexecutor.so caused by: couldn't find DSO to load: libjsc.so result: 0 result: 0
12-10 08:34:43.233 27268 27330 W System.err: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZTIN8facebook6hermes8debugger13EventObserverE" referenced by "/data/user/0/it.pagopa.io.app/lib-0/libhermes-inspector.so"...
12-10 08:34:43.233 27268 27330 W System.err:    at java.lang.Runtime.load0(Runtime.java:939)

**Comment by fabriziofff** [comment]
Ciao, ci puoi dare qualche dettaglio in più, ad esempio:
- descrivendo il comportamento aspettato vs cosa si verifica 
- modello del device usato

Se potessi allegare anche uno screenshot sarebbe perfetto, grazie!

**Comment by ste71m** [comment]
Il telefono è un Pixel 2 XL
Lo spinner di caricamento delle carte girava all'infinito senza mai riuscire a caricare nulla
Stranamente quando ho provato a riaggiungere una carta pagobancomat aggiunta in precedenza ha caricato tutte le carte
