### ISSUE TITLE
Transazioni Sumup non vengono considerate

### ISSUE THREAD

**Issue by claudiofus** [pagopa/io-app#2561]
**Descrivi il problema**
Ho effettuato 2 transazioni l'8 dicembre e sono state contabilizzate dalla mia Banca. La transazione effettuata con SumUp non è stata riconosciuta mentre l'altra è visibile nell'app. Oltretutto SumUp dovrebbe essere un circuito abilitato all'uso del cashback come indicato [qui](https://sumup.it/cashback-pos/).

**To Reproduce**
1. Dopo aver collegato una carta di debito e attivato il cashback dall'app IO
2. Effettuare un pagamento presso un esercente con SumUp
3. Attendere che l'operazione venga contabilizzata
4. Attendere il giorno successivo alla contabilizzazione e verificare se presente nell'app IO

**Expected behavior**
Conteggiare la transazione per il cashback

**Versione dell'app**
1.14.0.1

**Smartphone (please complete the following information):**
 - Device: Samsung A51
 - OS: Android 11

**Comment by thisisjp** [comment]
Ciao,
all’avvio del Cashback, alcuni Esercenti potrebbero non disporre da subito di un POS che ti consente di partecipare all’iniziativa. In [questa pagina](https://io.italia.it/cashback/acquirer) trovi la lista dei soggetti (detti "Acquirer") che supportano le transazioni per il Cashback. SumUp non è ancora ufficialmente attivo, ma lo sarà nei prossimi giorni.

Se hai altre domande, consulta le [FAQ](https://io.italia.it/cashback/faq) o leggi la [Guida](https://io.italia.it/cashback/guida).

Chiudo la issue perché non si tratta di un problema strettamente legato all'app. Se dovessi aver bisogno di assistenza, utilizza la sezione apposita in app, grazie :)

**Comment by jack1852** [comment]
Ciao, secondo SumUp loro sono abilitati al cashback (https://sumup.it/blog/cashback-sumup/) quindi pare strano che non lo siano lato PagoPa.

**Comment by claudiofus** [comment]
Anche a me è parso strano e ho inviato una richiesta a SumUp via mail tramite il loro sito. Purtroppo non ho ancora ricevuto risposta.

**Comment by thisisjp** [comment]
Ciao a tutti,
vi confermo che SumUp è ora un Acquirer Convenzionato, dovreste già vedere in app le vostre transazioni **a partire dal 9 dicembre**. Le informazioni aggiornate sono sempre riportate nella pagina [Acquirer Convenzionati](https://io.italia.it/cashback/acquirer).
