### ISSUE TITLE
"Translated with www.DeepL.com/Translator (free version)" disclaimer in help pages

### ISSUE THREAD

**Issue by edocod1** [pagopa/io-app#2565]
**To Reproduce**
1. Go to the credit card section and try to add a card
2. Press "?" at the top
3. Press on "Why is the saving unsuccessful?"

**Expected behavior**
A beautiful homemade translation.

**Actual behaviour**
The app shows that the kb has been machine translated with disclaimers

**Comment by thisisjp** [comment]
Thanks for your contribution, this [PR](https://github.com/pagopa/io-app/pull/2567) should solve the issue.
