### ISSUE TITLE
Informazioni sul tipo di memorizzazione delle informazioni relative ai dati di pagamento

### ISSUE THREAD

**Issue by Simulacron-3** [pagopa/io-app#2566]
Ciao,

questa segnalazione non è assolutamente un bug. Vorrei solo avere qualche informazione sui metodi con cui vengono memorizzati  i dati relativi ai metodi di pagamento(numero carta, scadenza e codice di verifica). Per intenderci se un malintenzionato dovesse per assurdo trovare un modo per accedere a questi dati, potrebbe utilizzarli a proprio uso e consumo?

Se ho sbagliato sezione per la richiesta, eliminate pure.

Grazie :)

**Comment by alfredonodo** [comment]
Si questo è molto interessante soprattutto in seguito al [comunicato stampa ufficiale](https://www.pagopa.gov.it/it/pagopa-spa/comunicati-stampa/2020-12-11-comunicato) dal quale si evince chi sono i fornitori di servizi.

**Comment by pachainti** [comment]
Per motivi di trasparenza sarebbe opportuno conoscere in dettaglio quali dati sono salvati da ogni fornitore e con quali protezioni crittografiche ovvero quali sono le garanzie sia nell'utilizzo quotidiano sia in caso di data breach.
Grazie

**Comment by NiccoloSegato** [comment]
Sebbene non sia un comunicato ufficiale, [questo](https://www.hdblog.it/sicurezza/articoli/n530979/cashback-dati-carte-conti-io-privacy/) articolo su HDBlog spiega bene come vengono utilizzati i dati.

**Comment by pachainti** [comment]
Grazie per l'articolo, purtroppo non aggiunge quasi niente di nuovo rispetto al comunicato ufficiale relativamente alle garanzie sulle protezioni dei dati.

**Comment by Simulacron-3** [comment]
Grazie per la segnalazione :) avevo già letto queste informazioni. Come dice giustamente @pachainti non risponde pienamente alla nostra richiesta. In particolare mi piacerebbe sapere le specifiche tecniche utilizzate da "hash PAN"(in merito alla parola hash voglio sperare che non si tratti di hash MD5 :D )

**Comment by Undermaken** [comment]
Ciao. L'app, cosi come tutta l'infrastruttura IO, non memorizza alcuna informazione sensibile relativa ai metodi di pagamento.
Le informazioni degli strumenti di pagamento sono custodite nella infrastruttura di [SIA](https://www.sia.eu/it/gruppo-sia/compliance), nostro partner tecnologico, certificato PCI  e non transitano mai nell'app (solo in fase di inserimento dello strumento di pagamento, su memoria volatile)

Quando viene rappresentato in app, uno strumento di pagamento, è presente in memoria come mostrato in questa immagine
![Schermata 2021-02-02 alle 19 09 43](https://user-images.githubusercontent.com/822471/106643610-3f7d4a80-658a-11eb-9d76-aa82be54bff5.png)

L'algoritmo di hashing usato è SHA256 del pan della carta + un SALT

**Comment by pachainti** [comment]
Grazie, quindi eseguite hash(message+salt) o HMAC?

**Comment by Undermaken** [comment]
L'app non applica alcuna funzione, legge quella informazione ove necessario (ad esempio per ricondurre una transazione del cashback allo strumento che l'ha prodotta). Viene usato come un identificativo.
Viene fatto sha256(SALT + pan) lato server.

L'app non ha necessità di leggere quel dato "in chiaro", in alcuna occasione, poiché non lo usa mai attivamente (per pagare, ad esempio). 

Non viene usato l'HMAC nello scambio dei messaggi e quindi l'app non custodisce nessun secret internamente

**Comment by alfredonodo** [comment]
Quindi, se ho capito bene, l'applicazione non memorizza alcun dato di pagamento. Tuttavia tali dati sono memorizzati sul server in chiaro e inviati con sha256(SALT + pan) invece di hmac. Come vengono inviati i dati relativi ai metodi di pagamento al server?

**Comment by Undermaken** [comment]
I dati sono custoditi da SIA cifrati. Non conosco nello specifico l'algoritmo di cifratura.
Ad ogni operazione di lettura, da parte del client, vengono estratti solo quelli utili a formare la risposta ed inviati su https

Il client, l'app, invia i dati della carta su https in fase di registrazione. Da quel momento in poi l'app non avrà mai in risposta il pan e il cvv ma solamente l'hash del pan e un id numerico che userà per identificare gli strumenti di pagamento ed utilizzarlo (es: voglio pagare con lo strumento con id: 12345)

**Comment by alfredonodo** [comment]
Un [nuovo comunicato ufficiale](https://www.garanteprivacy.it/home/docweb/-/docweb-display/docweb/9668146) del garante per la protezione dei dati personali blocca provvisoriamente alcuni trattamenti di dati che prevedono l’interazione con i servizi di Google e Mixpanel.

**Comment by pietro909** [comment]
@Simulacron-3 la discussione ti ha dato le risposte che cercavi? Possiamo chiudre la issue?

**Comment by Simulacron-3** [comment]
Sì grazie, si può chiudere.
