### ISSUE TITLE
Grafica tesserino codice fiscale

### ISSUE THREAD

**Issue by giovariot** [pagopa/io-app#2575]
Non so se sia un'idea saggia, perché rende sicuramente meno riconoscibile la scheda, però guardando la grafica molto minimal e molto curata dell'applicazione il tesserino del codice fiscale che spunta nella pagina del profilo sembra un po' fuori posto.

Proponevo quindi di indicare la tessera del CF con la grafica con cui vengono indicati i metodi di pagamento nel portafoglio con su scritto "Codice fiscale" e a lato al posto di quello del circuito bancario un logo (la prima cosa che mi veniva in mente era una bandierina).

**Comment by wizardgsz** [comment]
Curiosità: ma questo codice fiscale viene accettato anche in sostituzione di quello fisico oppure non serve a nulla?

**Comment by thisisjp** [comment]
Ciao,
grazie per il feedback!
Il tesserino presente nella sezione Profilo è un fac-simile, e può essere utilizzato per scansionare—tramite il codice a barre—il codice fiscale legato alla propria utenza SPID o CIE (es.: in farmacia).

Nella nostra [roadmap](https://io.italia.it/roadmap/#nextsteps) abbiamo lo sviluppo della sezione "Documenti", e sarà sicuramente l'occasione per migliorare la visualizzazione di questo documento.
