### ISSUE TITLE
Pulsante Indietro hardware in dettaglio transazione cashback

### ISSUE THREAD

**Issue by djechelon** [pagopa/io-app#2580]
**Descrivi il problema**
Il tasto indietro non funziona _coerentemente_ con la modale di descrizione di una singola transazione Cashback

**To Reproduce**
1. Entrare nella lista transazioni del cashback
2. Toccare una specifica transazione di cui si vogliono esaminare i dettagli
3. Fare indietro col tasto hardware

**Expected behavior**
La modale dovrebbe chiudersi.
Al contrario, la schermata _sotto_ torna indietro e la modale con la transazione rimane mostrata in primissimo piano

**Screenshots**
![Screenshot_20201214-093253](https://user-images.githubusercontent.com/3042285/102059470-39bc8180-3df1-11eb-8312-11c98ab3f2f2.png)

Nella schermata si vede che la modale è rimasta _appesa_ nonostante siamo rientrati alla schermata di portafoglio

**Versione dell'app**
Copia i due numeri che appaiono in alto a destra nello schermo dell'app.

**Smartphone (please complete the following information):**
 - Device: Pixel 5G
 - OS: AOSP 11 aggiornato dicembre 2020

**Comment by davcec** [comment]
Dovrebbero già averlo tracciato con PR #2614.
