### ISSUE TITLE
Aggiungere export transazioni Cashback

### ISSUE THREAD

**Issue by orson-69** [pagopa/io-app#2581]
**Descrivi il problema**
SI propone la seguente migliori: Aggiungere export transazioni Cashback.

**Expected behavior**
Possibilità di esportare, magari in formato CSV, su memoria teelfono o Google Drive e servizi simili, le transazioni registrate per il cashback

**Comment by djechelon** [comment]
**Upvoted**. Oggi ho scritto tramite IO chiedendo se fosse possibile ottenere uno scarico CSV/Excel e ovviamente mi è stato risposto, cordialmente, picche.
La funzionalità permetterebbe ad un utente di effettuare un confronto con l'estratto conto bancario per eventualmente individuare quelle transazioni che non fossero state conteggiate e provvedere eventualmente al reclamo CONSAP
