### ISSUE TITLE
Leggero sfarfallio  Icona Cashback

### ISSUE THREAD

**Issue by orson-69** [pagopa/io-app#2583]
**Descrivi il problema**
Leggero sfarfallio  Icona Cashback

**To Reproduce**
1. Click on '**Portafoglio**'
2. Scroll down fino a veder "**Cashback**"
4. L'icona Cash Back sulla destra **sfarfalla** alcuni decimi di secondo.

**Versione dell'app**
1.14.0.1

**Smartphone (please complete the following information):**
 - Device: Sony XA2
 - OS: Android 9

**Additional context**
Lo stesso problema si verifica se si tappa su **Aggiorna** nella sezione **Bonus e sconti**. Sembra che l'icona venga caricata 4 volte

**Comment by NiccoloSegato** [comment]
Verificando la segnalazione su iPhone 7 con iOS 14.2, app IO versione 1.14.0.1, il problema non si presenta.
@orson-69 hai modificato il refresh rate del tuo dispositivo?

**Comment by orson-69** [comment]
Non riesco a reimpostare il refresh rate nel mio telefono.
Non creo però dipenda da quello.
Riprovando ho osservato quanto segue.

Se clicco su Aggiorna di fianco a Bonus e Sconti, mi appare il banner del Cashback.
L'icona lampeggia 4 volte, poi il banner scorre in basso perché compare di sopra il banner del Bonus vacanze.
In quel momento smette di lampeggiare.
L'Icone del Bonus vacanze non presenta alcuna anomalia

Comunque provo anche con altri telefoni se riesco

**Comment by orson-69** [comment]
Testato con Iphone 8 e funziona tutto perfettamente.
Con LG K8, Android 8.1 invece si ripresenta il problema.

Mi sorge un dubbio che sia un problema legato ai terminali più lenti.
Provo ad inviare in allegato Screen recording del problema.
[video cashback.zip](https://github.com/pagopa/io-app/files/5701468/video.cashback.zip)

**Comment by orson-69** [comment]
Problema connche con samsung A 50

**Comment by orson-69** [comment]
Problema verificato anche con Samsung A50 Android 10

**Comment by wizardgsz** [comment]
Idem su Android Huawei ma non credo sia cosi' fondamentale una sua risoluzione... con tutti i problemi seri che ci sono :)

**Comment by orson-69** [comment]
Chiaro che non è un Bug prioritario come soluzione, però segnaliamo un po' tutti i problemi.

**Comment by fabriziofff** [comment]
grazie a tutti per le segnalazioni! il bug viene risolto in https://github.com/pagopa/io-app/pull/2639 e sarà disponibile nella prossima versione rilasciata dell'app
