### ISSUE TITLE
Suggerimento: Export Pagamenti

### ISSUE THREAD

**Issue by orson-69** [pagopa/io-app#2584]
**Descrivi il problema**
Alcuni enti sono in difficolta per nella gestione dei pagamenti tramite IO, infatti sono organizzati per gestire solo le ricevute cartacee

**Expected behavior**
So che è in parte in contraddizione con la logica full digital di IO, però sarebbe utile la possibilità di esportare in PDF la Ricevuta dell'operazione.

**Comment by NiccoloSegato** [comment]
Duplicate of #2581

**Comment by orson-69** [comment]
No, probabilmente non mi sono spiegato bene.
Non si tratta di un duplicato del #2581.
Quello è relativo al cashback.
Qui invece si parla deli pagamenti effettuati dall'App IO. 
In pratica l'idea è di poter stampare una ricevuta dei pagamenti effettuati tramite IO, da dare agli enti che offrono la prestazione.
Nel  #2581 invece si propone un export di dati del cashback.

**Comment by NiccoloSegato** [comment]
> No, probabilmente non mi sono spiegato bene.
> Non si tratta di un duplicato del #2581.
> Quello è relativo al cashback.
> Qui invece si parla deli pagamenti effettuati dall'App IO.
> In pratica l'idea è di poter stampare una ricevuta dei pagamenti effettuati tramite IO, da dare agli enti che offrono la prestazione.
> Nel #2581 invece si propone un export di dati del cashback.

Quote rimosso, scusa per la svista

**Comment by orson-69** [comment]
Figuriamoci, ho sbagliato anch'io a scrivere, ad una lettura rapida in effetti i due issues sembravano uguali. 
Vedrò di essere più chiaro in futuro
