### ISSUE TITLE
Esporre la data d'attivazione al Cashback della carta

### ISSUE THREAD

**Issue by davcec** [pagopa/io-app#2587]
Se il [toggle che indica lo stato d'attivazione al Cashback](https://github.com/pagopa/io-app/blob/master/ts/features/bonus/bpd/components/BpdPaymentMethodCapability.tsx#L97) è in stato attivo, sarebbe utile esporre anche la data d'attivazione al Cashback della carta.

**Comment by djechelon** [comment]
Strano ma vero, il cashback può essere disattivato e riattivato a uso e consumo dell'utente 😮
