### ISSUE TITLE
Banner "Hai già attivato il cashback sul tuo bancomat?" sopra la navbar non si toglie

### ISSUE THREAD

**Issue by drew458** [pagopa/io-app#2589]
**Descrivi il problema**
Nella sezione messaggi, in basso compare un banner non removibile odve chiede se si è gia aggiunta la carta e arrivato il cashback. 
Propongo di inserire funzione per rimuovere il banner con uno swipe o un tasto.

**To Reproduce**
1. Aprire App
2. Andare nella sezione messaggi

**Expected behavior**
Uno swipe laterale oppure un tasto che rimuove il banner.

**Versione dell'app**
1.14.0.1

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 14.2

**Comment by thisisjp** [comment]
Ciao @drew458, grazie del suggerimento!
Lo terremo in considerazione per i prossimi aggiornamenti dell'app.
