### ISSUE TITLE
Mancano informazioni su bancomat per cashback

### ISSUE THREAD

**Issue by matteomunaretto** [pagopa/io-app#2593]
Se possiedi più bancomat dalla stessa banca con stessa scadenza, sia aziendali che personali, mancano delle info aggiuntive per capire quale poter attivare.

**Comment by orson-69** [comment]
Concordo, sarebbe bene che apparissero le ultime 4 cifre della Carta, in modo da poterle distinguere

**Comment by ravinez** [comment]
Confermo quanto scritto dagli utenti precedenti, aggiungo screenshot esplicativo:

![Carte](https://user-images.githubusercontent.com/76996268/103631031-cc5cc600-4f42-11eb-954f-2d0e4fef2aa1.png)
