### ISSUE TITLE
Contatore Transazioni Valide poco chiaro

### ISSUE THREAD

**Issue by orson-69** [pagopa/io-app#2602]
**Descrivi il problema**
Il contatore delle transazioni Cashback tende ad ingenerare confusione.

**To Reproduce**
Entrare nella sezione Cashback

**Screenshots**
![numero transazioni](https://user-images.githubusercontent.com/75845496/102343981-85ab2a00-3f9b-11eb-8e30-908a228f287c.JPG)

**Expected behavior**
Vedrei bene un contatore sul modello dell'esempio che allegato, il primo caso nell'ipotesi di mancato raggiungimento delle transazioni minime, il secondo nel caso di superamento dello stesso.
![Transazioni](https://user-images.githubusercontent.com/75845496/102345142-3108ae80-3f9d-11eb-943c-b7b0d7d12e77.jpg)

**Versione dell'app**
1.14.0.1

**Additional context**
Ho sentito diversi utenti confusi da questa indicazione.
Alcuni interpretavano un 4 su 10 come il fatto che avessero transazioni rifiutate.
Altri il 20 su 10 come il fatto che solo 10 venissero conteggiate

**Comment by thisisjp** [comment]
Ciao @orson-69!
Nel prossimo periodo del cashback vedrai una versione leggermente diversa di questo componente, poiché entrerà in gioco anche la classifica del Super Cashback. Al tap potrai accedere direttamente al dettaglio transazioni (già oggi accessibile dal pulsante "dettaglio transazioni"), per chiarire qualsiasi dubbio riguardo questo widget che, per forza di cose, può mostrare soltanto un'informazione sintetica.
