### ISSUE TITLE
Transazioni non riconosciute

### ISSUE THREAD

**Issue by smartm0use** [pagopa/io-app#2605]
Dopo 5 giorni dal primo utilizzo del bancomat oggi sono comparse le transazioni sull'app, ma non tutte.
In particolare il 14 e 15 dicembre ho effettuato diversi pagamenti e ad oggi è comparso il cashback solo per alcune transazioni del 15 dicembre, del 14 nessuna.

Quale può essere il problema?

**Versione dell'app**
1.12.0.1

**Comment by thisisjp** [comment]
Ciao,
su Github non forniamo assistenza per casi specifici.

Ecco comunque una serie di FAQ che possono spiegare meglio perché potresti non vedere subito le tue transazioni:

- [Quali acquisti sono validi ai fini del Cashback?](https://io.italia.it/cashback/faq/#n32)
- [Quando faccio un acquisto, quella transazione è subito visibile tra le mie transazioni valide per il Cashback?](https://io.italia.it/cashback/faq/#n44)

Infine, se la tua carta PagoBANCOMAT ha anche il logo di un circuito internazionale (es.: Maestro), controlla di averla aggiunta anche come 'carta di debito/credito'. Trovi tutte le info qui: https://io.italia.it/metodi-pagamento/

**Comment by smartm0use** [comment]
Probabilmente il problema è il diverso circuito utilizzato. La cosa strana è che gli acquisti che ho fatto sono stati effettuati presso lo stesso negozio, per una transazione ho ricevuto il cashback, per un'altra no.

Grazie per le risposta.

**Comment by diegocom** [comment]
Ciao, sicuramente è un problema di circuito come è successo a me. Il mio bancomat ha sia PagoBancomat che Maestro e dipende da cosa seleziona il commerciante (inoltre per pagamenti contactless credo venga selezionato sempre il circuito Maestro). Il problema è che nel mio caso non posso registrare il bancomat anche con il circuito Maestro visto che la mia banca non permette l'addebito del piccolo importo di verifica riconoscendola come transazione online e la banca mi blocca queste transazioni.. questa cosa è un pò una rottura perchè dovrei ogni volta accertarmi che il commerciante selezioni il circuito giusto

**Comment by thisisjp** [comment]
@diegocom qual è la tua banca? Sei sicuro di aver abilitato il 3DS sulla tua carta? È un sistema di sicurezza obbligatorio che abilita le carte di debito ai pagamenti online, tramite l'invio di una OTP (via SMS o app, a seconda della banca).

**Comment by diegocom** [comment]
@thisisjp Ciao, la mia banca è Banco BPM e il bancomat in questione è questo: [QUESTO](https://www.bancobpm.it/DWN/trasparenza/Documenti/52452.pdf) 

Ti lascio anche uno screen della pagina che appare quando si prova ad aggiungere il bancomat. Se premo su continua mi viene riportato un errore per qualche secondo dell'app IO che conferma l'impossibilità di aggiungere la carta e invita a contattare la banca.
![IMAGE 2020-12-17 10:31:25](https://user-images.githubusercontent.com/11348286/102469558-31fc1780-4053-11eb-8baf-d0ffac3c6674.jpg)

**Comment by thisisjp** [comment]
@diegocom perfetto, la tua banca saprà offrirti diverse soluzioni (es.: una nuova carta abilitata ai pagamenti online). Volevo essere sicuro non ci fossero problemi di autorizzazione lato app. Chiudo la issue, grazie per i vostri feedback!

**Comment by smartm0use** [comment]
Confermo che è una issue lato banca, per risolverla senza dover richiedere un altro tipo di carta e chiedere in faso di pagamento che venga usato il circuito Bancomat.

**Comment by diegocom** [comment]
@smartm0use è una seccatura ma capisco non sia risolvibile facilmente (ma presumo che praticamente tutti quelli che hanno una carta con circuito maestro hanno questo problema)

**Comment by smartm0use** [comment]
> Confermo che è una issue lato banca, per risolvere, senza dover richiedere un altro tipo di carta, bisogna chiedere in fase di pagamento che venga usato il circuito Bancomat.

È una issue lato banca che, a quanto vedo, è stata risolta invece dall'app, che ora permette di inserire l'altro circuito (Maestro nel mio caso) anche per carte non abilitate ai pagamenti su internet.
