### ISSUE TITLE
WARNING: ruby-2.4.2 unsupported. non sarebbe opportuno aggiornare?

### ISSUE THREAD

**Issue by giupardeb** [pagopa/io-app#2607]
Buona sera, stavo installando tutto l'ambiente di sviluppo per poter provare a compilare l'applicazione.

Ho seguito tutti i passi senza nessun problema, ma nel momento in cui eseguo `asdf install` e si installa la versione di ruby, mi appare questo messaggio:

```
WARNING: ruby-2.4.2 is past its end of life and is now unsupported.
It no longer receives bug fixes or critical security updates.
```

Cercando sul sito ufficiale di ruby, la versione di Ruby su cui è basata io-app è una versione obsoleta rilasciata nel 2017 e non più mantenuta (sopratutto per quanto riguardano patch di sicurezza). 

Capisco che è difficile aggiornare una parte importante come ruby e che i passaggi di versione sono problematici, ma in un'applicazione così importante come questa, penso che sia molto importante installare una versione che sia ancora supportata e stabile (2.6.6 o la 2.7.2)

**Comment by pietro909** [comment]
https://github.com/pagopa/io-app/pull/3289 porta la versione di Ruby a 2.7.4
