### ISSUE TITLE
Cashback non attivabile per carte precedentemente attive in altri account

### ISSUE THREAD

**Issue by LucaDiba** [pagopa/io-app#2613]
**Descrivi il problema**
Se una carta di una persona è stata aggiunta ad un account di un'altra persona (non so se è stato anche erroneamente attivato il cashback, ma non penso sia possibile essendo nomi diversi anche se penso sia l'unico motivo per cui riscontro questo problema) non è possibile attivare il cashback nell'account del proprietario nonostante la carta sia stata eliminata dai metodi di pagamento dell'altra persona.

**To Reproduce**
1. Aggiungere la carta intestata ad X all'account di Y per effettuare un pagamento (la carta è stata aggiunta mesi fa, molto prima dell'inizio del cashback)
2. Aggiungere altri metodi di pagamento intestati a Y all'account di Y
3. Attivare il cashback dall'account di Y (non ricordo se l'ho attivato anche per la carta intestata a X)
4. Provare ad aggiungere la carta intestata ad X (registrata anche nell'account di Y) all'account di X
5. Ricevuto l'errore, eliminare la carta dall'account di Y
6. Provare ad aggiungerla nuovamente all'account di X: si ottengono sempre gli stessi errori

**Expected behavior**
Una volta eliminata la carta di X dall'account di Y, dovrebbe essere possibile attivare il cashback dall'account di X.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/34377738/102550140-98b61b00-40bd-11eb-9b76-453ca8fe7a39.jpeg)

**Additional information**
L'unica spiegazione che mi viene in mente è che il cashback sia stato attivato nell'account sbagliato ma, prima di eliminare la carta dai metodi di pagamento, non sia stato disattivato il cashback, che quindi risulta in qualche modo ancora collegato al vecchio account, non permettendo il collegamento all'account corretto.
Non avendo fatto transazioni con questa carta, non posso verificare che le transazioni vengano registrate nell'account errato.
Ho provato ad aprire una segnalazione direttamente dall'app condividendo il codice fiscale per poter effettuare verifiche più velocemente ma dopo diversi giorni non ho ricevuto risposta.

**Comment by thisisjp** [comment]
Ciao @LucaDiba, grazie per il tuo feedback. 
È un problema noto legato e stiamo lavorando con i nostri fornitori per risolvere in automatico il problema. 

In questo momento ti suggeriamo, per risolvere velocemente il problema, di chiedere alla persona che aveva precedentemente la tua carta in app di riaggiungerla, **disattivare il cashback** ed eliminare la carta. Entro 24h sarai in grado di aggiungere il metodo nella tua app.
