### ISSUE TITLE
PAN da 19 cifre in un campo da 16

### ISSUE THREAD

**Issue by smartm0use** [pagopa/io-app#2618]
**Descrivi il problema**
Il mio bancomat ha anche il logo Maestro e pertanto, come da indicazioni dell'app, l'ho inserito utlizzando la sezione "Carta di credito, debito o prepagata". In questa sezione però il campo "Numero della carta" ha 16 zero come _placeholder_, lasciando intendere che si possano inserire solo carte con PAN da 16 cifre. Avendo la mia carta un PAN da 19 cifre, in un primo momento non ho proseguito con l'inserimento pensando che non fosse la sezione giusta, poi, non trovando alternative ho provato ad inserire comunque tutte le cifre e l'inserimento sembra essere andato a buon fine. O non è così?
In ogni caso credo che vada corretto il placeholder di quell'input, perchè fuorviante.

![photo_2020-12-18_12-47-34](https://user-images.githubusercontent.com/5399265/102634818-aec1eb00-4152-11eb-8baa-acbfc5032276.jpg)

**Versione dell'app**
1.12.0.1

**Comment by denver-s** [comment]
Se usassero la versione da 19 cifre quelli con 16 cifre avrebbero lo stesso “dubbio”, quindi come si può risolvere?

ps ti consiglio di aggiornare alla v1.14

**Comment by smartm0use** [comment]
Non usare nessun placeholder, oppure indicare "16 o 19 cifre".

**Comment by thisisjp** [comment]
Ciao,
grazie a tutti dei suggerimenti.
Purtroppo esistono tanti tipi di carte differenti (anche con 15 cifre). Nella prossima versione dell'app abbiamo già previsto un link diretto alla nostra pagina [Metodi di pagamento](https://io.italia.it/metodi-pagamento/) al posto dei circuiti accettati, per aiutare a comprendere cosa è possibile fare con ciascuna carta in vostro possesso.

https://github.com/pagopa/io-app/pull/2548
