### ISSUE TITLE
Tutte le news risultano nuovamente da leggere dopo nuova autenticazione SPID

### ISSUE THREAD

**Issue by nu111** [pagopa/io-app#2665]
Ogni 30 giorni è richiesto di autenticarsi nuovamente con SPID e di creare un nuovo PIN, immagino che sia una misura necessaria per la sicurezza, anche se è una scocciatura.
Ogni volta che rifaccio l'autenticazione con SPID, tutte le news risultano nuovamente da leggere, cioè sembra perdersi l'informazione sul fatto che le ho già lette. Stessa cosa con i "servizi", mi vengono segnalati come "nuovi" servizi che ho già visionato.

**Versione dell'app**
1.16.0.1

**Smartphone (please complete the following information):**
 - Device: xperia zx1 compact
 - OS: android 9

**Comment by vincenzo-petronio** [comment]
Confermo, l'app non "ricorda" servizi e messaggi già letti.
Anche i messaggi archiviati vengono di nuovo mostrati in Ricevuti.

**Comment by SimoneRaspagni** [comment]
Confermo anche io.
versione app android 1.16.0.1

**Comment by thisisjp** [comment]
Grazie a tutti della segnalazione,
siamo a conoscenza del problema e viene risolto in [questa PR](https://github.com/pagopa/io-app/pull/2736). Sarà disponibile a breve con un prossimo aggiornamento dell'app.
