### ISSUE TITLE
Icone testuali non visualizzate con carattere personalizzato attivo

### ISSUE THREAD

**Issue by igor-cali** [pagopa/io-app#2666]
**Descrizione**
Utilizzando un carattere personalizzato sul dispositivo, le icone contenute nel font `io-icon-font` non vengono visualizzate correttamente. Vengono invece visualizzate lettere.

**Comportamento atteso:**
corretta visualizzazione delle icone anche con carattere personalizzato attivo sul telefono

**Schermate:**
Con carattere predefinito attivo (visualizzazione corretta):
(comando per inserire immagine non disponibile)

Con carattere personalizzato attivo (visualizzazione impropria):
(comando per inserire immagine non disponibile)

**Versione dell'app**
1.16.0.1

**Smartphone:**
 - Device: HONOR 8 [FRD-L09]
 - OS: Android 8.0 [Build FRD-L09 8.0.0.521 (C432)]

**Commenti aggiuntivi**
Suppongo questo comportamento sia dovuto al fatto che, nel font, le icone sono codificate come lettere comuni, che vengono quindi sostituite dai caratteri presenti nel font attivo sul dispositivo.
Suggerisco di attribuire alle icone codifiche Unicode speciali o di remoto utilizzo.

**Comment by fabriziofff** [comment]
Ciao, grazie per la segnalazione!
Per ovviare al problema da te descritto abbiamo in programma di abbandonare il font custom `io-icon-font` in favore di icone svg.

**Comment by pietro909** [comment]
Tracked via [IAI-35](https://pagopa.atlassian.net/browse/IAI-35)
