### ISSUE TITLE
[suggerimento] Integrazione dati di ANPR nella sezione profilo

### ISSUE THREAD

**Issue by SimoneRaspagni** [pagopa/io-app#2667]
**Descrivi il problema**
Buongiorno,
sarebbe possibile portare le funzioni ANPR pubbliche anche sulla app IO?

In questo modo il cittadino, a seguito di autenticazione SPID, nella **sezione profilo**, potrebbe trovare 3 riquadri: 
- i miei dati (forniti da ANPR): anagrafe, carta di identità, tessera elettorale
- La mia famiglia (famiglia anagrafica fornita sempre da ANPR)
- I miei documenti. In questa sezione potrebbero essere collocati i fac-simile del codice fiscale, carta identità, patente, carta nazionale dei servizi (queste ultime da aggiungere)
Grazie

**Screenshots**
Ecco il concept che ho realizzato,
si può vedere al seguente link (mia cartella di onedrive)
https://1drv.ms/u/s!Av7hifpxgWmDi4hwqFjpV5afaboTPA?e=pWUKG6

**Versione dell'app**
Android. versione 1.16.0.1

Grazie 👍
Simone

**Comment by thisisjp** [comment]
Ciao @SimoneRaspagni,
grazie a te del suggerimento!

Come puoi vedere nella nostra [roadmap](https://io.italia.it/roadmap/#nextsteps), prossimamente su IO sarà disponibile una nuova sezione "Documenti". Siamo anche al lavoro per integrare i dati forniti da ANPR.
