### ISSUE TITLE
Aggiunta circuito Maestro di carte non abilitate agli acquisti online (PAN a 19 cifre e CVV presente)

### ISSUE THREAD

**Issue by ravinez** [pagopa/io-app#2672]
Buongiorno,
ad oggi risulta impossibile aggiungere il circuito Maestro di carte che non sono abilitate agli acquisti online, in quanto ovviamente fallisce la transazione di verifica da 0,02 €.

**Potreste implementare un metodo di inserimento del circuito Maestro  che, così come già accade per il circuito PagoBancomat, non richieda la transazione online?**

Preciso che il problema non riguarda soltanto carte con PAN a 8 o 16 cifre e prive di CVV (che per definizione non sono utilizzabili online), ma anche carte con PAN a 19 cifre e con CVV, che sarebbero quindi predisposte agli acquisti online ma la cui Banca emittente ne ha inibito tale funzionalità; è il caso, ad esempio, delle carte di debito PagoBancomat + Maestro emesse da Banco BPM (screenshot in calce), ma anche da altri Istituti.

Grazie, cordiali saluti.

![Maestro](https://user-images.githubusercontent.com/76996268/103632645-e8616700-4f44-11eb-9b9f-2a48b5d026eb.png)

**Comment by thisisjp** [comment]
Ciao @ravinez,
come [comunicato qui](https://www.pagopa.gov.it/it/pagopa-spa/comunicati-stampa/2020-12-16-comunicato), siamo al lavoro—insieme alle diverse banche coinvolte—per permettere agli utenti l'aggiunta di carte con circuito internazionale non abilitate ai pagamenti online.
