### ISSUE TITLE
Autenticazione SPID solo con username e password

### ISSUE THREAD

**Issue by Massimo80** [pagopa/io-app#2674]
Salve,

utilizzo lo SPID di Poste (Poste ID) sul medesimo telefono (IOS) dove utilizzo l’app IO; normalmente, quando devo effettuare un accesso SPID a qualsiasi sito inquadro il QR Code e utilizzo il riconoscimento facciale del telefono (Face ID).

Se provo ad accedere tramite SPID all’app IO, questa possibilità non mi viene offerta e devo per forza inserire username e password di SPID; solo dopo l’accesso posso abilitare il riconoscimento facciale anche per l’app IO.

È possibile in qualche modo far dialogare le due applicazioni per un accesso più semplice?

**Comment by thisisjp** [comment]
Ciao @Massimo80,
l'esperienza da te descritta funziona sui siti desktop, dove puoi utilizzare la fotocamera del tuo smartphone per inquadrare il codice mostrato sullo schermo del tuo computer. Per esempio, se effettui un pagamento pagoPA sul sito di un Ente (come il tuo Comune), puoi accedere a SPID con il metodo da te descritto.

Nelle app però non è possibile replicare tale interazione, e al momento i vari Identity Provider non prevedono modalità d'accesso differenti a quelle attualmente in uso. Siamo comunque costantemente al lavoro con i vari soggetti coinvolti per semplificare il più possibile l'esperienza utente, e feedback come il tuo sono sicuramente utili ;)

**Comment by Massimo80** [comment]
Capisco, grazie. Speravo fosse possibile far dialogare le due app quando si trovano sullo stesso device, invece di doversi autenticare manualmente in IO; ma se gli Identity Provider non lo prevedono, ovviamente c'è poco da fare. Spero sia possibile implementare qualcosa di simile in futuro, sarebbe decisamente più comodo.
