### ISSUE TITLE
Mancata visualizzazione transazione dopo 15 giorni

### ISSUE THREAD

**Issue by Tallinn13** [pagopa/io-app#2679]
Un pagamento del 23 dicembre non lo visualizzo nell'app.
I precedenti pagamenti presso lo stesso negozio e con la stessa carta, stesso acquirer sono regolarmente registrati.
Come devo fare per segnalare la mancata transazione? Ho la ricevuta del pagamento
grazie.

**Comment by smartm0use** [comment]
La carta ha uno o due circuiti? Li hai inseriti entrambi nell'app?

**Comment by Tallinn13** [comment]
La carta è solo Masrtercard, regolarmente registrata.

**Comment by Tallinn13** [comment]
Oggi dopo ben 30 giorni è comparsa l'operazione!
Non so se in automatico o perché avevo inviato la ricevuta del pagamento tramite l'app.

**Comment by smartm0use** [comment]
Scusate se riprendo questa issue, ma a distanza di mesi, mi ritrovo con lo stesso problema. Mancano all'appello diverse transazioni effettuate nei giorni scorsi, alcune addirittura fatte 2 settimane fa, con circuiti, merchant e acquirer che altre volte sono stati rilevati. All'inizio credevo fosse un ritardo dovuto alle festività di Pasqua, adesso credo ci sia proprio un ritardo in generale, tant'è che ho visto che sta succedendo lo stesso ad un mio amico. C'è qualche problema in corso con l'acquisizione delle transazioni?
