### ISSUE TITLE
Metodi di pagamenti associati al Cashback non visibili senza aggiornare le Carte

### ISSUE THREAD

**Issue by rinaudosal** [pagopa/io-app#2686]
**Descrivi il problema**
Dopo aver effettuato una nuova autenticazione tramite SPID, all'accesso anche dopo 5 Minuti non Risultano Visibili Associate ne Al Portafoglio e ne al Cashback. Dopo aver cliccato "Aggiorna" dal Portafoglio sono visibili in entrambi i punti.

**To Reproduce**
1. Login con SPID
2. Vai su 'Portafoglio'
3. Verificare che non sono associate carte che prima erano presenti
4. Vai su 'Cashback'
5. Verificare che anche qui non sono presenti Carte Associate
6. Ritornare su 'Portafoglio'
7. Cliccare su 'Aggiorna' dei metodi di pagamento e verificare che ora appaiono
8. Ritornare su 'Cashback' e verificare che anche qui siano presenti.

**Expected behavior**

**Screenshots**
Nessuno

**Versione dell'app**
1.16.0.1

**Smartphone (please complete the following information):**
 - Device: Asus Zen phone 4
 - OS: Android 8.1.0

**Comment by Undermaken** [comment]
Ora il dettaglio del cashback ha un link aggiorna che permette di caricare i metodi di pagamento e ricondurli a quelli usati nelle transazioni
https://github.com/pagopa/io-app/pull/2527
