### ISSUE TITLE
Errata visualizzazione importo definitivo cashback

### ISSUE THREAD

**Issue by mbm901** [pagopa/io-app#2691]
**Descrivi il problema**
L'importo definitivo del cashback:
1) è visualizzato con il punto al posto della virgola come separatore dei decimali;
2) mostra tre decimali invece che due.

**To Reproduce**
1. Login 
2. Click su "portafoglio"
3. Click su "cashback 8-31 dicembre 2020"

**Expected behavior**
Messaggio "Complimenti Nome! Hai diritto a € 100,01..."

**Screenshots**

"Complimenti Nome! Hai diritto a € 100.010..."

**Versione dell'app**
1.16.0.1

**Smartphone (please complete the following information):**
 - Device: LG V30
 - OS: Android 8.0.0

**Comment by fabriziofff** [comment]
grazie per la segnalazione, risolto in https://github.com/pagopa/io-app/pull/2692
