### ISSUE TITLE
Apple Pay non dovrebbe funzionare ma funziona (in parte!)

### ISSUE THREAD

**Issue by mpix21** [pagopa/io-app#2693]
Non so come farvi riprodurre la questione ma vi descrivo la mia situazione:

- Utilizzo Curve come carta fisica
- Utilizzo Apple Pay tramite iPhone e Apple Watch
- Ho aggiunto Curve come carta su Apple Pay
- Ho aggiunto Curve come carta fisica su app IO

In teoria _(e anche in pratica)_ la carta su Apple Pay viene tokenizzata, quindi corrisponde ad un altro PAN.

Bene, questo è il risultato:

**NEGOZIO A:** Pagamento 1 con Apple Watch => Cashback riconosciuto su app IO su carta fisica anche se sullo scontrino c'è un altro PAN
**NEGOZIO A:** Pagamento 2 con Apple Watch => Cashback riconosciuto su app IO su carta fisica anche se sullo scontrino c'è un altro PAN
**NEGOZIO B:** Pagamento 1 con Apple Watch => Cashback non riconosciuto su app IO _(come in teoria dovrebbe essere)_
**NEGOZIO C:** Pagamento 1 con Carta fisica Curve => Cashback riconosciuto su app IO su carta fisica _(come in teoria dovrebbe essere)_

Qualcuno mi sa spiegare cosa sta succedendo?

**Comment by denver-s** [comment]
Può essere utile per indagare se riuscissi a fornire l'acquirer ID del negozio B.

**Comment by mpix21** [comment]
**NEGOZIO A:** 
Eserc: 7826278
AIIC: 00000000023
Auth: 112361

**NEGOZIO B:**
Eserc: 8475396
AIIC: 45000000000
Auth: 141514

Sono questi i dati che servivano?
