### ISSUE TITLE
IBAN per accredito Cashback di Natale visibile solo nella scheda del nuovo Cashback

### ISSUE THREAD

**Issue by nbonato** [pagopa/io-app#2695]
**Descrivi il problema**
IBAN e carte di pagamento associati al Cashback non sono visibili nella scheda del Cashback di Natale, ma solo in quella del nuovo Cashback. Anche in quella scheda l'IBAN non è immediatamente visibile, né la sua posizione chiara.

**To Reproduce**
1. Andare alla scheda 'Cashback'
2. Scorrere verso destra per visualizzare il nuovo Cashback (da gennaio a giugno 2021) 
3. Scorrere verso il basso per visualizzare l'IBAN per l'accredito del Cashback
4. Non è chiaro se questo IBAN è quello su cui verrà effettivamente accreditato il Cashback di Natale, dato che le informazioni non sono all'interno della stessa scheda

**Expected behavior**
1. Andare alla scheda 'Cashback'
2. Scorrere verso il basso per visualizzare l'IBAN per l'accredito del Cashback
3. Visualizzare il proprio IBAN e una chiara indicazione che su questo verrà accreditato il Cashback di Natale

**Versione dell'app**
1.17.0.3

**Smartphone (please complete the following information):**
 - Device: [e.g. Sony Xperia E5]
 - OS: [e.g. Android 6]

**Comment by davcec** [comment]
> IBAN e carte di pagamento associati al Cashback non sono visibili nella scheda del Cashback di Natale, ma solo in quella del nuovo Cashback.

Le carte di pagamento non vengono più visualizzate nel periodo Cashback terminato, ma l'IBAN indicato per l'accredito invece resta visibile.

**Comment by Undermaken** [comment]
https://github.com/pagopa/io-app/pull/2642
