### ISSUE TITLE
Emissione nuova Carta di Debito (nuova scadenza)

### ISSUE THREAD

**Issue by dfm8819** [pagopa/io-app#2712]
Ho due carte di debito ad oggi a mio nome. La banca me ne ha disabilitata una(non ancora scaduta) per aggiornamento a nuova carta. Ho fatto quindi la richiesta XME Card Plus, ricevuta e abilitata.
Ora ho la situazione sul portafoglio IO un po' strana.

- La carta di debito vecchia, solo come PagoBancomat (non potevo lato maestro perché non era possibile abilitarla per pag online) registrata correttamente (ho ricevuto del cashback)

- La xme card plus con circuiti abilitati Mastercard(correttamente impostato su IO), e PagoBancomat che però non riesco a trovarla tramite la ricerca dalla sezione carte(la ricerca mi propone sempre quella vecchia riconosciuta tramite data di scadenza).

La nuova ovviamente ha una data di scadenza diversa, oltre al pan da 16 cifre
come faccio ad impostarla come PagoBancomat?

**Comment by thisisjp** [comment]
@dfm8819 la visualizzazione delle carte PagoBANCOMAT non sempre restituisce risultati in tempo reale. Hai risolto il problema nel frattempo? Altrimenti ti invito a chiedere assistenza in app, fornendo il tuo Codice Fiscale per aiutare il team di assistenza.
