### ISSUE TITLE
[Suggerimenti] - Pagamento in app dal portale PagoPa

### ISSUE THREAD

**Issue by ItsFiloHere** [pagopa/io-app#2737]
Sarebbe molto comodo implementare una funzione che permette di concludere un pagamento iniziato nel portale web di pagoPa nell'app IO.

La soluzione migliore che mi viene in mente è quella di aggiungere un tasto, "Paga su IO" che quando premuto apre l'app (se ci si trova da mobile) oppure chiede la mail e, se associata ad un profilo su IO, invia una notifica di pagamento in app.

Grazie :)

**Comment by orson-69** [comment]
Ottima idea

**Comment by thisisjp** [comment]
Ciao @filioro, 
ottimo suggerimento!
Siamo già al lavoro per offrire un'esperienza ancora più semplice ed integrata tra i nostri prodotti, inclusi pagoPA e app IO.

Non vediamo l'ora di condividerle con voi :)
