### ISSUE TITLE
[Minor] Uniformare selezione del testo

### ISSUE THREAD

**Issue by davcec** [pagopa/io-app#2740]
I testi [qui](https://github.com/pagopa/io-app/blob/master/ts/features/bonus/bpd/components/superCashbackRanking/SuperCashbackRanking.tsx#L93) e [qui](https://github.com/pagopa/io-app/blob/master/ts/features/bonus/bpd/components/superCashbackRanking/SuperCashbackRanking.tsx#L107) nel component **SuperCashbackBottomSheet** sono selezionabili (da app Android), quando invece negli altri component non lo sono.

**Comment by davcec** [comment]
https://www.pivotaltracker.com/story/show/176481360/comments/221583795

**Comment by Undermaken** [comment]
https://www.pivotaltracker.com/story/show/176993827

**Comment by Undermaken** [comment]
https://github.com/pagopa/io-app/pull/2866

**Comment by Undermaken** [comment]
Fixed by https://github.com/pagopa/io-app/pull/2866
