### ISSUE TITLE
"Cancellare Iscrizione Cashback" Tasto troppo in vista

### ISSUE THREAD

**Issue by ettoremazza** [pagopa/io-app#2743]
**Descrivi il problema**
Il tasto per cancellare l'iscrizione è presente nella schermata principale accanto a quello per il dettaglio delle transazioni.
La posizione è troppo esposta per una funzione che, si presume, utilizzeranno in pochissimi.
Si corre il rischio di premerlo per sbaglio accedendo al dettaglio delle transazioni

**To Reproduce**
1. access app
2. Click on Portafoglio
3. Select cashback period
4. Scroll to the bottom

**Expected behavior**
Il tasto per la canceazione dovrebbe trovarsi in un sottomenù

**Versione dell'app**
1.18.03

**Smartphone (please complete the following information):**
 - Pixel 2 XL
 - OS: Android 11

**Additional context**

**Comment by thisisjp** [comment]
Ciao @ettoremazza,
il tasto prevede un'ulteriore conferma da parte dell'utente, quindi è piuttosto improbabile che l'azione avvenga senza un esplicito consenso da parte dell'utente. Si tratta di un paradigma di interazione [piuttosto consolidato](https://www.nngroup.com/articles/confirmation-dialog/).

Siamo comunque sempre al lavoro per migliorare ulteriormente l'esperienza d'uso, e valuteremo suggerimenti come il tuo nei prossimi aggiornamenti dell'app.

**Comment by ettoremazza** [comment]
Sarà come dici tu, ma sul forum [https://forum.italia.it/t/cancellazione-cashback/19748/15] ci sono persone che si sono cancellate per sbaglio ed hanno visto azzerato tutto il loro cashback.
Quel tasto nell'utilizzo normale non serve a nulla ed è assurdo che stia vicino al tasto per il dettaglio transazioni che viene premuto ogni giorno.

**Comment by Parnas72** [comment]
Concordo; al di là che venga richiesta una conferma per l'operazione, mette un po' di apprensione vedere il tasto per cancellare l'account accanto a quello per vedere le transazioni che si usa quotidianamente.
Tu pensa se, quando apri il gestione risorse di Windows, nella toolbar vicino a "New folder" o "Copy file" ci fosse un tastino "Format hard-drive"  :laughing:

**Comment by ettoremazza** [comment]
> Ciao @ettoremazza,
> il tasto prevede un'ulteriore conferma da parte dell'utente, quindi è piuttosto improbabile che l'azione avvenga senza un esplicito consenso da parte dell'utente. Si tratta di un paradigma di interazione [piuttosto consolidato](https://www.nngroup.com/articles/confirmation-dialog/).
> 
> Siamo comunque sempre al lavoro per migliorare ulteriormente l'esperienza d'uso, e valuteremo suggerimenti come il tuo nei prossimi aggiornamenti dell'app.

Più commenti indicano che non esista nessuna ulteriore conferma alla cancellazione.
