### ISSUE TITLE
Integrare area riservata lotteria degli scontrini in Io

### ISSUE THREAD

**Issue by mbm901** [pagopa/io-app#2762]
Sarebbe bello avere l'area riservata della lotteria degli scontrini integrata in Io, così tutto il piano Cashless Italia sarebbe accessibile da questa app.

**Comment by orson-69** [comment]
Concordo.
Strano per fare la stessa richiesta.
Tecnicamente credo sia una cosa semplice

**Comment by bhack** [comment]
https://forum.italia.it/t/lotteria-degli-scontrini-su-io/15227/21

**Comment by bhack** [comment]
🤖

**Comment by bhack** [comment]
🤖

**Comment by mbm901** [comment]
Issue is still present

**Comment by Marlowess** [comment]
🤖
