### ISSUE TITLE
Configurazioni di PRD sul repo

### ISSUE THREAD

**Issue by fgrotta** [pagopa/io-app#2776]
**Descrivi il problema**
Sono state pushate le configurazioni sul repository di tutti gli ambienti

**Comment by balanza** [comment]
Ciao @fgrotta, grazie della segnalazione.

Questa è una scelta ponderata.

Vogliamo tenere traccia degli "eventi" generati da utenti anonimi, privi di una sessione valida con il nostro backend.
Questo design potrebbe aiutare a diagnosticare, risolvere i problemi e rispondere ai problemi di pre-accesso. 
Fatta ferma questa prospettiva aziendale, non c'è molta differenza tra un token pubblico e un'API non autenticata.

**Comment by balanza** [comment]
Duplicate of https://github.com/pagopa/io-app/issues/1539
