### ISSUE TITLE
Icone del circuito non visualizzate

### ISSUE THREAD

**Issue by ettoremazza** [pagopa/io-app#2835]
Le icone del circuito non vengono visualizzate accanto alle transazioni, dove invece è mostrata una icona di carta generica.
Le icone vengono caricate solo dopo che si mostrano le carte e da allora sono disponibili.
Evidentemente, il problema, che era già presente, è stato risolto con una routine che carica le icone solo al momento in cui si mostrano le carte, ma se si tengono le carte nascoste (cosa possibile solo se non si sono mai mostrate dopo il login con SPID) le icone continuano a non essere caricate

**To Reproduce**
1.Logout
2. Login again
3. show tranactions
4. Card icons are not displayed
5. go back and show all cards
6. show transactions
7. icons are shown

**Expected behavior**
Le icone dovrebbero essere caricate anche quando si mostrano le transazioni

**Versione dell'app**
1.20.02

**Smartphone (please complete the following information):**

**Additional context**

**Comment by thisisjp** [comment]
Ciao @ettoremazza, grazie della segnalazione.
Dalla prossima versione il wallet [tornerà ad essere caricato in automatico](https://github.com/pagopa/io-app/pull/2792) al primo atterraggio nella sezione Portafoglio. Di conseguenza vedrai sempre le informazioni relative alle carte nel dettaglio transazioni cashback.
