### ISSUE TITLE
[Feature Request] Autenticazione tramite CIE

### ISSUE THREAD

**Issue by vixrt** [pagopa/io-app#2851]
Buongiorno, sfortunatamente la applicazione dedicata https://play.google.com/store/apps/details?id=it.ipzs.cieid&hl=en&gl=US per consentire l'autenticazione ai vari servizi tramite CIE, non è open source.

Come se non bastasse, l'applicazione non funziona per chi non possiede Google Play Service sul proprio android.

Ho testato l'app IO e tutto funziona, la CIE viene correttamente riconosciuta e riesco ad accedere.

Chiedo quindi che sia implementata, all'interno di IO app, una funzione che mi consenta di usarla per fare accesso ai vari siti tramite CIE.

Grazie a tutti, buona giornata

**Comment by vixrt** [comment]
@mzzntn puoi argomentare il "dislike"? Grazie

**Comment by Undermaken** [comment]
Ciao.
IO è un _service provider_ e non un _identity provider_ per cui lo scenario che descrivi non è realizzabile in quanto non rispetta i requisiti dell'[autenticazione tramite CIE](https://www.cartaidentita.interno.gov.it/CIE3.0-ManualeSP.pdf) per accedere ad un servizio (molto simili a quelli di SPID)

**Comment by vixrt** [comment]
Ciao @Undermaken , è possibile fare qualcosa allora per ottenere il rilascio del codice sorgente dell'app per l'autenticazione CIE? Per legge tutte le pubbliche amministrazioni dovrebbero pubblicare il loro codice

**Comment by Undermaken** [comment]
Certo. My bad, volevo lasciare i links
Il codice è già open source. L'app, usando React Native, utilizza un [sdk di Android e uno di iOS](https://github.com/pagopa/io-cie-sdk)
Tali sdk sono stati realizzati da consulenti esterni con il nostro contributo e noi abbiamo utilizzato una repo che li accorpa e ne permette l'uso attraverso React Native

[CIE sdk Android ](https://github.com/italia/cieid-android-sdk)- repo ufficiale

**Comment by vixrt** [comment]
Ciao @Undermaken , la ringrazio molto per la risposta. Dopo aver analizzato attentamente i codici delle repository che mi ha inviato, ho notato che essi riescono solo a processare (da questo link https://docs.italia.it/italia/cie/cie-manuale-tecnico-docs/it/master/overview.html ) solo il flusso descritto a questa immagine https://docs.italia.it/italia/cie/cie-manuale-tecnico-docs/it/master/_images/schemaMobile.png

Invece, l'applicazione CieID pubblicata dalla zecca dello stato, consente anche di effettuare l'autenticazione seguendo questo flusso https://docs.italia.it/italia/cie/cie-manuale-tecnico-docs/it/master/_images/img_MSC_CIE_ibrido.png che è quindi cloused source.

Come posso chiedere e ottenere il codice di questo flusso tramite QR code?

Lei ha contatti interni e può avanzare la richiesta "internamente" e ottenerne il rilascio prima? E' per assolvere l'obbligo di pubblicazione dei sorgenti da parte delle pubbliche ammistrazioni

Ringrazio in anticipo

**Comment by Undermaken** [comment]
Ciao @vixrt 
Puoi provare a contattare il maintainer principale della repo Android [fventola89](https://github.com/fventola89)

**Comment by vixrt** [comment]
Ciao @Undermaken 

Purtroppo ho cercato in rete e ho trovato questo https://forum.italia.it/t/codice-sorgente-app-cieid/20978/5
Sembra che non voglia rispondere o che non sappia dirci di più

A questo punto chi si può contattare? Lei non ha qualche contatto interno?

**Comment by Undermaken** [comment]
No, non ce ne siamo mai occupati noi in PagoPa
C'è un canale dedicato su [Slack - Developers Italia](https://join.slack.com/t/developersitalia/shared_invite/zt-758p3tw3-5L~imEa9HU_0X52AJR2YAA). Forse chiedere li potrebbe dare qualche risultato
Il canale è **`#cie`**

**Comment by vixrt** [comment]
@Undermaken 
Ti ringrazio tanto!

Sfortunatamente dopo aver cercato attentamente ho trovato questo
https://forum.italia.it/t/entra-con-cie-modalita-di-autenticazione-mista-desktop-cellulare/14048/26

E alla domanda di un utente se l'approccio sicurezza fosse "security by obscurity" è stato risposto orgogliasamente di sì
https://forum.italia.it/t/entra-con-cie-modalita-di-autenticazione-mista-desktop-cellulare/14048/35?u=astheneir

Temo non ci sia canale slack che tenga, qui non c'è proprio speranza di avere un dialogo.
Credo che a questo punto rimanga solo da inviare una mail al direttivo AGID

**Comment by lorenzofiamingo** [comment]
‘Security by obscurity’. Alla prima lezione di Computer Security(2 settimane fa) è stata la prima cosa che il professore ha detto di non fare per avere un sistema sicuro.
