### ISSUE TITLE
Errata visualizzazione importo bonifico eseguito

### ISSUE THREAD

**Issue by mbm901** [pagopa/io-app#2856]
Descrivi il problema
L'importo del cashback nel messaggio "Il tuo rimborso dell'extra cashback di Natale":

-è visualizzato con il punto al posto della virgola come separatore dei decimali;
-mostra tre decimali invece che due.

To Reproduce

Login
Click su "messaggi"
Click su "il tuo rimborso dell'extra cashback di Natale"
Expected behavior
Messaggio "ti confermiamo che il bonifico di € 100,01..."

Screenshots

"Ti confermiamo che il bonifico di € 100.010..."

Versione dell'app
1.22.0.1

Smartphone (please complete the following information):

Device: LG V30
OS: Android 8.0.0

**Comment by Undermaken** [comment]
Grazie per la segnalazione. 
Il problema è stato già preso in carico nei giorni passati e segnalato all'ente predisposto all'invio dei messaggi di notifica dell'avvenuto bonifico del cashback

Questo bug non risiede nell'app ne nella piattaforma IO: il messaggio viene creato ed invitato dall'ente **Ministero dell'Economia e Finanze** che utilizza la piattaforma IO per comunicare con i cittadini,
