### ISSUE TITLE
[Feature request] feedback nel codice di sblocco

### ISSUE THREAD

**Issue by alessiomatricardi** [pagopa/io-app#2896]
Quando si prova ad autenticarsi attraverso il codice di sblocco, non viene fornito alcun feedback sul tastierino numerico al tap di un numero. Ne risulta che l'utente ha una scarsa percezione di dove sta cliccando.
Suggerirei di adottare un sistema simile a quello che fa Apple su iOS: il numero su cui viene fatto tap si illumina immediatamente e poi si sfuma fino a tornare di "default". Può sembrare sciocco, ma migliora sensibilmente la UX.
Inoltre, suggerirei di ingrandire leggermente i bottoni numerici: un significante più grande da "sensazioni" migliori all'utente.

**Comment by Undermaken** [comment]
@thisisjp mi sembra una buona proposta
In closed beta avevamo il feedback sui pulsanti all'onpress ma lo abbiamo disabilitato globalmente in quanto causava un effetto non voluto per gli items in lista che si comportavano come dei pulsanti.

Questo per dire che riabilitarlo su specifici screen è possibile

**Comment by thisisjp** [comment]
Ciao @alessiomatricardi, grazie per il feedback _sul feedback_! 😄

Stiamo rivedendo in generale tutta la UI per completare i vari stati non ancora coperti, come ad esempio il _pressed_ del tastierino numerico. Stay tuned!

**Comment by alessiomatricardi** [comment]
La issue non è ancora risolta
