### ISSUE TITLE
cambio password obbligatorio tentando l'accesso con SPID Poste Italiane

### ISSUE THREAD

**Issue by Beppe70** [pagopa/io-app#2922]
Un problema che qualcuno ha dichiarato risolto nella versione 1.21.0.5.10072700 (ticket #2068), sta invece facendomi perdere un sacco di tempo nella versione 1.22.0.1
Sto rinunciando a leggere una notifica perché sono stufo di fare la procedura di cambio password in posteID, dal momento che il problema è in realtà della io-app e non della posteid.
Il problema si è presentato in prima nottata nel 19/03/2021
![Screenshot_20210319-024330_IO](https://user-images.githubusercontent.com/80932193/111719886-17595a80-885d-11eb-9f26-bb46683860db.jpg)

**Comment by Undermaken** [comment]
cc @raicastino

**Comment by thisisjp** [comment]
Ciao @Beppe70, abbiamo verificato con Poste Italiane e ci hanno comunicato che a volte possono verificarsi problemi nella propagazione delle modifiche. Ad ogni modo, si tratta di problematiche non imputabili all'app: se dovessi avere ulteriori problemi, ti invitiamo a contattare il servizio clienti di PosteID.
