### ISSUE TITLE
Apple Pay - Impossibile rimuovere o aggiornare le carte virtuali tokenizzate non più valide

### ISSUE THREAD

**Issue by OculiViridi** [pagopa/io-app#2949]
### Problema

Lo scorso dicembre ho scaricato l'app IO sul mio iPhone Xs (iOS v14) e registrato vari metodi di pagamento per accedere al Cashback di Stato, tra cui la mia Carta di Credito VISA contactless e il mio Bancomat, sempre contactless.
Poiché entrambe le carte erano già state precedentemente virtualizzate all'interno dell'app di sistema Wallet, l'app IO aveva **automaticamente aggiunto anche le versioni tokenizzate** delle suddette carte, che avevano rispettivamente, come ultime 4 cifre dell'identificativo virtuale, i seguenti numeri:

![20210331_063239627_iOS](https://user-images.githubusercontent.com/42179710/113102628-9310bb00-91fe-11eb-9293-1a1f99f23620.png)

Fino a circa 1 mese fa, tutto funzionava regolarmente e le transazioni venivano acquisite correttamente dall'app IO in tutti i casi, quindi anche in caso di pagamento con **carta virtuale da app Wallet**.

Successivamente, il mio dispositivo si è guastato ed è stato portato in assistenza, la quale me ne ha **restituito uno nuovo**.
A questo punto, ho ripristinato sul nuovo dispositivo il backup fatto precedentemente e con l'occasione è stata ripristinata anche l'app IO, la quale presentava tutti i metodi di pagamento già registrati, **comprese le carte virtuali del Wallet**.

Tuttavia, a seguito del ripristino di sistema, i metodi di pagamento virtuali registrati nel Wallet, sono stati sì mantenuti dal backup precedente, ma è stato assegnato loro un **nuovo identificativo**, come si vede dagli screenshot sottostanti dell'app Wallet:

![20210331_063711599_iOS](https://user-images.githubusercontent.com/42179710/113102651-9a37c900-91fe-11eb-99e9-221e8db4951f.png)

![20210331_063754047_iOS](https://user-images.githubusercontent.com/42179710/113102655-9c9a2300-91fe-11eb-8e5f-c738671ab1d1.png)

Come si nota, gli attuali identificativi delle carte virtuali registrate su Wallet **non corrispondono più a quelli tutt'ora presenti nell'app IO**.

**L'app IO continua a mantenere registrati i vecchi identificativi non più validi e non è possibile rimuoverli o aggiornarli in nessun modo.**

### Tentativi di risoluzione

Inizialmente ho provato a disattivare i metodi di pagamento virtuali per vedere se oltre ad essere disattivati, poi sarebbero stati anche rimossi, ma non è stato così.
Successivamente ho provato a rimuovere le carte fisiche corrispondenti a quelle virtuali dai metodi di pagamento registrati nell'app IO, ma senza risultato, perché le carte fisiche sono state rimosse correttamente, mentre le controparti virtuali errate sono rimaste.
Infine, ho provato a disinstallare e reinstallare completamente l'app IO, ma anche questa volta senza successo. **I metodi di pagamento registrati sono rimasti tutti, compresi quelli virtuali errati e sono tutt'ora presenti**.

Di fatto, eseguendo pagamenti con le carte virtuali dell'app Wallet, le transazioni corrispondenti non vengono più registrate nell'app IO. Eseguendo invece pagamenti con le carte fisiche corrispondenti, le transazioni vengono registrate correttamente.

Attualmente quindi, l'app si trova in uno *stato inconsistente*, nel quale non è possibile né rimuovere, né aggiornare o reinserire i metodi di pagamento agganciati all'app Wallet e questo **rende impossibile per l'utente l'utilizzo di tali metodi di pagamento come invece era possibile fare prima**.

### Riproduzione del problema

1. Installare l'app IO su un iPhone in cui sia già presente una carta virtuale all'interno dell'app Wallet.
2. Registrare nell'app IO la carta fisica corrispondente alla carta virtuale presente nell'app Wallet.
3. Fare qualche pagamento con la carta virtuale dall'app Wallet per vedere che effettivamente il metodo di pagamento sia stato registrato correttamente.
4. Eseguire un backup di iPhone.
5. Resettare iPhone.
6. Ripristinare il backup di iPhone in 2 modalità differenti:
    a. Sullo stesso dispositivo.
    b. Su un nuovo dispositivo.

NOTA: Non so dire se ripristinando il backup sullo stesso dispositivo, gli identificativi delle carte virtuali vengano comunque rigenerati oppure se il caso riguardi solamente il ripristino su un dispositivo differente.

### Comportamento atteso

Dovrebbe essere possibile per l'utente rimuovere i metodi di pagamento virtuali agganciati all'app Wallet.
In ogni caso l'app, in caso di aggiornamento dei metodi di pagamento, oppure in caso di nuova installazione e/o in altri casi da analizzare, deve verificare ed eventualmente rimuovere e/o aggiornare i metodi di pagamento virtuali.

So che il supporto alle forme di pagamento virtuali, quali Apple Pay, Google Pay e altre, non è ancora completo. Tuttavia la funzionalità è presente nell'app fin da dicembre 2020 e provoca anomalie e stati inconsistenti come questo, quindi dovrebbe essere previsto quantomeno un avviso.

### Versioni

App IO **v1.23.0.6**
iOS **v14.4.1**
Device **iPhone Xs**

**Comment by thisisjp** [comment]
Ciao @OculiViridi, 
i metodi da te evidenziati sono stati aggiunti da un altro canale—come chiaramente mostrato dall'app ("Attivati su altri canali"). Siamo al lavoro con i vari soggetti coinvolti per supportare le carte tokenizzate in app IO, e ne daremo comunicazione non appena la funzionalità verrà rilasciata.

Nel frattempo, hai già provato ad aggiungere nuovamente i metodi dall'app del tuo issuer? Trovi la lista delle app che ti permettono di gestire il Cashback in [questa pagina](https://io.italia.it/cashback/issuer).

**Comment by OculiViridi** [comment]
@thisisjp Mi sono preso un po' di tempo per fare qualche prova e per approfondire meglio il problema.

Innanzitutto, a differenza di quanto pensavo, le due carte tokenizzate che sono state aggiunte automaticamente nell'app IO alla prima installazione (vedi primo screenshot), non corrispondevano alla Carta di Credito e al Bancomat, bensì, erano entrambe la versione tokenizzata della sola Carta di Credito, rispettivamente presenti sul Wallet del mio iPhone e sul Wallet del mio Apple Watch (quindi con 2 ID differenti, uno per ciascun dispositivo).
L'ho notato perché la carta registrata su Apple Watch ha ancora lo stesso identificativo che ho riportato nello screenshot e dunque dovrebbe risultare ancora valida (non ho avuto modo di provare).

Quindi di fatto, le versioni tokenizzate del Bancomat, registrate appunto anch'esse sul Wallet di iPhone e su quello di Apple Watch, non sono mai stata prese in considerazione dalla app IO. Questo suppongo sia dovuto al fatto che il Bancomat è emesso e gestito dalla mia banca (che non è un issuer valido per i metodi di pagamento digitali), mentre invece la carta di credito è stata emessa da Nexi.

> Nel frattempo, hai già provato ad aggiungere nuovamente i metodi dall'app del tuo issuer? Trovi la lista delle app che ti permettono di gestire il Cashback in questa pagina.

Ho provato a disattivare la Carta di credito dalla app Nexi, nella sezione relativa al Cashback. Tuttavia, nell'app IO i corrispondenti metodi di pagamento, sono solo stati disattivati e non eliminati e **permane quindi ancora la versione tokenizzata della Carta di credito errata**. Nello screenshot ho evidenziato in verde la Carta di Credito tokenizzata su Apple Watch (corretta) e in rosso quella errata su iPhone.

![IMG_0163](https://user-images.githubusercontent.com/42179710/114357031-89c60d80-9b71-11eb-92dc-8859951fa1ac.jpg)

Ho anche provato a rimuovere la carta dal Wallet di iPhone, ma su app IO non è cambiato nulla. Ho provato a registrarla nuovamente sul Wallet, ottenendo un nuovo token, ma di nuovo su app IO la situazione non si è aggiornata.

**Comment by thisisjp** [comment]
Grazie @OculiViridi!
Hai già provato a rimuovere ed aggiungere nuovamente la carta di credito tramite l'app Nexi Pay? Quest'azione dovrebbe aggiungere 2 nuove carte virtuali nella sezione "Attivati su altri canali" di app IO (come hai giustamente intuito, si tratta di una carta per ciascun dispositivo Apple su cui hai attivo Apple Pay). In alternativa, ti suggeriamo di rivolgerti all'assistenza di Nexi Pay.

Prossimamente potrai abilitare le tue carte virtuali (tokenizzate) anche direttamente su app IO, ancora un po' di pazienza 💪

**Comment by OculiViridi** [comment]
> Grazie @OculiViridi!
> Hai già provato a rimuovere ed aggiungere nuovamente la carta di credito tramite l'app Nexi Pay? Quest'azione dovrebbe aggiungere 2 nuove carte virtuali nella sezione "Attivati su altri canali" di app IO (come hai giustamente intuito, si tratta di una carta per ciascun dispositivo Apple su cui hai attivo Apple Pay). In alternativa, ti suggeriamo di rivolgerti all'assistenza di Nexi Pay.
> 
> Prossimamente potrai abilitare le tue carte virtuali (tokenizzate) anche direttamente su app IO, ancora un po' di pazienza 💪

Non mi risulta che sia possibile rimuovere la carta dalla app Nexi. Ho guardato anche sulle pagine di supporto del sito [Nexi](https://www.nexi.it/privati/servizi/faq/gestione-della-carta.html).
Dalla app Nexi, l'unica cosa che posso fare e che appunto ho già provato, è "rimuovere" (nel senso di disattivare) la carta dalla sezione Cashback all'interno della app.
