### ISSUE TITLE
Tentativi di sblocco con FaceID illimitati

### ISSUE THREAD

**Issue by JustSomebody0** [pagopa/io-app#2962]
Salve a tutti,
Non so se questo sia o meno un bug o una feature voluta, ma vorrei far notare che su iOS non ci sono limiti al numero di volte per cui uno può provare a sbloccare IO usando il FaceID.
To Reproduce

1.Aprire IO;
2.Fallire più volte ad autenticarsi col FaceID;
3.Procedere nella schermata per inserire il PIN;
4.Fare tap sull'icona del FaceID in basso a sinistra;
5.ripetere dal punto 2.

Expected behavior
L'app, in caso di fallimento del FaceID, non dovrebbe presentare l'opzione di riprovare con quest'ultimo.

Versione dell'app
-1.23.0.6

Smartphone:
 - Device: iPhone 11 Pro
 - OS: 14.4.2

**Comment by Undermaken** [comment]
Ciao. Il comportamento che descrivi è quello voluto.
Se l'autenticazione biometrica fallisce, l'utente deve poter provare ad entrare nell'app attraverso la digitazione del pin. Allo stesso modo, al contrario, l'utente deve poter richiedere l'autenticazione biometrica se disponibile.

Non ci sono limiti sui tentativi di autenticazione falliti tramite biometrico.
Al momento un attacco brute-force sul PIN risulta essere molto più facile da applicare rispetto che sul biometrico.
