### ISSUE TITLE
Test su device android di fascia bassa

### ISSUE THREAD

**Issue by cloudify** [pagopa/io-app#297]
Device **LG Leon**, Android 5.0.1, [dettagli](https://www.gsmarena.com/lg_leon-7053.php)

Nello schermo Messaggi, `Scadenze` va accapo @fpersico 

![img_2427](https://user-images.githubusercontent.com/48206/42515269-a9e33d20-845b-11e8-9ea9-5636327511d5.JPG)
---
`Latest transactions` e' in inglese anche se il resto dell'app e' in italiano @fgiobergia 

![img_2429](https://user-images.githubusercontent.com/48206/42515270-aa08542a-845b-11e8-930c-6f5fe14c4b73.JPG)
---
preview carta di credito e' tagliata, dovrebbe adattarsi allo schermo @fgiobergia 

![img_2428](https://user-images.githubusercontent.com/48206/42515271-aa2d0d7e-845b-11e8-9b58-06c3dde86b47.JPG)
---
i bullet del numero di carta vanno accapo @fgiobergia 

![img_2431](https://user-images.githubusercontent.com/48206/42515272-aa4f81b0-845b-11e8-8d19-ec5fd4e11ff7.JPG)
---
secondo step dell'inserimento del PIN, il pulsante "modifica il codice" occupa lo spazio sopra l'input del PIN @fpersico 

![img_2426](https://user-images.githubusercontent.com/48206/42515273-aa738d30-845b-11e8-9563-af043dfc902f.JPG)
---
inserimento dei dati di carta, i tab appaiono sopra la tastiera occupando tutto lo schermo e impedendo l'inserimento @fgiobergia 

![img_2430](https://user-images.githubusercontent.com/48206/42515275-aaa1ef22-845b-11e8-8a73-92c944130467.JPG)
---
lettura QR code, meta' dell'immagine e' coperta @fgiobergia 

![img_2432](https://user-images.githubusercontent.com/48206/42515549-4afd7f72-845c-11e8-96fc-d27a6dd41b04.JPG)
---

![img_2433](https://user-images.githubusercontent.com/48206/42515550-4b22b0c6-845c-11e8-9020-c434f97ef0dc.JPG)

**Comment by DavideValdo** [comment]
Non visualizzo 6 input, ma 4:

![IMAGE 2020-11-24 16:16:13](https://user-images.githubusercontent.com/26572302/100113220-60ca0800-2e70-11eb-844d-ce62ae954c66.jpg)

Xiaomi Redmi S2
MIUI Global 11.0.5
Android 9
