### ISSUE TITLE
 Come vengono rilevate tecnicamente le transazioni dall'app?

### ISSUE THREAD

**Issue by smartm0use** [pagopa/io-app#2976]
Salve,
occorrono dei giorni, mediamente 3 (come indicato in app), affinchè delle transazioni possano essere conteggiate dall'applicazione.
Le stesse nello storico dell'home banking non appaiono immediatamente oppure compaiono senza una descrizione dettagliata, che compare solo quando la transazione viene effettivamente contabilizzata.

In particolare, per quanto mi riguarda, nell'ultimo periodo mancano transazioni effettuate 7-10 giorni fa, forse per via delle festività pasquali... ma quindi in che modo il conteggio è inficiato dai giorni festivi?

Insomma, in generale, come vengono raccolte le transazioni dall'app e perchè alcune compaiono prima e altre dopo?

**Comment by thisisjp** [comment]
Ciao @smartm0use, in [questo articolo](https://medium.com/pagopa-spa/cashback-retrospettiva-su-un-avvio-sfidante-con-lo-sguardo-rivolto-al-futuro-206cb609e4bb) puoi leggere come funziona il sistema alla base del Cashback. Trovi anche un diagramma che illustra i numerosi attori coinvolti nel processo, con i vari flussi di informazioni.

Nello specifico, le transazioni vengono inviate dagli [Acquirer convenzionati](https://io.italia.it/cashback/acquirer/), ovvero i soggetti che si occupano di gestire le transazioni elettroniche. 

Siamo a conoscenza che l'aggiornamento delle transazioni relative al mese di aprile sta subendo dei ritardi, ma non sono imputabili ad app IO. Le transazioni valide degli ultimi giorni saranno presto visibili, insieme al calcolo del Cashback.

**Comment by smartm0use** [comment]
Grazie Jacopo, molto gentile ;)
