### ISSUE TITLE
Mancanti transazioni

### ISSUE THREAD

**Issue by comios0941** [pagopa/io-app#2979]
Alcune transazioni sono bloccate dall’app e non vengo registrate dall’sistema non prima di una settimana penso che si un overflow di informazioni

**Comment by smartm0use** [comment]
In che senso sono "bloccate" dall'app? Non rilevate?
Io ho decine di transazioni mancanti risalenti anche a 2 settimane fa...

**Comment by comios0941** [comment]
Si

Matteo Comi

**Comment by thisisjp** [comment]
Ciao @comios0941,
siamo a conoscenza che l'aggiornamento delle transazioni relative al mese di aprile sta subendo dei ritardi, ma non sono imputabili ad app IO.

Le transazioni vengono inviate dagli [Acquirer convenzionati](https://io.italia.it/cashback/acquirer/), ovvero i soggetti che si occupano di gestire le transazioni elettroniche.

Ad ogni modo, le transazioni valide degli ultimi giorni saranno presto visibili, insieme al calcolo del Cashback.

**Comment by smartm0use** [comment]
Ciao @thisisjp, che tu sappia il ritardo nell'acquisizione delle transazioni è qualcosa con cui l'app IO dovrà convivere per tutta la durata del programma Cashback o è relativo solo al mese di aprile?

![image](https://user-images.githubusercontent.com/5399265/115405682-c2f42280-a1ee-11eb-86a0-3835f419ee17.png)

Vedremo sempre questo bannerino nell'app?
