### ISSUE TITLE
Scrolling transazioni cashback a scatti

### ISSUE THREAD

**Issue by djechelon** [pagopa/io-app#3014]
**Descrivi il problema**
Con l'aumentare del numero di transazioni, si fa fatica a fare lo scrolling della schermata. Nonostante io abbia un telefono di ultim**issim**a generazione con tanta RAM, il gesto di scorrere non è sincronizzato con lo scorrimento ed il medesimo non è fluido

**To Reproduce**
1. Avere qualche centinaio di transazioni all'attivo
2. Aprire il dettaglio delle transazioni per la fase cashback corrente
3. Scroll down, appunto...
4. Dopo diverse decine di transazioni scrollate si nota l'effetto a scatti

**Expected behavior**
Lo scrolling dovrebbe rimanere fluido e sincronizzato coi movimenti del dito come in cima alla lista

**Versione dell'app**
1.24.0.6

**Smartphone (please complete the following information):**
 - Device: Pixel 5XL
 - OS: AOSP 11

**Additional context**
Sembra essere un tipico problema di gestione dei widget grafici in memoria durante lo scrolling. Si potrebbe pensare di caricare la lista dal server a blocchi in modalità di scrolling infinito (ma stiamo parlando di centinaia, non centinaia di migliaia, vero maghi della pompa?), ma piuttosto si dovrebbe fare in modo da deallocare i widget che scompaiono per effetto dello scrolling.

**Comment by fabriziofff** [comment]
Ciao, grazie per la segnalazione.
La gestione delle transazioni è stata completamente rivista nella pr https://github.com/pagopa/io-app/pull/2995 e collegate, introducendo logiche di paginazione ed ottimizzazione del rendering che saranno disponibili a partire dalla prossima versione dell'app.
