### ISSUE TITLE
Problemi con la registrazione delle transazioni, dopo aver cancellato e riattivato un metodo di pagamento.

### ISSUE THREAD

**Issue by iderose** [pagopa/io-app#3017]
Vado a descrivere il mio problema. Sono il possessore di una carta Credem, con circuito **_pagoBancomat_** e  **_Maestro_**.  Fino al 24 aprile, ho potuto utilizzare esclusivamente il circuito **_pagoBancomat_**, in quanto il sistema non mi faceva aggiungere il secondo circuito. Mia moglie che possiede la stessa tipologia di carta, si è inscritta al Cashback  di recente, registrando senza problemi sia il circuito **_pagoBancomat_**, che il circuito **Maestro**. 
Ho pensato allora che fosse necessario cancellare il metodo **_pagoBancomat_**  e successivamente riaggiungerlo insieme al circuito **_Maestro_**.  Effettivamente la procedura è riuscita in quando  adesso vedo entrambi i circuiti **attivi**, ma da quel giorno il 24 aprile, il sistema non mi registra più transazioni.

**Versioni**
App IO: v1.24.0.6
Android: 10 QkQ1.191215.002
Device: Redmi Note 9 pro
MIUI: 12.0.4

**Comment by thisisjp** [comment]
Ciao @iderose,
in che modo hai aggiunto il circuito Maestro? Hai dovuto inserire intestatario e numero carta?

Ad ogni modo, siamo al corrente che l'aggiornamento delle transazioni di alcuni acquirer relative al mese di aprile (in particolare a partire dal 24 aprile) sta subendo dei ritardi non imputabili ad app IO. 

Ti preghiamo di pazientare, presto tutte le transazioni saranno di nuovo visibili in app IO; considera, in ogni caso, che questi ritardi nella visualizzazione non inficiano sul tuo diritto a ricevere l'eventuale rimborso accumulato con le transazioni ad oggi mancanti.

Ti ricordiamo che le transazioni che visualizzi nella tua card Cashback corrispondono a tutte quelle che il sistema gestito dalla società PagoPA S.p.A. (responsabile della infrastruttura tecnologica alla base del Programma) riceve a sua volta dai cosiddetti "[Acquirer Convenzionati](https://io.italia.it/cashback/acquirer)", cioè i soggetti bancari che elaborano i pagamenti effettuati dai partecipanti nell'ambito del programma ai fini del rimborso.

**Comment by iderose** [comment]
> in che modo hai aggiunto il circuito Maestro

No non è stato necessario ho eseguito i seguenti passi:

1. Dalla Home  ho cliccato sulla metodo **pagoBancomat** 
2. Ho cliccato su aggiungi secondo circuito
3. Ho cliccato su "No la uso solo nei negozi"
4. La ricerca non ha dato esito positivo

A questo punto:

1. Ho cancellato il metodo di pagamento **pagoBancomat*
2. Dalla Home +Aggiungi
3. Aggiungi metodo di pagamento
4. Il metodo di pagamento **pagoBancomat** è stato aggiunto correttamente
5. Dalla Home  ho cliccato sulla metodo **pagoBancomat** appena aggiunto
6. Ho cliccato su aggiungi secondo circuito
7. Ho cliccato su "No la uso solo nei negozi"
8. Il circuito maestro è stato aggiunto in automatico

**Comment by thisisjp** [comment]
@iderose potresti per favore premere sulla carta Maestro all'interno del tuo Portafoglio e controllare:
- il logo mostrato in alto a sinistra (è Credem?)
- la data di scadenza (corrisponde a quella del tuo PagoBANCOMAT?)

Ho il sospetto che tu abbia aggiunto la carta Maestro di un'altra banca.

**Comment by iderose** [comment]
@thisisjp  il logo è quello di Credem, così come la data di scadenza è quella corretta:

![1620257405959](https://user-images.githubusercontent.com/69236988/117222095-fb107d80-ae0a-11eb-853a-a06454b77cf5.jpg)

**Comment by thisisjp** [comment]
Grazie @iderose,
abbiamo segnalato al fornitore del [servizio carte co-badge](https://io.italia.it/cashback/carta-non-abilitata-pagamenti-online/) il disguido relativo a Credem (in uno scenario normale non dovresti cancellare la carta per poter iniziare il flusso di aggiunta carta, è sufficiente premere il bottone "Aggiungi secondo circuito"), e il team è già al lavoro.

Per le segnalazioni mancanti, vale quanto scritto sopra ;)
