### ISSUE TITLE
Allineamento transazioni mancanti

### ISSUE THREAD

**Issue by gianlucapuleri** [pagopa/io-app#3019]
Nel corso di questi mesi ho sempre utilizzato due carte di credito (Nexi e PosteItaliane) sulle quali non ho mai avuto problemi inerenti a transazioni mancanti, ma dal 24/04 ad oggi diverse decine di transazioni non sono state registrate nonostante sulle carte siano contabilizzate da oltre una settimana. Le transazioni mancanti si riferiscono ad entrambe le carte e sono state effettuate presso esercenti nei quali non avevo mai riscontrato problemi prima. Inoltre, vengono registrate solo alcune transazioni e talvolta intervallate (nello stesso negozio: un giorno vengono registrate, quello successivo no, poi di nuovo sì ecc.).

Che il problema sia imputabile ad IO o meno, in IO è schedulato un flusso periodico di allineamento delle transazioni mancanti tra Acquirer Convenzionati e IO? Grazie

**Comment by iderose** [comment]
Stesso problema pure per me. Dal 24 aprile

**Comment by thisisjp** [comment]
Ciao,
siamo a conoscenza del problema e già al lavoro con gli Acquirer Convenzionati per ricevere le transazioni mancanti—il cui ritardo non è imputabile ad app IO.

Ti preghiamo di pazientare, presto tutte le transazioni saranno di nuovo visibili in app IO; considera, in ogni caso, che questi ritardi nella visualizzazione non inficiano sul tuo diritto a ricevere l'eventuale rimborso accumulato con le transazioni ad oggi mancanti.
