### ISSUE TITLE
Utilizzare la tastiera numerica per inserire il CVV

### ISSUE THREAD

**Issue by djechelon** [pagopa/io-app#3067]
**Descrivi il problema**

Sto pagando un avviso PagoPA da IO. All'inserimento, per conferma, del CVV della carta di credito registrata, mi viene presentata la tastiera touch integrale.

Sarebbe utile impostare la modalità solo numerica per semplificare l'inserimento del codice di tre cifre.

**Screenshots**
![Screenshot_20210527-135614.png](https://user-images.githubusercontent.com/3042285/119835165-e05c9080-bf00-11eb-9a8e-c761061a6653.png)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 5
 - OS: Android 11 AOSP

**Comment by thisisjp** [comment]
Ottimo feedback, grazie!
