### ISSUE TITLE
Loop infinito nella schermata di conferma del pagamento

### ISSUE THREAD

**Issue by djechelon** [pagopa/io-app#3068]
**Descrivi il problema**
Related #3067 

Dopo il pagamento che ho effettuato non ho chiuso completamente la app Io e ho navigato un po' nel cashback, lasciando anche il cellulare andare in standby per inattività.

Ora mi trovo davanti uno strano loop infinito all'andare indietro. Uscendo dal cashback e facendo indietro sullo schermo mi trovo nella schermata di conferma del pagamento di cui al 3067 ma andando di nuovo "indietro" con la navigazione Android mi viene proposto di "continuare" o "annullare" il pagamento. E passo dalla prima alla seconda schermata e di nuovo alla prima all'infinito.

Chiudere completamente l'app risolve il problema.

Non ho un'idea chiara di come si sia **innescato** il loop

**To Reproduce**
1. Fare un pagamento di un bollettino PagoPA
2. "Smanettare un po'" (per non dire ca**eggiare) col Cashback
3. Tornare indietro con la schermata

**Expected behavior**
A furia di battere indietro dovrei uscire da IO

**Screenshots**
![Screenshot_20210527-152745~2.png](https://user-images.githubusercontent.com/3042285/119835464-244f9580-bf01-11eb-8680-dcf5ca0993c5.png)![Screenshot_20210527-152735~2.png](https://user-images.githubusercontent.com/3042285/119835478-287bb300-bf01-11eb-981a-5933af8854cd.png)

**Versione dell'app**
1.25.0.14

**Smartphone (please complete the following information):**
 - Device: Google Pixel 5
 - OS: AOSP 11

**Comment by thisisjp** [comment]
Grazie per la segnalazione @djechelon, faremo le opportune verifiche.
Giusto per capire: quando parli di "fare indietro" intendi con il tasto del tuo dispositivo o con la freccia in alto a sinistra?

**Comment by djechelon** [comment]
Faccio "swipe" sul bordo dello schermo per tornare indietro col dispositivo
https://support.google.com/pixelphone/answer/6073614?hl=en

Lato API vale come pressione del tasto back, che non ho in fondo allo schermo come i vecchi modello

**Comment by djechelon** [comment]
A parte che negli screen non vedo nessuna freccia in alto a sx
