### ISSUE TITLE
Rendere l'uso di MixPanel GDPR compliant

### ISSUE THREAD

**Issue by studiofuga** [pagopa/io-app#3137]
**Descrivi il problema**
Come da provvedimento del Garante della privacy del 9 giugno 2021, l'uso di alcuni tracker senza adeguata informativa verso il cliente è non accettabile.

Si suggerisce l'approccio utilizzato più di frequentemente in molte altre applicazioni, ossia quello di rendere facoltativo l'OPT-IN all'invio di tali telemetrie al servizio MixPanel.

Fattivamente, la cosa può essere realizzata introducendo un flag persistente (default false) il quale previene la chiamata al metodo `mixpanel.track()` nella funziona `mixpanelTrack()` del file `mixpanel.ts` (e altrove se necessario). 

In una opportuna posizione della UI può essere fatto richiesta all'utente dell'attivazione di tale flag al fine di migliorare l'esperienza utente; accanto a questo, una pagina di spiegazioni con le conseguenze dell'attivazione delle telemetrie anche in relazione agli eventuali dati personali e all'ID univoco.

**Comment by Undermaken** [comment]
Risolta da https://github.com/pagopa/io-app/pull/3145
