### ISSUE TITLE
Schermata "La Certificazione Verde COVID_19 su IO" riproposta durante la scelta di condivisione dati

### ISSUE THREAD

**Issue by giovannifil-64** [pagopa/io-app#3157]
Ho notato che nell'ultima versione dell'app per iOS disponibile sull'App Store (1.27.0), durante l'onboarding per accettare o meno la condivisione dei dati con Mixpanel, se premo su "Non Condividere" appena compare lo sheet per confermare la scelta o meno, viene di nuovo mostrata la schermata "La Certificazione Verde COVID_19 su IO" nonostante essa fosse già stata mostrata all'utente. Ho provato su più dispositivi e succede lo stesso.

**Smartphone**
 - Device: iPhone6S, iPhone 11 Pro
 - OS: iOS14.5, iOS 13.6

**Comment by Undermaken** [comment]
Ciao. L'opt-in/out di Mixpanel non è legato con il _what's new_ che viene mostrato e informa su cosa è possibile fare con la versione 1.27.0

Ci aspettiamo che dopo aver scelto `HO CAPITO` nella schermata _what's new_, quest'ultima non compaia più. In ogni caso è un avviso temporaneo che disabiliteremo presto appena questa nuova versione sarà stata sufficientemente adottata dagli utenti

**Comment by giovannifil-64** [comment]
Capito, l'ho segnalato perché mi sembrava un comportamento strano, ma capisco la casistica. Grazie mille per la risposta
