### ISSUE TITLE
Aggiunta dell’animazione quando si torna alla pagina precedente e Dark Mode

### ISSUE THREAD

**Issue by giovannifil-64** [pagopa/io-app#3174]
Sin da quando ho iniziato ad usare IO ho notato la mancanza dell'animazione per quando si torna indietro tra una pagina e l'altra, cosa a mio parere importante, poiché tornare alla schermata precedente e non avere una animazione sembra quasi una dimenticanza.
Altra cosa che sarebbe molto bello da avere è l'implementazione del tema scuro sull'app, visto che ormai tutti i vari OS offrono questa opzione all'utente.

**Comment by Undermaken** [comment]
Ciao. L'animazione di back non è presente per via di un bug della libreria di navigazione (react-navigation). La fix è stata fatta ormai tempo fa dai manutentori della libreria, è un nostro debito tecnico che speriamo di risolvere a breve.

Il dark mode è una funzione che introdurremo appena siamo certi di garantirne l'accessibilità, su cui lavoriamo tuttora sull'attuale UI/UX

**Comment by giovannifil-64** [comment]
Perfetto, allora non resta che aspettare l'implementazione di queste due opzioni. Inoltre, è per forza obbligatorio mostrare ogni volta questa schermata al login o può essere nascosta e mostrata solo in caso di debug?![image](https://user-images.githubusercontent.com/39963191/124514507-7e375b00-dddd-11eb-9326-639185aee6d3.png)

**Comment by Undermaken** [comment]
@thisisjp :point_up_2:

**Comment by thisisjp** [comment]
@giovannifil-64 è un chiaro omaggio al BIOS dei vecchi Pentium, non trovi? 😄 
Scherzi a parte, è una schermata che nel 99% dei casi scompare in pochi secondi—ma in caso di problemi torna molto utile capire a colpo d'occhio cosa c'è che non sta funzionando.

Confermo che il lavoro di miglioramento della UI non finisce mai, e in futuro potrebbe arrivare il dark mode—compatibilmente con le altre attività che abbiamo in roadmap.

Grazie per I feedback 🚀

**Comment by davcec** [comment]
> mostrare ogni volta questa schermata al login [image](https://user-images.githubusercontent.com/39963191/124514507-7e375b00-dddd-11eb-9326-639185aee6d3.png)

@thisisjp visto che avete già aperta https://www.pivotaltracker.com/story/show/172649001, si potrebbero inserire quelle info [direttamente nella schermata iniziale](https://github.com/pagopa/io-app/blob/f09c6966f8d61b4d8bc15fd51a0dc0a4633aec57/android/app/src/main/res/layout/launch_screen.xml#L48) (e.g. testo sotto al logo di IO che si aggiorna), almeno è più carina... :wink:

**Comment by giovannifil-64** [comment]
Concordo in @davcec, si potrebbe aggiungere questa opzione nella schermata iniziale, nonostante sia una schermata di pochi secondi, e fare in modo che venga mostrato un eventuale errore mediante un messaggio che spiga cosa non sia andato a buon fine.
P.S. Dato che pivotaltracker ormai non viene aggiornato poiché ci si è spostati su Jira & co di Atlassian, si potrebbe avere accesso alla "bacheca" oppure è qualcosa di strettamente interno?

**Comment by davcec** [comment]
>nonostante sia una schermata di pochi secondi

La schermata iniziale andrebbe ovviamente chiusa solo dopo che tutti i passi d'inizializzazione sono stati completati. :wink:

**Comment by davcec** [comment]
>Dato che pivotaltracker ormai non viene aggiornato poiché ci si è spostati su Jira & co di Atlassian

Sì, è un peccato non poter più seguire gli sviluppi dell'app IO... :confused:
