### ISSUE TITLE
Green pass digitale scadenza

### ISSUE THREAD

**Issue by MastroFelice** [pagopa/io-app#3190]
Green pass digitale su app IO o su immuni ottimo, però suggerei all’interno del pass anche una data di scadenza, (attualmente c’è scritto solo quanti giorni vale) oppure un conto alla rovescia per ricordare la scadenza…

**Comment by davcec** [comment]
> suggerei all’interno del pass anche una data di scadenza, (attualmente c’è scritto solo quanti giorni vale) oppure un conto alla rovescia per ricordare la scadenza…

Magari anche un messaggio sull'app IO stessa che arrivi in prossimità della scadenza.

**Comment by filioro** [comment]
Ciao! In questo caso bisognerebbe segnalare l'idea a chi gestisce la piattaforma DGC in quanto sono loro a fornire il servizio su IO.

:)
