### ISSUE TITLE
Esportare Green Pass in formato PNG

### ISSUE THREAD

**Issue by FabioPedretti** [pagopa/io-app#3192]
L'esportazione del Green Pass avviene attualmente in formato JPEG, formato che è stato pensato per immagini fotografiche.

Sarebbe preferibile se fosse esportata in formato PNG, in modo da non avere perdite di qualità derivanti dalla compressione JPEG, inoltre avrebbe probabilmente anche una minore occupazione di spazio.

![jpg_vs_png2](https://user-images.githubusercontent.com/3390837/124316807-77f37580-db76-11eb-8448-f9a95b25ac5c.png)

**Comment by Undermaken** [comment]
Mi sembra un ottima osservazione. Peraltro non mi vengono in mente limiti tecnici per cui il formato PNG non possa essere utilizzato.

https://github.com/pagopa/io-app/blob/f3e1b8e6aec191e9c1cf44184645f13daea1f27d/ts/features/euCovidCert/screens/valid/EuCovidCertValidScreen.tsx#L220

Faremo una PR per includere questa modifica nella nostra beta interna. In caso non ci siano show stopper, verrà rilasciata con il prossimo aggiornamento.

Ulteriori updates su questa issue

**Comment by pietro909** [comment]
https://github.com/pagopa/io-app/pull/3199

**Comment by fabriziofff** [comment]
risolta in https://github.com/pagopa/io-app/pull/3199
