### ISSUE TITLE
[iOS] Le informazioni sulla barra in alto sono bianche su sfondo chiaro 

### ISSUE THREAD

**Issue by alessiomatricardi** [pagopa/io-app#3198]
**Descrivi il problema**
Nella sezione "profilo" dell'app, quando si accede a qualsiasi pannello avanzato (Preferenze, Privacy, Informazioni su IO, ...) la barra posta in alto del mio iPhone 8 ha le scritte di colore bianco, che non si vedono sullo sfondo chiaro dei pannelli.

**To Reproduce**
1. Andare nella sezione profilo. Verificare che la barra ha scritte bianche su sfondo "blue Gray"
2. selezionare qualsiasi sotto-sezione tra quelle sopra indicate, verificare che le scritte rimangono bianche su sfondo chiaro

**Expected behavior**
Accedendo a queste sotto-sezioni, le scritte sulla barra dovrebbero essere di colore scuro (presumibilmente nere).

**Screenshots**
Sezione profilo             |  Sotto-sezione casuale
:-------------------------:|:-------------------------:
![IMG_4399](https://user-images.githubusercontent.com/26736913/124496236-749bfc00-ddb9-11eb-8427-b2cb0365fd9a.PNG) | ![IMG_4400](https://user-images.githubusercontent.com/26736913/124495843-e758a780-ddb8-11eb-8d50-dded2a847222.PNG)`

**Versione dell'app**
1.28.0 rc 4

**Smartphone (please complete the following information):**
 - Device: iPhone 8 64GB
 - OS: iOS 14.6, iOS 15 beta 2

**Additional context**
Il problema si verifica con sia con la dark mode che senza.

**Comment by thisisjp** [comment]
Grazie per il feedback @alessiomatricardi!
Siamo a conoscenza del problema e lo stiamo affrontando nelle diverse schermate coinvolte.

In uno dei prossimi aggiornamenti dell'app dovresti vedere le modifiche apportate 🚀

**Comment by alessiomatricardi** [comment]
Problema non ancora risolto
