### ISSUE TITLE
[suggerimento] container logo e nome pannello troppo grandi

### ISSUE THREAD

**Issue by alessiomatricardi** [pagopa/io-app#3224]
Vorrei segnalarvi che, con un dispositivo di “piccole” dimensioni (eg < 5.5’’) l’accesso alle informazioni di una schermata è davvero molto limitato a causa del troppo spazio occupato in alto ed in basso.

<img src="https://user-images.githubusercontent.com/26736913/125443040-39b49a34-aa84-4e78-984d-47af988a6c06.png" height="700" />

ad esempio, questo è un iPhone 8. Lo schermo dovrebbe essere 4.7’’. Lo scrollpane dei servizi occupa neanche il 50%  di tutto lo schermo. Se il main menù ed il banner delle preferenze sono importanti, lo stesso non si può dire della parte superiore dello schermo. I due pannelli (quello dove viene mostrato il logo e quello dove è mostrato il nome della schermata (in questo caso, Servizi) sono un pugno in un occhio e davvero limitanti.
Lo stesso problema di usabilità si riesce a percepirlo nella schermata del wallet dove, complice il banner “il cashback per ora è sospeso” e “paga avviso pagopa”, si ha l’idea di una interazione ridotta, quasi claustrofobica.

Vi suggerisco di ridimensionare e snellire tutte quelle zone che appesantiscono davvero troppo lo schermo. Prendete ad esempio le app iOS di Instagram e Facebook, sono riusciti ad ottimizzare lo spazio al massimo.

PS vedo che siete sempre molto impegnati ad implementare nuove features per stare al passo dei decreti attuativi del governo, immagino sia un lavoraccio 😥
Buon lavoro 🙏🏼

**Comment by thisisjp** [comment]
Ciao @alessiomatricardi, grazie come sempre dei tuoi feedback!
La sezione servizi è in continuo miglioramento—non vediamo l'ora di farvi vedere cosa abbiamo disegnato 🤞 

Nel nostro backlog abbiamo un sacco di interventi per migliorare il layout su schermi piccoli—speriamo di poterci lavorare presto 🚀 

P.S.: lo sai che PagoPA è sempre alla ricerca di nuovi talenti? Tieni d'occhio [questa pagina](https://www.pagopa.gov.it/it/pagopa-spa/societa-trasparente/selezione-del-personale/reclutamento-del-personale/lavora-con-noi/) 😉

**Comment by alessiomatricardi** [comment]
> Nel nostro backlog abbiamo un sacco di interventi per migliorare il layout su schermi piccoli—speriamo di poterci lavorare presto 🚀

Perfetto :)

> P.S.: lo sai che PagoPA è sempre alla ricerca di nuovi talenti? Tieni d'occhio [questa pagina](https://www.pagopa.gov.it/it/pagopa-spa/societa-trasparente/selezione-del-personale/reclutamento-del-personale/lavora-con-noi/) 😉

Grazie! Finita l'università darò un'occhiata 😉

**Comment by Undermaken** [comment]
@thisisjp possiamo chiudere la issue?
