### ISSUE TITLE
TS-CNS

### ISSUE THREAD

**Issue by xpitt** [pagopa/io-app#3249]
Ho abilitato il chip della mia tessera sanitaria e posso ora accedere con essa ad esempio all'inps o all'agenzia entrate. Come mai non sembra previsto il suo utilizzo per avere il green pass, un servizio sanitario?

Pensate di provvedere al suo utilizzo per poter utilizzare l'app io? E, in questo caso, segnalarlo opportunamente?

Grazie

Mario Pitteri

**Comment by pietro909** [comment]
@xpitt utilizzi un lettore di smart-card per accedere via tessera sanitaria?

**Comment by xpitt** [comment]
Certo, niente smartphone
