### ISSUE TITLE
Banner rende impossibile filtrare i servizi

### ISSUE THREAD

**Issue by nu111** [pagopa/io-app#3258]
Il banner "hai scelto la configurazione rapida" rende impossibile filtrare i servizi locali.

Inoltre il banner copre i risultati di ricerca.
Qui un video che riproduce la cosa
https://drive.google.com/file/d/1eeTURelxVSKXMACfYBZXxkEDlNISiRIV/view?usp=drivesdk

Versione app: 1.30.0.2

Decide Xperia zx1 compact
OS: Android 9

**Comment by pietro909** [comment]
Grazie per la segnalazione @nu111 stiamo lavorando per sistemarla.

Ticket collegato a #3282
