### ISSUE TITLE
Esportare Green Pass in Apple and Google Wallet

### ISSUE THREAD

**Issue by Krusty93** [pagopa/io-app#3259]
**Qual è il problema che vorresti risolvere?**
Attualmente è possibile esportare il Green Pass solo come immagine; tuttavia sarebbe molto più comodo (e sicuro) poterlo esportare nel Wallet del proprio telefono tramite Apple Wallet e Google Wallet

**Quale soluzione proponi?**
Nel momento in cui si preme "Salva dettagli", un popup dovrebbe chiedere come si preferisce effettuare l'operzazione. Nello specifico:
- Galleria (feature attuale)
- Wallet

Valuterei anche l'impossibilità di esportare l'immagine nella galleria del telefono: potrebbe essere un modalità di falsificazione dei certificati

**Comment by Marlowess** [comment]
Duplicato: https://github.com/pagopa/io-app/issues/3168

**Comment by pietro909** [comment]
Discussione in #3168
