### ISSUE TITLE
Sezione documenti

### ISSUE THREAD

**Issue by simofdo92** [pagopa/io-app#3264]
**Qual è il problema che vorresti risolvere?**
Sarebbe bello poter avere sottomano i principali documenti italiani (carta d’identità, patente, codice fiscale, passaporto) e creare un SDK con API dedicate sfruttabili dai vari enti per rilasciare biglietti, certificazioni o pass (tessere mezzi pubblici, pass mense, prenotazioni luoghi pubblici, certificati vaccinali) compatibili con Wallet di iOS e Android.

**Comment by thisisjp** [comment]
Grazie per il feedback! Per comodità chiudo, c'è già una segnalazione aperta simile: #3173
