### ISSUE TITLE
Übersetzungen

### ISSUE THREAD

**Issue by andr223** [pagopa/io-app#3277]
1. Conto--> Zahlungsmethoden--> "Aggiorna"= Aktualisieren.
2.  Conto-->Ihre letzten Transaktionen--> "Mostra operazioni"= Zeige Transaktionen
3. Dienste--> Notional--> "Ministero della Salute"= Gesundheitsministerium

**Comment by thisisjp** [comment]
Grazie mille @andr223!
Abbiamo aggiunto "Zeige Transaktionen" ("Aktualisieren" era stato già aggiunto, ma lo vedrai con il prossimo aggiornamento dell'app). Al momento i nomi degli Enti non supportano più lingue, ma terremo in considerazione il feedback per il futuro ;)
