### ISSUE TITLE
messaggio fastidioso

### ISSUE THREAD

**Issue by MastroFelice** [pagopa/io-app#3282]
![F8E92F64-5AD4-4D51-987D-C9EB19BE93DC_1_201_a](https://user-images.githubusercontent.com/86830895/128226742-323145e5-f14e-4796-a8d6-c203342cae37.jpeg)

**Comment by thisisjp** [comment]
Grazie del feedback @MastroFelice, siamo già al lavoro per risolvere il problema 💪
