### ISSUE TITLE
[IABT-1231] Perdita sessione dopo tasto indietro

### ISSUE THREAD

**Issue by djechelon** [pagopa/io-app#3285]
**Descrivi il problema**
Rifatto login con SPID lv2, visualizzata schermata principale di IO.
Tasto indietro riporta alla pagina di login.
Chiudendo IO viene chiesto il PIN di IO (le 6 cifre per capirci) e poi di nuovo login

L'istanza di IO installata è pregressa, cioè questa login è dovuta alla scadenza delle credenziali SPID e non è quindi un "primo accesso"

**Fortunatamente** il problema non sembra persistente, cioè se chiudo e riapro la app forzatamente torno ai messaggi dopo aver inserito il PIN di 6 cifre.
Però secondo me si ripeterà dopo il prossimo mese di scadenza, quindi meglio segnalare comunque almeno per tener traccia.

**To Reproduce**
1. Ho aperto app Io su Android da icona
1. Ho fatto login con Aruba Spid, inserendo username, password e OTP L2
2. Immediatamente mi è comparso il messaggio di congratulazioni per il cashback
3. Ho navigato i messaggi
4. Dalla schermata dei messaggi ho usato il tasto "Indietro" del telefono
5. Atterro su una schermata blu con una "grossa" spunta ✔ bianca
6. Di nuovo indietro, sperando di chiudere la app, atterro sulla schermata di scelta del provider SPID
7. A quel punto torno alla home del telefono
8. Riapro app Io da icona
9. Mi viene chiesto il PIN di 6 cifre ricordo dei mesi passati
10. Inserito il PIN mi viene nuovamente richiesta la login SPID

**Expected behavior**
Al punto 5 IO avrebbe dovuto chiudersi

**Screenshots**
Provo a non farne. Se il problema dovesse essere deterministicamente ripetibile li allego

**Versione dell'app**
1.31.0.3

**Smartphone (please complete the following information):**
 - Device: Nokia 7.1
 - OS: Android AOSP 10

**Additional context**
Secondo me dovuto a qualche problema nella gestione del breadcrumb di navigazione lato codice.
Fortunatamente riesco a non dover rifare la login semplicemente chiudendo la app forzatamente.
Avrei cancellato i dati come step successivo.

**Comment by thisisjp** [comment]
Grazie @djechelon, analizzeremo il problema e ti faremo sapere 💪

**Comment by Undermaken** [comment]
ciao @djechelon 
quando dici
> Immediatamente mi è comparso il messaggio di congratulazioni per il cashback

intendi che ti è arrivata una notifica?

**Comment by djechelon** [comment]
No, non la notifica. Si è aperto il messaggio di congratulazioni. La notifica era giunta in passato. Sono stato settimane senza rifare la login

**Comment by marcodadamo** [comment]
Nell'ultimo aggiornamento il bug è stato risolto

**Comment by pietro909** [comment]
Grazie @marcodadamo ! Se @djechelon riesce a confermare possiamo chiudere anche la issue :-)

**Comment by djechelon** [comment]
Non ho possibilità di verificare non essendo mio il dispositivo.
Chiudete pure
