### ISSUE TITLE
Menu servizi, visualizzabile il certificato GREEN PASS

### ISSUE THREAD

**Issue by marcodadamo** [pagopa/io-app#3308]
**Quale soluzione proponi?**
Introdurre all'interno dell'area servizi, oltre all'area messaggi, la possibilità di visualizzare il certificato verde dalla scheda certificazione verde COVID-19.
In allegato l'immagine di esempio del funzionamento descritto. 

![IMG_20210818_003658_991](https://user-images.githubusercontent.com/56562822/129809758-53924662-4395-4196-ad8b-dc899f8ca1e5.jpg)
Cosa ne pensi di questa integrazione ? @thisisjp

**Comment by thisisjp** [comment]
Ciao @marcodadamo, la certificazione verde è uno dei cosiddetti servizi “push”: quando l’ente ha qualcosa da dirti (in questo caso il Ministero della Salute) ti manda direttamente un messaggio. 

Siamo al lavoro per arricchire la sezione Servizi e offrire modalità “pull” quando il caso d’uso lo richiede (es.: presentare un’istanza, richiedere un voucher, etc).

Raccogliamo comunque il feedback: mi sembra di capire che ti piacerebbe avere un modo rapido per aprire messaggi “più importanti” di altri ☑️

**Comment by marcodadamo** [comment]
Grazie per la disponibilità e la collaborazione nel dialogo. @thisisjp
