### ISSUE TITLE
Left to right swipe to go back

### ISSUE THREAD

**Issue by sim-1998** [pagopa/io-app#3315]
**Qual è il problema che vorresti risolvere?**
Su schermi di grosse dimensioni può essere a volte scomodo dover sempre centrare, con una sola mano, il tasto back in alto a sinistra nelle varie schede. 

**Quale soluzione proponi?**
Suggerirei che sarebbe molto utile introdurre anche il go back facendo swipe “left to right”.

**Comment by thisisjp** [comment]
Ciao @sim-1998, siamo a conoscenza del problema :) Stiamo aggiornando le librerie di React Navigation per supportare a pieno questo tipo di gestures. Ne daremo evidenza appena possibile 🚀

**Comment by sim-1998** [comment]
> Ciao @sim-1998, siamo a conoscenza del problema :) Stiamo aggiornando le librerie di React Navigation per supportare a pieno questo tipo di gestures. Ne daremo evidenza appena possibile 🚀

Ottimo 😉🚀🚀
