### ISSUE TITLE
Errore di autenticazione con SPID

### ISSUE THREAD

**Issue by marcodadamo** [pagopa/io-app#3321]
**Descrivi il problema**
Durante la procedura di inserimento dati di accesso all'app IO mediante SPID e confermare l'autenticazione il sistema rilascia un errore, pertanto bisogna rifare il percorso di autenticazione questa volta con SMS, in  modo tale da avviare la comunicazione dati e l'apertura dell'app io.
Sistema utilizzato ANDROID

@thisisjp

**Comment by thisisjp** [comment]
Ciao @marcodadamo, puoi specificare qual è l'Identity Provider che stai utilizzando?

> il sistema rilascia un errore

Dove avviene questo errore? Hai uno screenshot?

Tutto ciò che avviene in fase di login avviene in webview ed è indipendente da app IO—in generale ti invito a contattare l'assistenza del tuo Identity Provider.
