### ISSUE TITLE
Riconoscimento facciale non disponibile su dispositivo Android

### ISSUE THREAD

**Issue by Simone7monaco** [pagopa/io-app#3337]
**Problema**
Nell'accesso all'app non compare la possibilità di utilizzare il riconoscimento biometrico (riconoscimento facciale) come modalità di autenticazione. Sotto la voce "Sicurezza" viene mostrato il testo _"Gestisci accesso biometrico e codice di sblocco"_, ma a differenza di dispositivi che dispongono di sensore di impronta o di dispositivi iPhone con riconoscimento facciale nel menù contestuale non compare l'opzione per attivare tale funzione.

**Versione dell'app**
1.32.0.3

**Smartphone:**
 - Device: Pixel 4
 - OS: Android 11

**Comment by fabriziofff** [comment]
Ciao @Simone7monaco, grazie per la segnalazione! 
Il problema è probabilmente riconducibile alla libreria che si occupa dell'autenticazione biometrica, per la quale è già programmata la sostituzione in quanto obsoleta.

**Comment by pietro909** [comment]
@fabriziofff questa issue potrebbe parzialmente includere https://github.com/pagopa/io-app/issues/2498 ?

**Comment by fabriziofff** [comment]
@pietro909 si, è sempre riconducibile alla sostituzione della libreria di autenticazione biometrica che al momento non rileva su Android la presenza del riconoscimento facciale.
