### ISSUE TITLE
Alcuni bottoni e titoli delle NavBar non sono mostrati o distanziati nel modo corretto

### ISSUE THREAD

**Issue by giovannifil-64** [pagopa/io-app#3364]
**Descrivi il problema**
Nelle sezioni "indirizzo email", "avviso di pagamento" e "attivazione" (quando vado a modificare il pin d'accesso) i pulsanti per confermare o meno l'azione non sono correttamente distanziati dalla parte inferiore dello schermo.

Inoltre in alcune sezioni dove non è disponibile il pulsante "?", come per esempio la pagina "Privacy" per l'aiuto il testo nella NavBar non è centrato.

**Screenshots**
![image](https://user-images.githubusercontent.com/39963191/132762433-7996ac31-0733-429c-bef2-7e8b1c541196.jpeg)

![image](https://user-images.githubusercontent.com/39963191/132762444-acdf1ab2-2956-47a0-8f58-222a1a96683a.png)

![image](https://user-images.githubusercontent.com/39963191/132762494-60422a91-1ed0-40f9-aeaf-bf38bb3c154a.jpeg)

![image](https://user-images.githubusercontent.com/39963191/132762521-78029073-2f06-4120-851c-8feda694a168.png)

**Versione dell'app**
Versione 1.33.0.16

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 13.6.1

**Additional context**
Sempre nella sezione "avviso di pagamento" l'immagine del bollettino PagoPA è in una risoluzione molto bassa, starebbe meglio in una risoluzione maggiore, magari come vettoriale.

**Comment by thisisjp** [comment]
Grazie @giovannifil-64, sono entrambi due problemi noti e in corso di risoluzione ;)

**Comment by pietro909** [comment]
Ci sono due issues qui:

1. la safe area in alcuni modelli e' un follow up di https://www.pivotaltracker.com/n/projects/2048617/stories/176660226 e probabilmente relativo a https://github.com/pagopa/io-app/pull/2795
2. la centratura del titolo e' aperto su https://www.pivotaltracker.com/n/projects/2048617/stories/174061718 e disponibile (per il team interno: https://pagopa.atlassian.net/browse/IA-256)

@giovannifil-64 e/o chi fosse interessato a contribuire, queste sono entrambe buone opportunita' per un intervento circoscritto, testabile, e relativamente semplice.

**Comment by pietro909** [comment]
https://github.com/pagopa/io-app/pull/3404
