### ISSUE TITLE
IO non riconosce CIE per login

### ISSUE THREAD

**Issue by emmecii** [pagopa/io-app#3384]
**Descrivi il problema**
Segnalo impossibilità ad effettuare il login tramite CIE a seguito di aggiornamento da Android 10 ad Android 11 su Nokia 5.3

**To Reproduce**
 Dopo aver inserito il PIN della CIE, mettendo poi la CIE sul lettore NFC, viene visualizzato questo errore

![immagine](https://user-images.githubusercontent.com/22106041/133493145-06323b89-1e21-418b-b958-c74e26ca0f2d.png)

La CIE viene regolarmente letta dal chip NFC del telefono tramite app come NFC Tools perciò escludo un problema al chip della CIE. La carta non viene mossa durante la lettura del chip. Lettura che termina subito appena viene rilevato il chip con il suono caratteristico di fine lettura ma che ora mostra l'errore dello screenshot allegato.

Possiedo un Nokia 5.3 aggiornato all’ultima versione di Android disponibile di Android 11,.L’ultima volta che ho effettuato il login un paio di mesi fa con CIE la versione di Android presente sullo stesso telefono era la versione 10 che non presentava problemi di login

**Expected behavior**
Autenticazione su IO da CIE senza problemi

**Screenshots**

**Versione dell'app**
1.33.0.16

**Smartphone (please complete the following information):**
 - Device: Nokia 5.3
 - OS: Android 11 con  Android One, ultimo aggiornamentio 1 agosto 2021

**Comment by Undermaken** [comment]
Ciao. Hai provato ad eseguire la lettura con [CieID](https://play.google.com/store/apps/details?id=it.ipzs.cieid&hl=it)?
Riesci con quest'app a riconoscere la tua CIE?

@fventola98

**Comment by emmecii** [comment]
> Ciao. Hai provato ad eseguire la lettura con [CieID](https://play.google.com/store/apps/details?id=it.ipzs.cieid&hl=it)?
> Riesci con quest'app a riconoscere la tua CIE?
> 
> cc @fventola89

Essendo già precedentemente autenticato (quando ancora avevo Android 10 prima dell'aggiornamento alla versione 11)  ho disinstallato e reinstallato CieID, ora ri registrando la CIE ricevo lo stesso tipo di errore e non posso continuare. Confermo che NFC è attivo e funzionante sul telefono, solo non funziona la lettura con IO e ora CieID

![immagine](https://user-images.githubusercontent.com/22106041/133498580-5a9e27a0-1031-48e2-b5f6-a2f1d8471a47.png)

**Comment by fventola89** [comment]
E' stato aggiunto questo messaggio bloccante per evitare problemi su alcuni dispositivi che hanno disabilitato le APDU estese necessarie per comunicare con la tecnologia NFC con la CIE 3.0. Il controllo avviene utilizzando il metodo esposto dalle API Android, a questa [pagina](https://developer.android.com/reference/android/nfc/tech/IsoDep#isExtendedLengthApduSupported()). 

Purtroppo sembra che questo controllo non funzioni correttamente su tutti i dispositivi (casi di falsi positivi), nei prossimi giorni rilasceremo una nuova versione di CieID che renderà il messaggio non bloccante e che permetterà di provare a leggere comunque la CIE.

**Comment by emmecii** [comment]
> E' stato aggiunto questo messaggio bloccante per evitare problemi su alcuni dispositivi che hanno disabilitato le APDU estese necessarie per comunicare con la tecnologia NFC con la CIE 3.0. Il controllo avviene utilizzando il metodo esposto dalle API Android, a questa [pagina](https://developer.android.com/reference/android/nfc/tech/IsoDep#isExtendedLengthApduSupported()).

Questo vale, per quello che mi sembra di capire, solo per vecchi device? Perchè non penso che il mio telefono, da un giorno all'altro dopo l'aggiornamento di sistema, all'improvviso non supporta le APDU estese

**Comment by fventola89** [comment]
Purtroppo molti dispositivi dall'aggiornamento ad Android 11 hanno iniziato ad avere problemi e abbiamo dovuto introdurre questo controllo.

**Comment by emmecii** [comment]
Io oggi avrei riprovato a loggarmi con la CIE sia su Io che su CieID ma ancora non viene letta, il problema è stato risolto?

**Comment by emmecii** [comment]
Tutt'ora il problema persiste e la cosa devo dire la verità non mi piace dato che era una funzionalità che prima era presente e funzionava e ora non più, ed essendo un servizio statale peraltro il problema è ancora più fastidioso e va ad annullare gli effetti benefici della CIE sull'agenda digitale del paese
