### ISSUE TITLE
Stato certificazione verde direttamente in app

### ISSUE THREAD

**Issue by cadaniele** [pagopa/io-app#3413]
**Qual è il problema che vorresti risolvere?**
Molte persone purtroppo mostrano una certificazione verde non più valida.

**Quale soluzione proponi?**
Sarebbe molto comodo che Io potesse già mostrare lo stato (valido oppure no) direttamente anche al proprietario senza aspettare che venga letto dall'app VerificaC19

**Hai già considerato soluzioni alternative?**
Stessa cosa sarebbe utile anche sull'app  Immuni

**Altre informazioni**

**Comment by davcec** [comment]
Ref. #3190

**Comment by cadaniele** [comment]
Grazie
Però in quello viene chiesto di inserire la data di scadenza ma io penso più a uno stato in base ad una verifica con le stesse regole dell'app verifica C19.
Un green pass revocato risulterebbe non valido anche se non ancora scaduto.

**Comment by ItsFiloHere** [comment]
La soluzione potrebbe essere abbastanza semplice. In Austria, nell'app Grüner Pass, è possibile caricare i propri Green Pass e ogni volta che la si apre verifica se il certificato è valido o scaduto (penso che venga analizzata la data di emissione e la prestazione effettuata), ma in ogni caso mostra ancora il QR Code (semplicemente esce una spunta verde o rossa sotto al certificato).

**Comment by fabriziofff** [comment]
Ciao,
da qualche settimana la piattaforma DGC restituisce lo stato di "certificato scaduto", per questo motivo è ora possibile riconoscere i certificati non più validi, ricevuti su app IO.
Aprendo un messaggio con green pass scaduto, si visualizza la seguente schermata:
<img width="300" alt="Schermata 2021-11-29 alle 11 46 11" src="https://user-images.githubusercontent.com/26501317/143854226-ae8bf6b0-9a08-465c-b43d-20e855b5e6bd.png">
Per questo motivo la issue può essere ora chiusa.
