### ISSUE TITLE
Error login access Green Pass

### ISSUE THREAD

**Issue by marcodadamo** [pagopa/io-app#3416]
**Errore Avvenuto**
Errore test  durante l'apertura del certificato green pass. Scansione schermata di errore.

**Screenshots**
![20211004_131549](https://user-images.githubusercontent.com/56562822/135842371-f46e1bba-bfd3-404c-8f99-78910bcc62a6.jpg)

**Versione dell'app**
Versione dell'app su cui è stato riscontrato l'errore dati n. 1.32.0.3

**Smartphone  di verifica(please complete the following information):**
 - android 

@thisisjp

**Comment by fabriziofff** [comment]
Ciao @marcodadamo, puoi riprovare? Quella schermata viene visualizzata in caso di errore temporaneo. Non risultano esserci disservizi al momento.

**Comment by marcodadamo** [comment]
Verifica Test su Io app su Android. Durante la fase login, accedendo alla sezione green pass verifico l'esattezza della comunicazione nei dati nonché la corretta visualizzazione del certificato. Pertanto risulta eseguibile l'azione green pass
