### ISSUE TITLE
Errore in clone master

### ISSUE THREAD

**Issue by stefanosisto** [pagopa/io-app#3479]
Ciao,
ho provato a clonare il master per lanciare l'app in production mode, ma è presente un errore nel file i18n.ts:

`import { PreferredLanguageEnum } from "../definitions/backend/PreferredLanguage";`
`import { BackendStatusMessage } from "../definitions/content/BackendStatusMessage";`

Questi due import falliscono. Ho notato che sono stati inseriti nella commit 8f0db6878770792d08db5ae80dfa05fdcdebc8e4 ma non sono stati aggiungi (nella stessa commit) i file necessari per queste enum.

Forse sbaglio io a lanciare il master?

**Comment by fabriziofff** [comment]
Ciao @stefanosisto, hai eseguito anche questo passo https://github.com/pagopa/io-app#generating-api-definitions-and-translations?

**Comment by stefanosisto** [comment]
@fabriziofff no, avevo eseguito solo `npm run generate:locales` come da commento.
Lanciando il `yarn generate:all`, il problema è risolto.

Non avevo capito che era obbligatorio! Grazie mille :)
