### ISSUE TITLE
Documenti in app

### ISSUE THREAD

**Issue by PeraDev7** [pagopa/io-app#3498]
**Qual è il problema che vorresti risolvere?**
La possibilità di avere i documenti in app

**Quale soluzione proponi?**
Ho visto sulla roadmap dell'app IO che si stava valutando questa opzione. Visto che da oggi il sito dell'anagrafe permette di scaricarli, sarebbe utile integrare il sistema in app.

**Comment by pietro909** [comment]
@PeraDev7 puo' essere che questo suggerimento sia parte di https://github.com/pagopa/io-app/issues/3173 ? O intendi altri documenti?

**Comment by alessiomatricardi** [comment]
> @PeraDev7 puo' essere che questo suggerimento sia parte di https://github.com/pagopa/io-app/issues/3173 ? O intendi altri documenti?

Penso che si riferisca alla roadmap in questa pagina https://io.italia.it/roadmap/#nextsteps
Dove viene esplicitato che entro 2021 sarebbe stata disponibile una sezione documenti (ricevute, documenti di identità, possibili certificati).

Off topic ma sempre qui viene definito il rilascio di una web-app per la consultazione da pc: ci sono progressi oppure è stata una previsione un po' troppo ottimostica?

Buon lavoro

**Comment by alessionossa** [comment]
Nonostante il 2021 si sia concluso, non sembrano ancora esserci aggiornamenti a riguardo

**Comment by bhack** [comment]
Gran parte della roadmap credo che debba essere formalizzata in base a quanto messo nero su bianco nel PNNR (aka Recovery Plan)

https://italiadomani.gov.it/it/Interventi/investimenti/servizi-digitali-e-cittadinanza-digitale.html

> favorire l'adozione dell'applicazione digitale per i pagamenti tra cittadini e pubbliche amministrazioni (PagoPa) e l'adozione dell'app “IO” quale principale touchpoint digitale tra cittadini e amministrazione per un'ampia gamma di servizi, comprese le notifiche, con la logica dello “sportello unico” attraverso l'investimento dedicato "Adozione scale up dei servizi della piattaforma PagoPA e dell'app “IO”"
