### ISSUE TITLE
Flusso per login CiE

### ISSUE THREAD

**Issue by stefanosisto** [pagopa/io-app#3512]
Ciao a tutti.
Secondo la documentazione CiE (disponibile all'URL https://docs.italia.it/italia/cie/cie-manuale-tecnico-docs/it/master/cieIDSDK.html) dovrebbero esistere due possibili flussi di autenticazione (con reindirizzamento o flusso interno).
Per iOS, secondo questa documentazione, non esiste il flusso interno ma solo con reindirizzamento.

Vedendo l'app IO, però, mi sembra che il flusso utilizzato sia quello interno sia per iOS che per Android.

Mi chiedo quindi se la libreria react-native-cie attualmente utilizzata permetta solo il flusso interno.

**Comment by pietro909** [comment]
Ciao @stefanosisto e benvenuto :-) 
Se sei d'accordo (e se il resto del team e' d'accordo 🙇 ) ti proporrei di spostare la discussione su https://github.com/pagopa/io-cie-sdk/ visto che la domanda in questa issue e':

> Mi chiedo quindi se la libreria react-native-cie attualmente utilizzata permetta solo il flusso interno.

**Comment by stefanosisto** [comment]
Sposto la domanda nel relativo Repo!

**Comment by stefanosisto** [comment]
Ciao. Scusa se riapro di qui, ma non ho ottenuto risposta nell'altro Repo..
