### ISSUE TITLE
Molti green pass, difficile distinguere gli attivi dagli scaduti

### ISSUE THREAD

**Issue by nu111** [pagopa/io-app#3543]
I green pass hanno scadenze diverse, se una persona ha tanti green pass diversi, per capire quali sono attivi e quali sono scaduti bisogna aprirli uno per uno.
Uno scenario in cui questo può accadere è a seguito di un ricovero ospedaliero, dove ogni 2 giorni si è soggetti a tampone molecolare.

Potrebbe risolvere se nella videata ad elenco i green pass scaduti avessero una label "scaduto".

In alternativa potrebbe essere utile poterli filtrare o nascondere sempre e comunque i green pass scaduto (ma non so se questo collide con qualche esigenza particolare di alcuni utenti).

**Comment by davcec** [comment]
v. https://github.com/pagopa/io-app/issues/3413#issuecomment-981520477

**Comment by nu111** [comment]
Ciao, a mio parere non risolve la "scomodità" che segnalavo, perché se hai molti green pass, molti dei quali scaduti, sei costretto comunque ad aprirli uno alla volta tutti per capire quale è ancora valido.
Per questo penso sia importante operare direttamente sulla videata di elenco, non tanto sulla scheda di dettaglio del singolo green pass.

**Comment by davcec** [comment]
Sì sì, intendevo riportare che quell'informazione ora c'è. Concordo che esporla direttamente sulla lista messaggi sarebbe molto comodo.

**Comment by nu111** [comment]
Il problema è ancora presente.
