### ISSUE TITLE
Possibile problema di data privacy con invio di notifiche da backend anche quando utente non loggato?

### ISSUE THREAD

**Issue by fpietrosanti** [pagopa/io-app#3547]
Seguo segnalazione vista da Twitter come commenti a Colao che riporto, su possibile problema di data privacy con invio di notifiche da backend anche quando utente non loggato?

<img width="270" alt="Screenshot 2021-12-04 at 10 03 32" src="https://user-images.githubusercontent.com/770363/144703963-d929fb5f-aabc-44a2-9578-b75b7992b7c9.png">

**Comment by fabriziofff** [comment]
Ciao, quando non si è loggati si riceve una notifica generica che segnala esclusivamente che c'è un messaggio in app. Solo quando poi si effettua di nuovo il login saranno mostrati l'ente mittente e relativo contenuto del messaggio.
