### ISSUE TITLE
Avviso scadenza login

### ISSUE THREAD

**Issue by mbm901** [pagopa/io-app#3662]
**Qual è il problema che vorresti risolvere?**
Ricevere una notifica quando sta per scadere il login altrimenti non si ricevono le notifiche dai vari servizi pubblici (es scadenza c.i., nuovo documento in cassetta postale inps...)

**Quale soluzione proponi?**
Ricevere notifica 48 ore prima della scadenza del login in modo da "rinnovarlo" prima del logout automatico.

**Comment by thisisjp** [comment]
Ciao @mbm901!
Quando la tua sessione scade (perché sono trascorsi 30 giorni dal tuo login tramite SPID o CIE) continui comunque a ricevere notifiche push: facendo tap sulla notifica ti verrà poi chiesto di effettuare nuovamente login.

Quando invece effettui un logout (dalla sezione Profilo) o accedi ad IO con un altro dispositivo, non riceverai più notifiche relative ai messaggi.

Se lo scenario descritto qui sopra non corrisponde alla tua esperienza, chiedi pure assistenza in app 💪
