### ISSUE TITLE
Impossibile tornare indietro quando mostrato il Pagobancomat

### ISSUE THREAD

**Issue by djechelon** [pagopa/io-app#3670]
**Descrivi il problema**
Tento di aggiungere una carta Pagobancomat ma tuttavia NON voglio aggiungerla davvero.
Fatta la ricerca mi compare la carta. Vorrei tornare indietro ma non mi è consentito. Non compare un tasto indietro, l'indietro di sistema non funziona

**To Reproduce**
1. Andare nella sezione portafoglio
2. Aggiungere metodo di pagamento
3. Selezionare Pagobancomat
4. Mostrare la lista delle Pagobancomat associate (nel mio caso una sola)
5. Tentare di andare indietro

**Expected behavior**
IO dovrebbe permettermi di annullare tutto e tornare indietro un passo alla volta

**Screenshots**
Se volete ne allego uno ma è chiarissima la descrizione

**Versione dell'app**
2.0.0.0

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - OS: AOSP 12

**Additional context**
In Android 12 è consentito fare "indietro" di sistema facendo un legger swipe sul bordo dello schermo

**Comment by fabriziofff** [comment]
Ciao @djechelon, grazie per la segnalazione! Nel caso specifico non si tratta di un bug ma il comportamento da te descritto è intenzionale. Il flusso di aggiunta PagoBANCOMAT, attualmente, prevede l'iterazione su tutti i BANCOMAT del cittadino, in modo che possa effettuare la scelta per ognuno di essi. Ad ogni passo è comunque possibile premere su "Salta" ed evitare così l'aggiunta al Portafoglio.
