### ISSUE TITLE
Compatibilità del green pass con Apple Wallet

### ISSUE THREAD

**Issue by amdemarco** [pagopa/io-app#3671]
**Qual è il problema che vorresti risolvere?**
Utilizzare il codice a barre del green pass direttamente in Apple Wallet su dispositivi iOS. Questa funzionalità renderebbe più semplice la ricerca della certificazione di avvenuta vaccinazione e farebbe risparmiare tempo durante i controlli (evitando potenziali assembramenti). Per quanto sia possibile salvare il codice QR nelle immagini oppure consultarlo direttamente utilizzando le app IO e Immuni, i metodi attuali richiedono del tempo (es. per effettuare l'accesso a IO oppure navigare attraverso i menù di Immuni) mentre la fruizione tramite Apple Wallet sarebbe quasi immediata.

**Quale soluzione proponi?**
Rendere compatibile il sistema attuale con Apple Wallet come documentato in questa pagina: https://support.apple.com/it-it/HT212752

**Hai già considerato soluzioni alternative?**
Non applicabile.

**Comment by PeraDev7** [comment]
O.T.
Si può fare tramite un servizio esterno su iOS da qui : 
https://covidpass.marvinsextro.de/it-IT

**Comment by alessionossa** [comment]
Come già menzionato in https://github.com/pagopa/io-app/issues/3168#issuecomment-1025148226, è ora tecnicamente possibile salvare il DGC in Apple Wallet nella nuova beta di iOS 15.4
