### ISSUE TITLE
Nome file certificato verde salvato in galleria

### ISSUE THREAD

**Issue by marcoscale98** [pagopa/io-app#3707]
**Descrivi il problema**
Quando viene salvato in galleria il Green Pass, il nome del file che gli viene attribuito non chiarisce di cosa si tratta. Non so se sia voluta come cosa o sia colpa della libreria usata per allocare un URI per l'immagine.
Sta di fatto che il nome del file che viene fuori è una cosa simile a questa:
![telegram-cloud-photo-size-4-6028312708669093427-y](https://user-images.githubusercontent.com/43850400/151679204-c7198e22-a609-4e96-a44a-552752641a67.jpg)
Io lo metto come collegamento sulla home screen e vedersi la scritta "ReactNative..." non è proprio bellissimo.

**To Reproduce**
1. Selezionare una Certificazione Verde COVID-19
2. Premere "Salva"
3. Premere "Salva come immagine nella galleria"
4. Andare nell'archivio dei file, cercare il file e notare il nome del file.

**Expected behavior**
Un nome come "Certificazione verde COVID-19 <data>" sarebbe visivamente più chiaro e carino.

**Versione dell'app**
2.1.0.1

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S9
 - OS: Android 10

**Comment by pietro909** [comment]
https://pagopa.atlassian.net/browse/IA-651
