### ISSUE TITLE
Scaricare l'app iOS fuori Italia/Europa

### ISSUE THREAD

**Issue by voztovoice** [pagopa/io-app#3788]
Non so in quanti paesi è possibile scaricare l'applicazione, però nell'apple store colombiano no e conosco molte persone, tra le quali il sottoscritto, che ne avrebbero bisogno.
Grazie

**Comment by fabriziofff** [comment]
Ciao @voztovoice, è possibile scaricare l'app da tutti i paesi supportati dall'App Store, non vi è alcun limite o blocco. In particolare, https://apps.apple.com/co/app/io/id1501681835 questo dovrebbe essere il link per lo store colombiano.
