### ISSUE TITLE
[IA-683] When a PagoPA bulletin's QR Code is scanned, the green check mark remain visible 

### ISSUE THREAD

**Issue by giovannifil-64** [pagopa/io-app#3793]
**Descrivi il problema**
When the QR Code of a PagoPA bulletin is scanned and the user goes back to the scan page, a green check mark is still visible

**To Reproduce**
1. Go to 'Wallet'
2. Click on 'Pay notice'
3. Scan a QR Code and wait the loading of the payment information
4. If you go back to the scanning screen, the green check mark is still visible 

**Expected behavior**
The check mark should not be visible

**Screenshots**
![96150bab-afab-4893-a778-2132ea7eff86](https://user-images.githubusercontent.com/39963191/156046747-67bd785e-e559-4d0b-8091-d2d29ccd6f87.jpg)

**Versione dell'app**
Version 2.3.0.2

**Smartphone:**
 - iPhone 6S
 - iOS 15.3

**Comment by fabriziofff** [comment]
Created https://pagopa.atlassian.net/browse/IA-683 (for internal tracking)
