### ISSUE TITLE
Servizi nazionali duplicati

### ISSUE THREAD

**Issue by RomanKorpanyuk** [pagopa/io-app#3890]
Buonasera.
Vorrei indicarvi che nella lista dei servizi nazionali legati a INPS ci sono dei servizi duplicati. 
In allegato vi aggiungo l'immagine. Grazie, cordiali saluti, Roman Korpanyuk
![4C5EB69A-4ABF-4C41-93BF-28592E7F0BE8](https://user-images.githubusercontent.com/24389905/162063293-dd892fe4-1be7-4ea6-a35c-1500de6c949d.jpeg)

**Comment by Marlowess** [comment]
Addirittura adesso i servizi INPS (quasi tutti) sono triplicati.

**Comment by fabriziofff** [comment]
Grazie per la segnalazione, il problema è stato risolto in https://github.com/pagopa/io-app/pull/3980
