### ISSUE TITLE
The back button on the PayPal screen brings up a search for banks

### ISSUE THREAD

**Issue by giovannifil-64** [pagopa/io-app#3987]
**Descrivi il problema**
After a certain amount of navigation within adding a PagoBANCOMAT card, the back button on the PayPal screen brings up a search for banks

**To Reproduce**
1. Go to Wallet
2. Click on Add Payment Method
3. Click on PagoBANCOMAT card
4. After pressing on the continue button, if there are no cards detected, if I press on "Select Bank" it takes me to the search for a specific bank for possible addition
5. Now, going back to the Add Payment Method page, if I click on PayPal and then try to go back to the previous page, I am shown the bank search page

**Expected behavior**
It should go back to the Add Payment Method page

**Screenshots**

https://user-images.githubusercontent.com/39963191/170972818-9e796798-585a-4f40-990d-cf47409d7293.MP4

**Versione dell'app**
Version 2.10.0.1

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 15.4.1

**Additional context**
I can imagine it's quite hard to understand the problem from the description, for any clarification I'm available

**Comment by fabriziofff** [comment]
Thanks for the report, that was tricky 😄 
Tracked with https://pagopa.atlassian.net/browse/IA-871

**Comment by giovannifil-64** [comment]
I know it's something hard to find, but sometimes the majority of bugs are found while randomly "playing" with the app😂
