### ISSUE TITLE
Glitch shows two pages when a message is opened

### ISSUE THREAD

**Issue by giovannifil-64** [pagopa/io-app#3997]
**Descrivi il problema**
In the message section, when a message is first opened, the content loading screen and then the message itself are shown, and it is shown as if they were two separate screens [1].
On the other hand, if the message has already been opened, the loading screen is always shown, but below the message [2]. 

**To Reproduce**
1. Go to the 'Messages' page
2. Open a message and you should be able to see the glitch

**Expected behavior**
The message loading should be handle in one page

**Screenshots**
[1]
![IMG_1906](https://user-images.githubusercontent.com/39963191/172044027-deb31225-05fe-49bb-a124-a3ce4624e9e7.PNG)

[2]
https://user-images.githubusercontent.com/39963191/172043946-ce0b9471-8674-418a-bbe3-46c5576fe943.mp4

**App Version**
Version 2.10.0.1

**Device**
Device: iPhone 11 Pro
OS: iOS 15.4.1

**Comment by fabriziofff** [comment]
Hi @giovannifil-64 ,
this is known behavior, due to the current navigation implementation.
We are currently updating the navigation flows one by one, we will probably review this behavior after finishing the update.

Thanks anyway for the report!
