### ISSUE TITLE
Impossible completare transazione se necessario cambiare app in esecuzione 

### ISSUE THREAD

**Issue by alessandropellegrini** [pagopa/io-app#4027]
**Descrivi il problema**

Se sto utilizzando IO e devo passare ad un'altra app per confermare una transazione 3DS, spesso dopo la conferma IO si "dimentica" del punto in cui si era arrivati e riparte dalla schermata iniziale. In questo modo è impossibile completare i pagamenti.

Il comportamento dipende sia dall'app della banca che dal modo in cui l'utente accede alla conferma in app. Alcune app, dopo la conferma, si chiudono e tornano alla home di Android. Altre tornano "indietro" e, a volte, IO mantiene lo stato correttamente.

**To Reproduce**
1. Tenta un pagamento con carta di credito.
2. All'arrivo della notifica chiudi IO tornando alla home
3. Apri l'app della banca
4. Conferma la transazione
5. Riapri IO
6. Viene effettuato nuovamente il processo di login e si riparte dalla home, non potendo concludere la transazione 

**Expected behavior**
Allapertura di IO, se lasciata in background, l'app ricorda il suo stato e riparte dalla vista precedente senza effettuare le operazioni di login.

**Screenshots**
N/A

**Versione dell'app**
2.11.0.5

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi A1
 - OS: Android 9

**Additional context**
N/A

**Comment by thisisjp** [comment]
Ciao @alessandropellegrini, il problema da te descritto dipende dalla RAM del tuo dispositivo.
Prova a chiudere le altre app aperte, oppure riavvia periodicamente il tuo dispositivo così da liberare la RAM inutilizzata.

Prima di riprovare il pagamento, verifica se questo è andato comunque a buon fine: vai in "Portafoglio" e scorri in basso per vedere le tue operazioni.

**Comment by alessandropellegrini** [comment]
:man_facepalming: 
Status: `confirmed` --> `wontfix`
