### ISSUE TITLE
Critical error prima dell'autenticazione

### ISSUE THREAD

**Issue by federicomazzalovo** [pagopa/io-app#4030]
Dopo aver aperto l'app, prima di raggiungere la maschera di autenticazione l'applicazione va in crash con il seguente errore
![Screenshot_20220705-191317_IO](https://user-images.githubusercontent.com/13098024/177381539-1cc5a7a7-a699-4610-b9fb-82510b75fb9b.png)

**Comment by thisisjp** [comment]
Fixed in #4082
