### ISSUE TITLE
L'app si arresta in modo anomalo restituendo un errore critico - android 12

### ISSUE THREAD

**Issue by DarkMinee** [pagopa/io-app#4058]
**Descrivi il problema**
Quando apro l'app, subito dopo la schermata blu iniziale, questa si chiude e viene mostrato un messaggio di errore critico che non permette di proseguire. La versione dell'app è la 2.12.0.2, l'ultima disponibile. Sto utilizzando android 12.

**Screenshots**
![Screenshot_20220716-164723_IO](https://user-images.githubusercontent.com/43444257/179359906-01e5f410-cb85-4e30-96a1-55a6cde9e6b3.png)
![Screenshot_20220716-164752_IO](https://user-images.githubusercontent.com/43444257/179359926-0b729ce2-6477-4dd6-9065-c62481e094d6.png)

**Comment by francescopersico** [comment]
Thanks for reporting the issue. We are already addressing it with #4060.

**Comment by thisisjp** [comment]
Fixed in #4082
