### ISSUE TITLE
Crital Error Occured ! 

### ISSUE THREAD

**Issue by petruzzellialessandro** [pagopa/io-app#4059]
**Descrivi il problema**
Non mi è possibile utilizzare l'app poiché questa crash riportando un errore critico nel momento dell'avvio. In particolare durante l'animazione dei caricamento dei 4 step iniziale prima dell'avvio dell'app appare una schermata che riporta *Crital Error Occured ! *

**To Reproduce**
Per riprodurre basta aprire l'app, nel mio caso. 

**Expected behavior**
L'app dovrebbe aprirsi e dovrebbe permettermi di fare l'accesso

**Screenshots**
![photo_2022-07-17_17-15-13](https://user-images.githubusercontent.com/47218421/179404848-cdd16d9f-4921-42e4-8231-44f332ea17d0.jpg)
![photo_2022-07-17_17-15-17](https://user-images.githubusercontent.com/47218421/179404852-8bbe0368-f2a0-4ec8-8e3e-abce2bdf5198.jpg)

**Versione dell'app**
La versione dell'app è 2.12.0.2

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 9
 - OS: Android 12

**Comment by francescopersico** [comment]
Thanks for reporting the issue. We are already addressing it with #4060.
