### ISSUE TITLE
PDF della ricevuta di pagamento 

### ISSUE THREAD

**Issue by User13052001** [pagopa/io-app#4118]
**Qual è il problema che vorresti risolvere?**
Inserire una funzione che permetta di esportare la ricevuta di pagamento di qualsiasi operazione in un documento PDF.

**Quale soluzione proponi?**
Inserire una funzione ESPORTA.

**Hai già considerato soluzioni alternative?**
No.

**Altre informazioni**

**Comment by Bavuett** [comment]
Mi piacerebbe lavorare su questa issue, magari avendo le dovute indicazioni su come ottenere (o eventualmente generare) il PDF della transazione.

**Comment by User13052001** [comment]
Grazie Bavuett della risposta.
Non sono esperto di questa piattaforma ma mi piacerebbe risolvere questa issue!
Come possiamo fare?

**Comment by User13052001** [comment]
Grazie @Bavuett della risposta.
Non sono esperto di questa piattaforma ma mi piacerebbe risolvere questa issue!
Come possiamo fare?

**Comment by Bavuett** [comment]
Hey @User13052001. È quello che cercavo di chiedere in quel messaggio. Proprio come te sono un utente dell'app (non lavoro per PagoPA, nonostante sia mia intenzione farlo in futuro - sono ancora uno studente delle superiori) ma mi piacerebbe usare le mie competenze in ambito di programmazione per aiutare lo sviluppo visto che la pubblicazione del codice sorgente da parte loro mi consente di farlo. 

Dovremmo aspettare che i proprietari del progetto inizino a pensare all'implementazione specifica della funzionalità. La tua issue è aperta da Settembre 2022 e magari è anche quasi finita, come potrebbero anche aver avuto altro a cui pensare. Io mi sono proposto nel caso i maintainer fossero interessati a coinvolgere volontari per facilitare lo sviluppo perché riconosco i vantaggi che l'esportazione dei PDF dall'app darebbe a utenti come noi, ma non me la sento di creare un'implementazione senza direttive dai legittimi proprietari, che potrebbero scegliere diverse strategie per esigenze interne al progetto.

Saluti, e buon weekend. :)
