### ISSUE TITLE
Schermata inserimento CVV: visualizzare le ultime cifre della carta

### ISSUE THREAD

**Issue by loremari** [pagopa/io-app#4134]
Pagando con carta di credito, compare una schermata per l'inserimento del CVV.

Questa schermata presenta un problema di usabilità in quanto non riporta nessun riferimento al numero di carta per il quale viene chiesto il CVV: chi come me ha registrato più carte deve ricordarsi quale di queste è stata selezionata, normalmente di default dal sistema, nella schermata precedente.

Il problema è aggravato dal fatto che non è possibile tornare alla schermata precedente per leggere il numero. E' solo possibile annullare il pagamento, il che comporta minimo 10 minuti di attesa prima di riprovare. Anche l'inserimento del CCV corretto, ma della carta errata comporta la necessità di attendere prima di riprovare. L'esperienza è parecchio frustrante.

Suggerisco come minimo di includere nella schermata di richiesta CVV il numero di carta, opportunamente asteriscato per mostrare solo le ultime cifre.

**Comment by loremari** [comment]
NB: nella stessa schermata lo stesso dato viene chiamato CVV (nella label) e poi CVC (all'interno del campo). Potete uniformare la nomenclatura?

**Comment by thisisjp** [comment]
Grazie @loremari! Abbiamo girato il tuo feedback al team di pagoPA, che eroga le webview coinvolte nel processo di pagamento. 

Ne approfitto per ricordarti che il metodo proposto in automatico durante il pagamento è quello che hai scelto come preferito nel tuo Portafoglio. Puoi modificare tale preferenza da Portafoglio > {metodo} > Usa come preferito 😉

**Comment by thisisjp** [comment]
@loremari la pagina ora mostra un riferimento alla carta e delle istruzioni più chiare su dove trovare il codice di sicurezza ;)

Grazie per il tuo suggerimento!

<img src="https://user-images.githubusercontent.com/2277990/215051803-682b0f6f-274a-45fa-a9af-a0972ff9f2d8.PNG" width="375">
