### ISSUE TITLE
Ricezione di Verbali di Violazioni del Codice su App IO 

### ISSUE THREAD

**Issue by carriero68** [pagopa/io-app#4154]
Sono domiciliato per motivi di lavoro in Comune diverso da quello di residenza.

**PROBLEMA**
I verbali di violazioni del Codice della Strada (e relativi avvisi di pagamento) arrivano esclusivamente per posta cartacea al mio indirizzo di residenza; tipicamente, non essendo nessuno presente all'indirizzo, gli addetti delle Poste depositano avvisi di giacenza che miei incaricati non sempre riescono a ritirare tempestivamente. 
Ne conseguono tempi di ricezione e di pagamento dilatati nonchè aggravi di  costo. 

**Quale soluzione proponi?**
Se il Comune aderisce alla App IO, identificato il numero di targa del veicolo in violazione dovrebbe essere in grado di collegare la targa al Codice Fiscale del proprietario, quindi emettere il verbale a quel Codice Fiscale via App IO. 
Presumo che la soluzione sia praticabile, visto che il Comune dove sono domiciliato mi ha recentemente notificato una contravvenzione via IO (a differenza di altri - pure aderenti alla APP - che invece effettuano ancora le notifiche via posta cartacea). 

**Hai già considerato soluzioni alternative?**
Poste Italiane offre un servizio di tramitazione della corrispondenza, che però NON COMPRENDE atti giudiziari (ed è comunque per nulla affidabile).

**Comment by thisisjp** [comment]
Ciao @carriero68!
In questi giorni dovresti aver ricevuto in app un messaggio che racconta le ultime novità di IO: il caso da te descritto rientra proprio in una delle funzionalità che stiamo sperimentando con alcuni enti 😉
