### ISSUE TITLE
Trasformare IO in applicazione multipiattaforma (PC Windows / linux)

### ISSUE THREAD

**Issue by hixcube** [pagopa/io-app#4176]
The power, utility and appreciation of an application in a way pervaded by smartphones and some operating systems distributed in millions of PCs around the world is the possibility of the app itself being able to be used with the same account between Android and iOS systems as is currently the case. The circle would be completed if the IO app could work the same way on MS Windows systems, and even linux if you want to exaggerate.

I have only this idea to propose, I don't have the solution because I'm not a programmer, but a user who would like to be able to use and manage IO on his Windows PC.

Thank you
---

**EDIT:
Anche se il significato è chiaro, ripeto e sintetizzo in italiano: 
¿ Perché non rendere compatibile IO con Windows, e Linux col fine ovvio di renderla un'app veramente per tutti ?**

**Comment by hixcube** [comment]
Up please

**Comment by scollovati** [comment]
Questa issue é importante anche per poter fornire un supporto a tutti i dispositivi mobili che non utilizzano gli app store Google / Apple come evidenziato qui https://github.com/pagopa/io-app/issues/1718

**Comment by hixcube** [comment]
Anche in vista delle annunciate dichiarazioni, a maggior ragione l'utilizzo di questa app deve essere estesa a tutti i principali sistemi operativi. Non solo android.

Curioso che nessuno del progetto PagoPA qui su GitHub, si sia degnato di rispondere o accodare un suo parere

**Comment by Fale** [comment]
Il problema non è ancora stato risolto!

**Comment by hixcube** [comment]
The power, utility and appreciation of an application in a way pervaded by smartphones and some operating systems distributed in millions of PCs around the world is the possibility of the app itself being able to be used with the same account between Android and iOS systems as is currently the case. The circle would be completed if the IO app could work the same way on MS Windows systems, and even linux if you want to exaggerate.

I have only this idea to propose, I don't have the solution because I'm not a programmer, but a user who would like to be able to use and manage IO on his Windows PC.
..... 
Anche se il significato è chiaro, ripeto e sintetizzo inpper gli amici italiani:
¿ Perché non rendere compatibile IO con Windows, e Linux col fine ovvio di renderla un'app veramente per tutti ?

**Comment by Fale** [comment]
Il problema non è ancora stato risolto!

**Comment by d1nuc0m** [comment]
> Il problema non è ancora stato risolto!

Inutile, tanto la maggior parte delle issues viene chiusa "d'ufficio" per mancanza di attività
