### ISSUE TITLE
Nel messaggio se mantenere o meno i sistemi di pagamento compare un messaggio di errore

### ISSUE THREAD

**Issue by cirospat** [pagopa/io-app#4194]
**Descrivi il problema**
Il 23.11.2022 mi arriva una notifica su App IO e accedo. 
Si tratta del messaggio se voglio mantenere o meno i sistemi di pagamento attualmente registrati sull'app.
Vado su seleziona.
Mi compare messaggio: workunit_generic_failure.

**To Reproduce**

**Expected behavior**

**Screenshots**

![Screenshot_2022-11-23-15-34-45-849_com.google.android.apps.photos.jpg](https://user-images.githubusercontent.com/3757525/203573439-5c1efa6e-df38-4242-89dc-a50651eba01a.jpg)

**Versione dell'app**
Copia i due numeri che appaiono in alto a destra nello schermo dell'app.
0.6

**Smartphone (please complete the following information):**
 - Device: [Xiaomi mi10t]
 - OS: [android 12]

**Additional context**

**Comment by CrisTofani** [comment]
Ciao @cirospat la funzionalità è supportata a partire dalla versione `2.19.0.4` mentre nel tuo caso vedo che stai usando la `2.14.0.6`
