### ISSUE TITLE
Suggerimento password di iOS non funzionante

### ISSUE THREAD

**Issue by giovariot** [pagopa/io-app#4200]
**Descrivi il problema**
Sia nel form di login con SPID che nel login, ad esempio a PayPal nell'aggiunta dei metodi di pagamento anziché comparire il suggerimento della password per il sito di login (nel mio caso, ad esempio, con InfoCert) appare soltanto il pulsante per accedere alle password salvate sul telefono sul quale bisogna poi cercare l'indirizzo web del sito.

Ulteriore problema è il fatto che se, ad esempio, si utilizza l'autenticazione a 2 fattori su PayPal il codice variabile di verifica che sarebbe normalmente accessibile tramite il supporto 2FA di iOS in cima alla tastiera è inaccessibile e bisogna andare a copiarlo manualmente dalle impostazioni di iOS.

**To Reproduce**
Facendo il login tramite SPID alla prima apertura anziché trovare in cima alla tastiera iOS il nome dell'account vi sarà solo "🔑 Password".

**Expected behavior**
Dovrebbe comparire il proprio nome utente su cui premere vedendo automaticamente compilato il form di login.

**Screenshots**
![image](https://user-images.githubusercontent.com/12408904/203851537-ac9643d5-7cc1-48dd-878a-324023e75e43.png)

**Versione dell'app**
2.19.0.4

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro (ma anche su iPhone 6S)
 - OS: iOS 16.1.1

**Comment by giovariot** [comment]
https://github.com/react-native-webview/react-native-webview/issues/2117

Un problema simile è affrontato in un issue sul repo di react-native-webview che credo di aver capito sia la webview che utilizza IO app, consigliano alcune soluzioni al problema

**Comment by abz-denys-z** [comment]
We need autofill, hopefully the developers will see all the issues on this topic
