### ISSUE TITLE
Notifiche scadenza bollo auto non funzionano

### ISSUE THREAD

**Issue by giovariot** [pagopa/io-app#4201]
**Descrivi il problema**
Nonostante io sia iscritto al servizio ACI Bollo non ricevo alcuna notifica allo scadere del bollo.

**To Reproduce**
1. Iscriversi al servizio Bollo Auto di ACI
2. Attendere la scadenza del bollo

**Expected behavior**
Penso dovrebbe arrivare una notifica prima o al momento della scadenza.

**Versione dell'app**
2.19.0.4

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro 
 - OS: iOS 16.1.1

**Additional context**
Sono un cittadino ligure per cui il servizio ACI credo si interfaccia con il sistema ligure (dal momento che finisco sempre per pagarlo sul sito della regione).

**Comment by thisisjp** [comment]
Ciao @giovariot, per problemi con i servizi di ACI puoi contattare direttamente l'ente. Verifica su IO di avere attivato la configurazione rapida o le preferenze di comunicazione sul servizio "Bollo Auto".
