### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by giovariot** [pagopa/io-app#4202]
**Qual è il problema che vorresti risolvere?**
L'app è molto ben studiata dal punto di vista grafico ma è molto bianca, e ad oggi tutti i sistemi operativi mobili hanno una "modalità scura" per risparmiare batteria.

**Quale soluzione proponi?**
Propongo l'aggiunta di una modalità scura, magari con la possibilità di correlarne l'attivazione con l'impostazione in quel momento attiva sul sistema.

**Comment by dmnplb** [comment]
[Tramite l'etichetta `Dark Mode` potete seguirne gli avanzamenti](https://github.com/pagopa/io-app/pulls?q=is%3Apr+label%3A%22Dark+mode+%F0%9F%8C%9D%22
)
