### ISSUE TITLE
Generazione buoni del Bonus Cultura direttamente dall'app

### ISSUE THREAD

**Issue by Church-17** [pagopa/io-app#4209]
La generazione dei buoni del Bonus Cultura richiede l'accesso al sito 18app.italia.it, fare l'accesso tramite SPID o CIE, e destreggiarsi tra i menù, solo per iniziare a creare il buono. Tutti questi passaggi possono essere piuttosto lenti e macchinosi, soprattutto dovendo passare per forza da un browser, e soprattutto se li si può fare solo da un dispositivo mobile.

Sarebbe utile e più veloce se si potessero generare i buoni direttamente da una sezione dell'app IO.

**Comment by SimoneRaspagni** [comment]
Idea molto utile che si può estendere alla carte dei docenti
