### ISSUE TITLE
Errore lettura nuovo tipo (chip?) CIE probabilmente prodotte a partire dal 01/01/2023

### ISSUE THREAD

**Issue by undertherainITA** [pagopa/io-app#4339]
**Errore lettura nuovo tipo (chip?) CIE**
La lettura delle nuove carte CIE, probabilmente prodotte a partire dal 01/01/2023, non funziona.
Tali nuove carte sono riconoscibili da nuovo logo bandiera EU in alto a sinistra e da nuovo logo IT in basso a destra, entrambi non presenti su versione vecchia.

**Per riprodurre l'errore**
Step per riprodurre l'errore:
1. Aprire l'app IO
2. Cliccare su "Entra con CIE"
3. Inserire il PIN della CIE
4. Cliccare su "Continua"
5. Appoggiare la CIE
6. La lettura della CIE va in errore senza dare alcun messaggio, semplicemente dopo pochi istanti la circle progress bar da colore blu diventa colore marrone (o simile...). Anche riprovando con differenti modelli di smartphone e di S.O. Android, più volte, si ottiene sempre lo stesso comportamento. Utilizzando stesso smartphone/S.O./versione Android con vecchia CIE la lettura funziona perfettamente. Utilizzando la nuova CIE con app CieID la lettura avviene correttamente. Evidentemente va aggiornata la parte software (libreria?) dell'app IO che si occupa della comunicazione con il chip "NFC" (nuovo chip su nuova CIE?). Si segnala che anche app iPatente presenta medesimo problema.

**Comportamento atteso**
La lettura delle nuove CIE da parte dell'app IO e iPatente dovrebbe funzionare così come funziona, correttamente, sull'app CieID (nessun problema con quest'ultima e corretto accesso tramite browser a siti istituzionali quali Sanità, INPS, AdE, etc.)

**Screenshots**
![photo_2023-02-01_10-37-25](https://user-images.githubusercontent.com/15998009/216006970-daaf59fd-1faf-4ed6-af13-dd3185a86a31.jpg)

**Versione dell'app**
2.24.0.2

**Smartphone:**
 - Device: Google Pixel 3a/4a/6a - Xiaomi 11 Lite NE
 - OS: Android 12/13

**Commenti aggiuntivi**
Si segnala che anche app iPatente presenta medesimo problema.

**Comment by undertherainITA** [comment]
> Confermo, anch'io con una nuova carta emessa nella prima metà di gennaio di quest'anno riscontro le stesse problematiche. La registrazione della carta è avvenuta senza problemi con l'app CieID. Spero che questo problema venga risolto al più presto dato che l'app IO è ormai sulla buona strada per diventare il punto unico di comunicazione tra PA e cittadini. Segnalo anche un problema simile con l'applicazione CieSign. Mi chiedo inoltre come sia possibile questa discrepanza tra applicazioni, pensavo che esistesse un SDK unico per implementare l'accesso con CIE.
> 
> Cordiali saluti

Beh, ti posso dire, da developer, che ci sono sempre vari modi per implementare qualcosa e di utilizzare un'SDK, per cui... va bene così, aspetto fiducioso.
Inizialmente pensavo che fosse difettosa la carta, poi stupidamente non avevo verificato che con CieID funziona perfettamente.
Devo chiederne un'altra ma quasi quasi aspetto... si sa mai... ;)

**Comment by undertherainITA** [comment]
> 

Stai scrivendo ad uno che usava la CNS con lettore China quando le persone ancora non sapevano quasi cosa fosse Feisbuc... ;)
Comunque siamo su GitHub, chiudiamo l'O.T. (mi scuso) ed attendiamo che i developer prendano in mano il ticket.
Grazie ancora.

**Comment by francescopersico** [comment]
Ciao @undertherainITA ti confermo la presa in carico della segnalazione. Il team tecnico sta lavorando per rilasciare quanto prima una versione che risolve quanto segnalato in questa issue.

**Comment by undertherainITA** [comment]
Grazie mille @francescopersico, ho chiesto perchè non vedendo la presa in carico non avevo capito, ora posso dire a mamma e papà di stare sereni... ;)
Grazie ancora.

**Comment by francescopersico** [comment]
Fixed by #4380

**Comment by francescopersico** [comment]
Fixed in v2.26.0.3.

**Comment by francescopersico** [comment]
@undertherainITA @robertbridda Abbiamo rilasciato una nuova versione dell'app che dai nostri test risolve il problema. Ci sarebbe molto utile avere un riscontro da parte vostra.

**Comment by undertherainITA** [comment]
> @undertherainITA @robertbridda Abbiamo rilasciato una nuova versione dell'app che dai nostri test risolve il problema. Ci sarebbe molto utile avere un riscontro da parte vostra.
Te lo stavo proprio per scrivere, amico mio, già testata e funziona perfettamente con nuova CIE di mia mamma prodotta dopo il 01/01/2023 per la quale avevo aperto il ticket... ;)
Ti chiedo un favore, anche se capisco che è O.T.: il medesimo problema è presente nell'app iPatente che però vedo scritta da altra software house.
Tu hai modo di avvisare i developer dato che non ho trovato loro GitHub?
Al di la di scrivere commento su Google Play Store non saprei come fare, so che mandare e-mail all'indirizzo riportato nel Play Store, appunto, manco la leggerebbero... ;)
Detto questo, davvero complimenti, siete stati veloci e risolutivi per quanto mi riguarda, altro che storie.

**Comment by undertherainITA** [comment]
> Abbiamo aperto una [PR](https://github.com/italia/cieid-android-sdk/pull/26) che risolve il problema sulla libreria principale utilizzata dalla maggior parte delle app. Questo dovrebbe risolvere anche per iPatente appena aggiornano la libreria.

Ottimo @francescopersico, davvero ottimo.
Ringrazio a nome dei miei ed anche a nome di tutti colori i quali molte volte parlano male delle software house che lavorano per il pubblico (devo dire che avete fatto ricredere anche me), tanto di cappello davvero per il vostro modo di lavorare, ce ne fossero.
Grazie ancora... ;)
