### ISSUE TITLE
L'App non ha categoria nell'App Library (iOS)

### ISSUE THREAD

**Issue by TheIronboy** [pagopa/io-app#4372]
**Descrivi il problema**
L'applicazione viene smistata scorrettamente all'interno di una cartella "Altro" nell'App Library su iPhone.
Questo è dovuto ad una mancanza di categoria nel codice dell'App.

**To Reproduce**
1. Installare l'App dall'App Store
2. Aprire l'App library
3. Applicazione nella cartella "Altro"

**Expected behavior**
L'App dovrebbe avere una propria categoria e non essere smistata in "Altro"
es. Produttività e Finanza

**Screenshots**
![image](https://user-images.githubusercontent.com/66006359/218304912-de34d3ee-7878-49a2-ae91-9a4f18c9a51b.jpeg)

**Versione dell'app**
2.25.0.2

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro (256gb)
 - OS: iOS 16.3

**Comment by Bavuett** [comment]
Facendo un po' di ricerche pare che gli sviluppatori non abbiano molta libertà nel scegliere la categoria di App Library di cui l'app debba far parte. Pare che l'algoritmo sia sconosciuto, e **forse** si basa solo ed esclusivamente sulla categoria di App Store. Non ho alcun dispositivo Apple con cui eventualmente testare, ma nel dubbio lascio un paio di fonti:

https://www.jessesquires.com/blog/2022/01/11/ios-app-library-is-drunk/
https://forums.macrumors.com/threads/is-there-no-way-to-influence-the-app-library-at-all.2334109/
https://stackoverflow.com/questions/63114627/ios-14-app-library-categorization-by-developer-name
