### ISSUE TITLE
[Wallet & Messages] The screens are not displayed properly

### ISSUE THREAD

**Issue by ItsFiloHere** [pagopa/io-app#4373]
**The problem:**
On the "Add payment method" and "Messages" screens, some components are not displayed correctly.

On the "Add payment method" screen, there is not enough space from the border of the screen and the icon of the payment methods.

In the "Messages" section, the slider with "received" and "archived" is not displayed correctly. The shadow on the top is not that beautiful to see, so it should be removed or at least with more margin from the title and the icon of the section

![Screenshot_20230212_125658_IO.jpg](https://user-images.githubusercontent.com/55856803/218309932-614cc0b0-f913-41fd-9560-b78f26f378df.jpg)

![Screenshot_20230212_125650_IO.jpg](https://user-images.githubusercontent.com/55856803/218309939-c3c3245b-56d2-4831-bd6e-5f6a4f16fa12.jpg)

**Comment by dmnplb** [comment]
Hi @ItsFiloHere,
First of all, thank you.
The issue related to the Wallet has been fixed in the following PR: https://github.com/pagopa/io-app/pull/4361.
We opened a new issue for the UI regression related to the Messages.
