### ISSUE TITLE
Accorciare UX per dare suggerimenti in app

### ISSUE THREAD

**Issue by TheBrunez** [pagopa/io-app#4395]
**Qual è il problema che vorresti risolvere?**
Credo che dare suggerimenti in app sia troppo tedioso. Partendo dall'app aperta, il processo è questo:

1. login
2. cliccare il "?" in alto a destra
3. scroll in basso fino a fine pagina
4. cliccare sul pulsante "Apri una richiesta"
5. selezionare argomento "Nessuno dei precedenti"
6. selezionare "Vorrei dare un suggerimento"
7. cliccare su "consenti" per dare il consenso alla trasmissione dei dati
8. scrivere il problema nella casella di testo
9. cliccare sul pulsante di invio 

**Quale soluzione proponi?**

1. dare il consenso una volta sola: attualmente il consenso di invio dati viene chiesto ogni volta che si fa una richiesta di assistenza. Inutile, chiederlo la prima volta e basta. L'idea migliore sarebbe aggiungere una spunta del tipo "Non chiedermelo più" come si vede in molte altre app e contesti
2. accorciare la UX:
2.1. evitare di dovermi far scollare in fondo ogni volta (punto 3 del problema). Piuttosto fatemi leggere quelle avvertenze la prima volta e poi basta
2.2. mettere la sezione "Suggerimenti" nel livello più alto, senza dover selezionare "Nessuno dei precedenti" che è pure poco significativo e costringe a leggersi tutti gli altri punti prima di selezionare quello
2.3. inserire un form per la richiesta di suggerimento che aiuti a separare le informazioni utili. La qualità dei feedback sarebbe molto più elevata già potendo differenziare tra "Qual è il problema che vorresti risolvere?" e "Quale soluzione proponi?" esattamente come qua in GitHub, piuttosto che mettere una semplice casella di testo dove ognuno scrive quello che vuole

**Hai già considerato soluzioni alternative?**
No

**Altre informazioni**
Visto lo stato dell'app (molto bella, ma con veramente poche integrazioni, mi spiace dirlo) credo sia necessario spingere più persone a dare feedback in merito. Poter ricevere dei feedback velocemente e di qualità è essenziale. 
Consiglio anche l'utilizzo di applicativi come [canny.io](https://canny.io/) per rendere poi gli utenti consapevoli delle richieste DI TUTTI e di quello su cui state lavorando. Altrimenti le uniche cose di cui si ha visibilità sono gli issue qua in GitHub, piattaforma che forse utilizzano il 5% degli utenti dell'app IO. E personalmente credo che ci siano ben più di 20 feature request di cui ci sarebbe bisogno, ne potrei proporre 20 nuove che qui non vedo in 5 minuti :)

Nota. prendete le mie critiche come costruttive, sono critiche da cittadino che tutti i giorni ancora oggi fa veramente molta fatica (inutile) per interagire con la PA. Siete l'unica speranza che ho per avere una gestione più umana ed in linea con i tempi che viviamo.

**Comment by TheBrunez** [comment]
@thisisjp vedo che l'issue é stato segnato come completato, da che release é disponibile? Grazie :)

**Comment by thisisjp** [comment]
@TheBrunez la issue è stata chiusa perché non riguarda il team dell'app. Presto sarà disponibile una nuova modalità per raccogliere feedback da parte degli utenti.
