### ISSUE TITLE
When a message is first open, a loading screen can be seen underneath it

### ISSUE THREAD

**Issue by giovannifil-64** [pagopa/io-app#4582]
**Describe the problem**
I had already reported the problem about one year ago, but it continues to be present in the current version of the app.
In the message section, when a message is first opened, the content loading screen and then the message itself are shown as if they were two separate screens.
On the other hand, if the message has already been opened, the loading screen is always shown, but for less time.

**To Reproduce**
1. Go to the 'Messages' page
2. Open a message and you should be able to see the glitchOpen a message and you should be able to see the glitch

**Expected behavior**
The loading screen should be inside the message itself

**Screenshots**

https://user-images.githubusercontent.com/39963191/235877901-6b3b3317-9051-437a-918a-e7499ff287ea.MP4

![IMG_4415](https://user-images.githubusercontent.com/39963191/235876985-101dab3f-1bee-49a9-9658-e55e42b69752.PNG)

**Versione dell'app**
2.30.0.2

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 16.2.1

**Additional context**
As I said before, the glitch was already shown in #3997, but since then there has been no update

**Comment by Vangaorth** [comment]
Thanks for reporting it @giovannifil-64. We are aware that this issue exists and are working to resolve it.
