### ISSUE TITLE
When the new transactions list is displayed, the message constraints for the helpdesk are incorrect

### ISSUE THREAD

**Issue by giovannifil-64** [pagopa/io-app#4865]
**Descrivi il problema**
With the usage of the new listItem component the message constraints dos not appear to be applied.
Can the message be removed completely, or use the banner component instead, and the transactions be shown directly without loading them manually?

**To Reproduce**
1. Go to 'Wallet'
2. Click on 'Show transactions'
3. You should see the wrong constraints behaviour

**Expected behavior**
The banner should have the same constraints as the message.

**Screenshots**
![image](https://github.com/pagopa/io-app/assets/39963191/f1416305-a671-4972-a3c3-c96cab05da78)

![image](https://github.com/pagopa/io-app/assets/39963191/82be1776-7551-4d51-b43f-8de579889c22)

**Versione dell'app**
2.39.04

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 16.4.1(a)

**Comment by Hantex9** [comment]
Addressed into #4875 

Thank you for the report!
