### ISSUE TITLE
accesso al backoffice IO

### ISSUE THREAD

**Issue by michelaportesani** [pagopa/io-app#4939]
L'accesso al backoffice è limitato solo alla mia persona in quanto legato al mio telefono

Sarebbe possibile aggiungere altri account amministrativi? sarebbe possibile aggiungere account non amministrativi ma operativi che possono ad esempio utilizzare solo alcune chiavi per mandare messaggi? Questo potrebbe aiutare a decentrare l'invio di messaggi presso i vari settori/servizi e non lasciare, come accede oggi, tutti gli invii a ICT che però non può farsi carico della quantità di messaggi che a regime saremmo in grado di mandare

**Comment by thisisjp** [comment]
Ciao @michelaportesani!

Negli ultimi mesi abbiamo lavorato ad un nuovo portale di back-office dedicato agli Enti, denominato “[Area Riservata](https://www.pagopa.it/it/area-riservata)”, concepito per costituire il canale primario di interfaccia degli Enti (e loro eventuali partner tecnologici) per l’adesione e gestione dei prodotti in capo alla società.

A breve, agli enti verrà chiesto di entrare in Area Riservata e, una volta importati i loro servizi, di cominciare ad utilizzare il nuovo portale per gestire IO. Il developer portal verrà deprecato ed infine del tutto eliminato.

La novità del nuovo back-office è una modifica sostanziale nel paradigma: da “delegato-centrico”, in cui i servizi sono creati dal singolo delegato, a “ente-centrico”, dove i servizi sono legati direttamente all’ente di riferimento.
Questo significa che sarà possibile avere più utenti, sia amministrativi che operativi, che operano sullo stesso servizio e possono inviare messaggi da quel servizio.

Il tuo ente verrà informato direttamente quando sarà possibile effettuare l'accesso alla nuova Area Riservata 😉

**Comment by michelaportesani** [comment]
Sono molto contenta, è una cosa che stavamo aspettando con ansia per poter essere davvero operativi 

grazie 

Michela Portesani 

Comune di Cremona 
Unità Direzionale Segretario Generale 
ICT e Agenda Digitale 
Via Gallarati, 1 
26100 Cremona 
Tel. 0372/407585 
***@***.*** 


Da: "Jacopo Pompilii" ***@***.***> 
A: "pagopa/io-app" ***@***.***> 
Cc: "Michela Portesani" ***@***.***>, "Mention" ***@***.***> 
Inviato: Mercoledì, 30 agosto 2023 14:36:10 
Oggetto: Re: [pagopa/io-app] accesso al backoffice IO (Issue #4939) 





Ciao [ https://github.com/michelaportesani | @michelaportesani ] ! 

Negli ultimi mesi abbiamo lavorato ad un nuovo portale di back-office dedicato agli Enti, denominato “ [ https://www.pagopa.it/it/area-riservata | Area Riservata ] ”, concepito per costituire il canale primario di interfaccia degli Enti (e loro eventuali partner tecnologici) per l’adesione e gestione dei prodotti in capo alla società. 

A breve, agli enti verrà chiesto di entrare in Area Riservata e, una volta importati i loro servizi, di cominciare ad utilizzare il nuovo portale per gestire IO. Il developer portal verrà deprecato ed infine del tutto eliminato. 

La novità del nuovo back-office è una modifica sostanziale nel paradigma: da “delegato-centrico”, in cui i servizi sono creati dal singolo delegato, a “ente-centrico”, dove i servizi sono legati direttamente all’ente di riferimento. 
Questo significa che sarà possibile avere più utenti, sia amministrativi che operativi, che operano sullo stesso servizio e possono inviare messaggi da quel servizio. 

Il tuo ente verrà informato direttamente quando sarà possibile effettuare l'accesso alla nuova Area Riservata \uD83D\uDE09

**Comment by michelaportesani** [comment]
Buongiorno, so che il post è chiuso, spero comunque di ottenere una risposta:
Possiamo avere un'idea dei tempi? Perché questo sarebbe una discriminante importante per fare una scelta sul bando PNRR 1.4.3 app IO: decidere cioè di tenere lo stesso numero di servizi (cambiandoli come ci è stato comunicato) o rinunciare e presentare una nuova domanda con molti meno servizi. Se i settori saranno in grado di mandare messaggi autonomamente, manterremmo alto il numero di servizi altrimenti ci vedremmo costretti ad abbassarli.
Grazie
