### ISSUE TITLE
App crash con "Paga un avviso"

### ISSUE THREAD

**Issue by EnricoBara** [pagopa/io-app#5082]
Dopo aver reinstallato l'app su iPhone 15 pro e iOS 17.0.3 l'app non ha chiesto i permessi di utilizzare la fotocamera e va in crash premendo su "paga un avviso". Già provato il logout e una nuova installazione dell'app.

Grazie

**Comment by EnricoBara** [comment]
![IMG_0123](https://github.com/pagopa/io-app/assets/12520941/d8326e10-af05-490d-996a-3b82ce31a262)

**Comment by thisisjp** [comment]
Ciao @EnricoBara, il bug dovrebbe risolversi con la versione 2.43, presto disponibile negli store. Lascio la issue aperta così ci puoi dare un feedback quando aggiornerai l’app 💪🏻

**Comment by manuelevlr** [comment]
> Dopo aver reinstallato l'app su iPhone 15 pro e iOS 17.0.3 l'app non ha chiesto i permessi di utilizzare la fotocamera e va in crash premendo su "paga un avviso". Già provato il logout e una nuova installazione dell'app.
> 
> 
> 
> Grazie

Anche io ho il medesimo problema. iPhone 15 pro con l'ultima versione di iOS.

**Comment by manuelevlr** [comment]
> Ciao @EnricoBara, il bug dovrebbe risolversi con la versione 2.43, presto disponibile negli store. Lascio la issue aperta così ci puoi dare un feedback quando aggiornerai l’app 💪🏻

Confermo che con l'ultima versione il problema è stato risolto.
