### ISSUE TITLE
Avvisi di Pagamento: informazioni in App carenti rispetto a quelle in riecevuta email

### ISSUE THREAD

**Issue by bzimage-it** [pagopa/io-app#5092]
**Le informazioni mostrate nella notifica e negli avvisi di pagamento sono carenti rispetto a quelle che poi sono contenute nella ricevuta email**
Il problema può essere importante quando si ricevono più avvisi di pagamento simili e quindi non si riesce a capire informazioni essenziali.
Ad esempio mi è capitato che la scuola frequentata da 2 miei figli abbia mandato una avviso di pagamneto per il contributo gite scolastiche per uno solo dei figli, ma non c'era modo di sapere ne dalla notifica, ne dall'avviso ne dalle informazioni presenti in App ne prima ne dopo l'avvenuto pagamento a quali dei due figli fosse riferita l'operazione. Poi una volta arrivata la ricevuta email , conteneva effettivamente il codice fiscale del bambino e solo grazie a quello ho potuto collegare le cose. Ritengo per per altri tipo di avviso possa presentarsi una problematica simile.  Tuttora non è possibile visualizzare queste informazioni in App ne in "portafoglio" -> "Le tue operazioni" ne in "Messaggi". 

**Quale soluzione proponi?**
Se il codice fiscale ed altre informazioni sono mostrate in ricevuta email non c'è motivo che non vengano mostate anche in App. Si tratta solo di arricchire le informazioni in App con ciò che è già noto al sistema: il flusso di informazioni fra piattaforme va arricchito.

**Altre informazioni**
maggiori informazioni e screenshot con informazioni personali che non è possibile allegare qui sono state scambiate con il centro assistenza riferimento  #ticket 963195

**Comment by thisisjp** [comment]
Ottimo feedback @bzimage-it, faccio le dovute verifiche ma penso riusciamo a inserire tale informazione nella schermata di riepilogo dell'avviso 💪

**Comment by bzimage-it** [comment]
"Ottimo feedback" perché siamo colleghi e anche io sono informatico 🙂
Quando si parla la stessa lingua è tutto più facile. Buon lavoro.

Il mer 11 ott 2023, 11:06 Jacopo Pompilii ***@***.***> ha
scritto:
