### ISSUE TITLE
IT Wallet

### ISSUE THREAD

**Issue by PeraDev7** [pagopa/io-app#5252]
Ci sono novità sull'IT WALLET?
Come si può partecipare alla beta?

**Comment by AndreaCicca** [comment]
> Ci sono novità sull'IT WALLET? Come si può partecipare alla beta?

La fase di beta chiusa è terminata e entro la prima metà del 2024 arriverà a tutti [https://dday.it/redazione/47944/it-wallet-portafoglio-identita-digitale-italiano-prima-versione-pubblica-entro-giugno-2024](link)
