### ISSUE TITLE
Use the numeric keypad in CVV inputs

### ISSUE THREAD

**Issue by bfabio** [pagopa/io-app#5295]
**Qual è il problema che vorresti risolvere?**
When paying with a credit card (and I guess a debit card as well) on Android (haven't tried iOS) you can end up in this screen asking for a CVV:
![image](https://github.com/pagopa/io-app/assets/788293/a5330019-4408-44d0-a4b4-90f13e2cfab8)

The soft keyboard is the default one, but it should be a numeric one. That would vastly improve the UX of that activity.

**Quale soluzione proponi?**
Use a numeric soft keyboard for both Android and iOS when asking for CVVs or any other number-only input

**Comment by bfabio** [comment]
Just noticed this was already reported as #3067.

Please please please for the love of all that is good don't configure stale-bots like that! When the reporter doesn't provide more info on request it's fine to close an issue after a while, but NOT when the info is there but the issue isn't getting any traffic.

**Comment by thisisjp** [comment]
Thanks for the feedback @bfabio! This page is part of a web view-based flow which is not developed by this team. 
However, we've already identified the bug and hopefully it will be fixed by our payments solution provider in an upcoming revamp of the payment experience. Stay tuned 🚀

**Comment by bfabio** [comment]
@thisisjp nice to know, thanks!

**Comment by bfabio** [comment]
Bump

**Comment by bfabio** [comment]
Bump

**Comment by thisisjp** [comment]
The whole card onboarding flow has been refactored (with our vendor Nexi) and it now includes a proper handling of numeric keyboard on mobile. During payments with saved methods, you won't need to re-enter the CVV anymore.

It will be generally available in the next weeks 🚀

**Comment by thisisjp** [comment]
v 2.65.0.0 now supports the new payment flow which includes the proper numeric keyboard handling
