### ISSUE TITLE
Lettura byte template mail

### ISSUE THREAD

**Issue by pippob02** [pagopa/io-app#5307]
Buongiorno,
gestiamo un applicativo che invia le notifiche APPIO tramite una chiamata rest al vostro servizio e riscontriamo un bug nella lettura dei byte presenti nel template.
Per fare dei test specifici abbiamo utilizzato un testo contenente alcuni caratteri speciali che potrebbero non essere accettati dal vostro standard di charset (in allegato il file).
[template_mail_lista 1.txt](https://github.com/pagopa/io-app/files/13578420/template_mail_lista.1.txt)
Questo è il risultato:
![Screenshot_2023-12-05-16-48-06-621_it pagopa io app](https://github.com/pagopa/io-app/assets/144464814/bde96121-bc87-490e-98e5-f3b5b7a9832a)
Sembri che nella chiamata forziamo l'utilizzo del charset UTF-8 ed è stato provato anche utilizzando lo standard ISO-8859-1, ma entrambe le modalità non sono sufficienti a risolvere il problema. 
Internamente avete una gestione particolare della lettura dei byte o ci consigliate di modificare la richiesta rest in qualche modo?

Attendiamo una vostra risposta
Grazie
Saluti

**Comment by LoFrance** [comment]
Ciao,

abbiamo ricevuto e lavorato la tua segnalazione, ma per fornirti la risposta di risoluzione al tuo problema, ti invito a scrivere all’email del service management io-service-management@pagopa.it

Grazie

**Comment by pippob02** [comment]
Ciao,
abbiamo codificato la stringa in questione utilizzando ISO-8859-15 per poi fare una richiesta verso pagopa con utf8 e siamo riusciti a mostrare tutti i caratteri tranne il simbolo dell'euro, l'unico modo trovato per stamparlo su appio è stato utilizzare la codifica html "&#x20AC;", forse utilizzate una codifica vecchia.
