### ISSUE TITLE
Titolo sezione Servizi errato

### ISSUE THREAD

**Issue by Marlowess** [pagopa/io-app#5356]
**Descrivi il problema**
La sezione SERVIZI riporta erroneamente il titolo MESSAGGI.

**To Reproduce**
1. Navigare fino alla sezione SERVIZI

**Expected behavior**
La sezione dovrebbe avere SERVIZI come valore dell'header.

**Screenshots**
![image](https://github.com/pagopa/io-app/assets/8728861/d1398ef1-fc32-4c21-9154-534defbca7c4)

**Versione dell'app**
2.48.0.7

**Smartphone (please complete the following information):**
 - Device: iPhone12
 - OS: iOS 16.6.1

**Additional context**
None

**Comment by CrisTofani** [comment]
Addressed in #5358 thanks for the mention!
