### ISSUE TITLE
Accesso anche da browser su PC

### ISSUE THREAD

**Issue by alever22** [pagopa/io-app#5364]
Buongiorno,
leggendo le caratteristiche del progetto, mi sembra che l'accesso sia limitato agli smartphones Android oppure iOS.

Credo che questa limitazione precluda molto l'utilizzo dell'applicazione da parte dei cittadini, considerando alcuni aspetti non trascurabili:

- molte persone non possiedono uno smartphone e non hanno intenzione di procurarselo
- in futuro potrebbe aumentare molto l'uso di tecnologie per smartphone diverse da Android/iOS e l'accesso via browser consentirebbe di non dover espandere tutta l'applicazione

Grazie dell'attenzione

**Comment by thisisjp** [comment]
Duplicated of #4176
