### ISSUE TITLE
Eliminare accont io

### ISSUE THREAD

**Issue by Cavolfiorecongelato** [pagopa/io-app#5455]
**Qual è il problema che vorresti risolvere?**
Non riesco a trovare un modo per eliminare l'accont io e cioè tutto ciò che ne è associato.

**Quale soluzione proponi?**
Mettere un collegamento seplice, chiaro, visibile e disponiblie che riconduca ad eliminare l'accont, ad esempio nelle FAQ.

**Hai già considerato soluzioni alternative?**
Ho pensato si doverebbe rientrare nell'app, ma io l'app non la uso da molto e si è disconnessa e quindi per rientrare dovrei accettare le nuove condizioni di privacy e non voglio farlo, proprio perchè voglio eliminarlo, non riaprilo.

**Comment by thisisjp** [comment]
Ciao @Cavolfiorecongelato,
per eliminare il tuo account senza accedere all'app, puoi richiedere la cancellazione dei tuoi dati tramite il [portale Onetrust](https://privacyportal-de.onetrust.com/webform/77f17844-04c3-4969-a11d-462ee77acbe1/9ab6533d-be4a-482e-929a-0d8d2ab29df8).

Il portale è sempre raggiungibile dal sito www.pagopa.it, alla voce "Diritto alla protezione dei dati personali".
