### ISSUE TITLE
Data scadenza pagamento errata

### ISSUE THREAD

**Issue by Marlowess** [pagopa/io-app#5481]
**Descrivi il problema**
Inserendo manualmente il codice di avviso pagamento e il codice fiscale dell'ente ottengo i dati corretti, eccetto la data di scadenza (vedi immagine).

**To Reproduce**
1. Andare su Portafoglio
2. Cliccare su 'Paga un avviso'
3. Cliccare su 'Inserisci manualmente'
4. Inserire i dati e osservare la data di scadenza

**Expected behavior**
Ci si aspetta la data reale di scadenza. Si precisa che su piattaforma dell'ente collegata a PagoPa la data di scadenza risulta corretta.

**Screenshots**
![image](https://github.com/pagopa/io-app/assets/8728861/7ee47110-81d4-4183-8727-23118af12fd7)

**Versione dell'app**
Versione 2.52.0.1

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 16.6.1

**Additional context**
None

**Comment by thisisjp** [comment]
Ciao @Marlowess,
grazie per il feedback!

Se puoi, sarebbe utile conoscere il nome dell'Ente Creditore così da indirizzare correttamente la richiesta.
Se vedi la data di scadenza correttamente sul sito dell'Ente, allora molto probabilmente si tratta di un uso improprio da parte sua del campo `dueDate`, previsto dalle specifiche pagoPA.

**Comment by Marlowess** [comment]
> Ciao @Marlowess,
> 
> grazie per il feedback!
> 
> 
> 
> Se puoi, sarebbe utile conoscere il nome dell'Ente Creditore così da indirizzare correttamente la richiesta.
> 
> Se vedi la data di scadenza correttamente sul sito dell'Ente, allora molto probabilmente si tratta di un uso improprio da parte sua del campo `dueDate`, previsto dalle specifiche pagoPA.

L'ente è la Regione Piemonte. È possibile che la data di scadenza che ho visto sul sito dell'ente fosse riferito alle informazioni in loro possesso (trattandosi di tassa regionale) e non effettivamente a ciò che era contenuto all'interno dell'avviso di pagamento. Resta comunque un uso improprio di quel campo date. Grazie se glielo segnalerete 🙂
