### ISSUE TITLE
"codice avviso" non uniforme

### ISSUE THREAD

**Issue by bzimage-it** [pagopa/io-app#5549]
**Descrivi il problema**
"codice avviso" non sempre uniforme e chiaro nei vari contesti comunicativi legati all' App io. Questo crea una certa ambiguità su cosa deve essere inserito nelle vari campi per il pagamento.

**Details**
Ho ricevuto una email dalla scuola di mio figlio "Emissione avviso di pagamento per......"  indicante fra le altre cose il codice avviso che costituiito in realtà da una lettera A seguito dal C.F. della scuola seguito da altri 14 cifre decimale e infine "FQTL" totale 29 caratteri alfanumerici.

**Expected behavior**
ci si aspettava che il codice avviso fosse quello indicato da inserire nell' APP io. ma invece non era neanche quello che seguiva il codice fiscae della scuola e che precedeva FQTL. Quello vero è stato poi trovato in altro modo, e non era per nulla indicato nella email.

**Solution**
rendere chiaro e univoco il concetto di "codice avviso"

**Internal ref**
si veda ticket di assistenza interna APP IO numero 1186612 contenente riferimenti e dati personali qui non inviabili

**Comment by bzimage-it** [comment]
[chiusa per errore]

**Comment by thisisjp** [comment]
Ciao @bzimage-it grazie della segnalazione! 

Il problema riguarda una comunicazione effettuata dall'Ente via email, e non riguarda nello specifico l'app IO. 

Abbiamo comunque segnalato il problema all'Ente, così da evitare in futuro di inviare informazioni errate sui codici avviso pagoPA. Se il problema dovesse persistere, ti invitiamo a contattare l'Ente di riferimento.
