### ISSUE TITLE
Mostrare agli utenti screenshot di un avviso cartaceo

### ISSUE THREAD

**Issue by sbronzolo** [pagopa/io-app#558]
**Descrivi il problema**
Gli utenti non hanno lo screenshot dell'avviso cartaceo dove individuare i dati che gli chiediamo di inserire @matteodesanti 

**To Reproduce**
1. Go to 'portafoglio'
2. Click on 'paga avviso'
3.Click to 'Inserisci i dati manualmente'
4. Clicchi su "Dove si trovano?" e il link non è attivo

**Expected behavior**
Cliccando vorrei vedere uno screenshot di un avviso cartaceo

**Screenshots**

**Versione dell'app**
Copia i due numeri che appaiono in alto a destra nello schermo dell'app.

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fabriziofff** [comment]
Issue no longer valid in the current implementation
