### ISSUE TITLE
Ingrandire titolo "Inserisci pin" nella schermata blu del pin

### ISSUE THREAD

**Issue by sbronzolo** [pagopa/io-app#559]
**Descrivi il problema**
Corpo del titolo troppo piccolo

**To Reproduce**
1. Entra nell'app per la seconda volta
2. Ti compare schermata blu inserimento pin
3. Il corpo del titolo "Inserisci il codice PIN è piccolo
4. L'utente è attirato più dal messaggio "Cambia codice" che dalla CTA principale

**Expected behavior**
Ingrandire corpo del titolo

**Comment by sbronzolo** [comment]
@matteodesanti

**Comment by fabriziofff** [comment]
Issue no longer valid in the current implementation
