### ISSUE TITLE
Sezione portafoglio corpo del sommario

### ISSUE THREAD

**Issue by sbronzolo** [pagopa/io-app#561]
**Descrivi il problema**
Il corpo del sommario della sezione portafoglio è più piccolo di quello usato abitualmente nell'app

**To Reproduce**
1. Go to 'sezione portafoglio'
2. Guarda il testo sotto al titolo "Portafoglio"

**Expected behavior**
Ingrandire corpo del testo

@matteodesanti

**Comment by fabriziofff** [comment]
Issue no longer valid in the current implementation
