### ISSUE TITLE
Sezione preferenze: icone accese

### ISSUE THREAD

**Issue by sbronzolo** [pagopa/io-app#563]
**Descrivi il problema**
Nella sezione preferenze, le icone di tutte le voci di menu a parte la prima (elenco dei servizi) possono essere interpretate come CTA mentre non sono cliccabili

Se lo saranno in futuro si potrebbe prevedere una modale come in altri punti dell'app
Se non è previsto che siano cliccabili valutare ui alternativa (spegnere icone o rimuoverle)

@matteodesanti

**Comment by DenisFrezzato** [comment]
@cloudify I think this was fixed by https://github.com/teamdigitale/italia-app/pull/708.

**Comment by pietro909** [comment]
le CTA sono tutte attive ad oggi.
