### ISSUE TITLE
Swipe per tornare indietro iOS

### ISSUE THREAD

**Issue by mttb02** [pagopa/io-app#5631]
**Qual è il problema che vorresti risolvere?**
Mancanza di metodo comodo per "tornare indietro" su iOS (in particolare per i dispositivi con uno schermo grande)

**Quale soluzione proponi?**
Abilitare (almeno su iOS) la funzione di "trascinamento dall'estremità sinistra", tipica nel sistema operativo per "tornare indietro"

**Comment by thisisjp** [comment]
Ciao @mttb02!
Stiamo progressivamente implementando lo swipe back nelle varie sezioni dell'app—puoi provarlo, per esempio, nella sezione relativa a Carta Giovani Nazionale.

Presto verrà esteso anche al resto dell'app 🚀
