### ISSUE TITLE
Aggiungere la possibilità di scaricare le ricevute delle operazioni

### ISSUE THREAD

**Issue by San7o** [pagopa/io-app#5655]
**Qual è il problema che vorresti risolvere?**
Dopo aver saldato un avviso di pagamento, è possibile consultare lo storico delle operazioni nella sezione "portafoglio", tuttavia non è consentito scaricarle (ad esempio in formato PDF) né esportarle, né singolarmente né in modo cumulativo. L'unico modo per conservare e inviare la ricevuta della transazione è effettuare uno screenshot dello schermo.

**Quale soluzione proponi?**
Dare la possibilità di scaricare la ricevuta in formato pdf

**Comment by thisisjp** [comment]
Ciao @San7o,
le ricevute pagoPA arrivano in automatico nella sezione messaggi:
1. quando paghi qualsiasi avviso dall'app IO;
2. quando tu, o qualcun altro per tuo conto, paghi un avviso a te intestato presso [qualsiasi canale pagoPA](https://www.pagopa.gov.it/it/cittadini/dove-pagare/).

Apri il messaggio e scarica il PDF con la ricevuta che trovi in allegato.

> [!TIP]
> Se non hai ricevuto alcun messaggio, controlla di aver attivato il servizio "Ricevute pagoPA": lo trovi nei servizi nazionali, sotto la voce "IO, l'app dei servizi pubblici". 

> [!TIP]
> Vuoi ricevere in futuro in automatico i messaggi? Abilita la "configurazione rapida" dalla sezione `Profilo > Preferenze > Gestione Servizi`

Siamo comunque al lavoro per migliorare lo storico delle operazioni pagoPA, speriamo presto di poter condividere novità a riguardo 🚀

**Comment by San7o** [comment]
Grazie
