### ISSUE TITLE
Multiple toast notifications displayed when archiving more than one message

### ISSUE THREAD

**Issue by giovannifil-64** [pagopa/io-app#5810]
**Describe the problem**
When I archive one message, only one confirmation toast banner is displayed. On the other hand, if I archive 2 or more messages, two toast banners are displayed. This behavior also occurs when removing the messages from the archive.

**To Reproduce**
1. Go to "Messages"
2. Long press on a message, select more than one
3. Click "Archive"
4. You should see two messages

**Expected behavior**
Only one banner should appear when I select 1 or more news items.

**Screenshots**
https://github.com/pagopa/io-app/assets/39963191/863cd316-5d3d-45c9-9f68-7fdba216bfda

**Version of the app**
2.60.0.2

**Smartphone:**
 - Device: iPhone 11 Pro
 - OS: iOS 17.3.1

**Comment by Vangaorth** [comment]
Fixed from [2.67.0.3](https://github.com/pagopa/io-app/releases/tag/2.67.0-rc.3) onwards
