### ISSUE TITLE
Is it possibile to apply for driver licence upload testing?

### ISSUE THREAD

**Issue by savdav96** [pagopa/io-app#5983]

**Comment by mabio91** [comment]
Sono interessato anche io. Avevo mandato una segnalazione tramite app in merito allo stesso quesito tempo fa...

**Comment by fra9000** [comment]
Confermo l'interesse, e la volontà di partecipare ad eventuali BETA - testing.

**Comment by mabio91** [comment]
Rinnovo la richiesta, in previsione del prossimo allargamento della fase di test!

**Comment by saveriol** [comment]
Mi unisco anche io per partecipare se possibile. Grazie!

**Comment by thisisjp** [comment]
Ciao, sul nostro sito potete trovare le [domande frequenti](https://io.italia.it/documenti-su-io/faq) relative a [Documenti su IO](https://io.italia.it/documenti-su-io).

Se non siete tra i primi 50mila utenti abilitati oggi, riceverete una comunicazione sull’app IO quando Documenti su IO sarà disponibile (tramite messaggio in app o banner informativo). 

Per non perdere la comunicazione, attivate la ricezione delle notifiche push nelle impostazioni di IO e/o del dispositivo 😉

**Comment by mabio91** [comment]
Effettivamente... più che altro, come dice fra9000, sicuramente sarebbe stato anche più "utile" per il team di sviluppo ricevere feedback da parte di chi aveva mostrato interesse nel partecipare alla sperimentazione (probabilmente più "puntuali" rispetto a un campione randomico di cittadini). Mi dispiace che per un progetto sviluppato in open source non vengano "sfruttati" anche coloro che - per diverse motivazioni - non possono contribuire allo sviluppo software, ma che avrebbero comunque interesse nel fornire i loro contributi.

**Comment by savdav96** [comment]
C'è bisogno anche di parlarne? Siamo in Italia, sicuramente sarà arrivata la notifica di selezione a zia Concetta di Catanzaro che non ha mai aperto l'app e persone che avrebbero fornito feedback adeguato (sono ingegnere informatico) non hanno nemmeno delle risposte in un thread di GitHub (marcato come completato, tra l'altro).
