### ISSUE TITLE
Contatti

### ISSUE THREAD

**Issue by sbronzolo** [pagopa/io-app#607]
**Descrivi il problema**
Sembra mancare una pagina contatti dove inserire 
Licenza, firma del progetto e contatti 
Design e tecnologia a cura di Team per la Trasformazione Digitale - Presidenza del Consiglio
Per informazioni sul progetto visita il sito di [io](io.italia.it)

**Comment by bormiopoli** [comment]
Gataway error dopo aver dato il consenso alla condivisione dati, successivo a reindirizzamento dopo autenticazione NFC con carta identita'

**Comment by fabriziofff** [comment]
Issue no longer valid in the current implementation
