### ISSUE TITLE
Cambia PIN - Disconnetti dal tuo account SPID

### ISSUE THREAD

**Issue by sbronzolo** [pagopa/io-app#608]
**Descrivi il problema**
Entrambe le operazioni rendono di fatto inutilizzabile l'applicazione e obbligano l'utente a riloggarsi con SPID. Per questo motivo sarebbe utile una modale di avviso 
Stai per dissociare la tua utenza dalla app. Per usare di nuovo l'app dovrai inserire le tue credenziali SPID
Annulla - Procedi

**To Reproduce**
1. Go to 'Preferenze'
2. Click on 'Cambia PIN'
oppure
2. Click on 'Disconnetti il tuo account SPID'

**Expected behavior**

**Screenshots**

**Versione dell'app**
Copia i due numeri che appaiono in alto a destra nello schermo dell'app.

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fabriziofff** [comment]
Issue no longer valid in the current implementation
