### ISSUE TITLE
Firma digitale.

### ISSUE THREAD

**Issue by Persiano62** [pagopa/io-app#6110]
**Quale soluzione proponi?**
Firma digitale cittadino.
Sarebbe molto utile poter avere la funzione di firma digitale per il cittadino,  così come previsto per la PA o per società di pubblico servizio.

**Hai già considerato soluzioni alternative?**
Le società commerciali di certificazione firma fanno pagare tanto, anche per un uso occasionale del cittadino.

**Comment by thisisjp** [comment]
Ciao @Persiano62!
In realtà offriamo già un servizio di firma, trovi maggiori informazioni [qui](https://firma.io.italia.it/). Alcuni enti stanno già usando il servizio e, quando necessario, inviano un messaggio in app con una richiesta di firma.

Speriamo presto di poter comunicare novità sul servizio, nel frattempo grazie per il suggerimento!
