### ISSUE TITLE
Possibile accedere alla modalità sviluppatore nella versione scaricata da Google Play Store

### ISSUE THREAD

**Issue by nochill-lp** [pagopa/io-app#6111]
**Descrivi il problema**
Con l'applicazione scaricata da Google Play Store è possibile accedere alla modalità sviluppatore. Non so se sia voluto oppure è un bug.

**To Reproduce**
1. Go to 'Profilo'
2. Click many times on 'app version'

**Screenshots**

**Versione dell'app**
2.68.0.0

**Smartphone (please complete the following information):**
 - Device: One plus Nord
 - OS: Android 12

![Screenshot_2024-08-16-22-36-35-64_59f77d10638d1612042c0637b0baeedc~2](https://github.com/user-attachments/assets/d2fac529-b855-45bf-8439-3690fd16dda8)

**Comment by Marlowess** [comment]
Stessa cosa su iOS.

![image](https://github.com/user-attachments/assets/377a39f0-1e6e-4e27-88e5-2d4cf5dd90a2)

**Comment by Vangaorth** [comment]
Ciao @nochill-lp @Marlowess,
come da vostra ipotesi è una funzionalità voluta riservata a chi si occupa dello sviluppo dell'app.

Questo ci consente, in maniera controllata, di passare in ambiente di test o accedere a componenti UI alternativi utilizzati nelle varie sezioni dell’app.

Alcune delle funzionalità, essendo ancora in fase di sviluppo, possono modificare il normale funzionamento dell'app.
Per questo motivo, consigliamo di non abilitarle a meno che si abbia una conoscenza approfondita del loro utilizzo.

Grazie!
