### ISSUE TITLE
Avvisi di pagamento

### ISSUE THREAD

**Issue by pmattia069** [pagopa/io-app#6134]
Dopo aver pagato un avviso quest’ultimo non è più visualizzabile e compare solo la dicitura avviso già pagato. Resta visualizzabile è scaricabile solo la ricevuta. 

Sarebbe molto comodo che  l’avviso di pagamento effettuato rimanga disponibile per la consultazione anche dopo il pagamento. Questo perché mi capita negli ultimi tempi che a fini fiscali molte volte venga richiesto sia la ricevuta che la motivazione del pagamento appunto l’avviso. Avere tutto a disposizione nell’app sarebbe un grosso vantaggio anche in caso di smarrimento degli avvisi cartacei.

grazie e Complimenti

**Comment by thisisjp** [comment]
Ciao @pmattia069!
La motivazione del pagamento è riportata, insieme a tutti gli altri dati, nella ricevuta pagoPA. Puoi trovarla nella sezione Pagamenti, oppure anche nei messaggi se hai attivo il relativo servizio.

In futuro, sarà possibile accedere ancora più facilmente alla ricevuta direttamente dal messaggio contenente la richiesta di pagamento.

Puoi aiutarmi a capire meglio quali dati ti "mancano"? Grazie :)

**Comment by pmattia069** [comment]
Si spiego meglio. Nell''app IO ricevo una notifica di avviso di pagamento. Procedo al pagamento. Dopo di che visualizzo e scarico la ricevuta. E fin qui tutto ok. Successivamente se ritorno sulla stessa notifica che mi segnala "pagato"![image](https://github.com/user-attachments/assets/c5a72c0f-d204-4a6c-8a66-10d28879bff6)
Non riesco più a visualizzare il documento di notifica avviso ma visualizzo solo una pagina che dice "questo avviso è già stato pagato". Vorrei tornare a visualizzare il documento di notifica avviso![image](https://github.com/user-attachments/assets/d53762b1-1eb8-474e-b900-b6538189bc77)

Spero si comprenda così 
Grazie ancora

**Comment by thisisjp** [comment]
@pmattia069 chiaro. Una volta pagato, non è più possibile accedere alla richiesta di pagamento (la versione digitale dell'avviso, per intenderci). Tutte le informazioni però sono disponibili nella ricevuta.

Come dicevo prima, stiamo lavorando per consentire di accedere automaticamente alla ricevuta (dalla schermata "Questo avviso è stato già pagato"), così da evitare l'utente di doverlo fare manualmente andando nella sezione "Pagamenti".

**Comment by pmattia069** [comment]
Grazie e buon lavoro
