### ISSUE TITLE
Menu sviluppatori accessibile in Prod

### ISSUE THREAD

**Issue by fabiosanto** [pagopa/io-app#6249]
**Descrivi il problema**
Scaricando l'app da Play Store posso accedere al menu sviluppatori.

**To Reproduce**
1. Go to settings 
2. 3 taps on version x.y.z

**Expected behavior**
Menu sviluppatori non dovrebbe essere accessibile in Prod?

![Screenshot_20241007-182135.png](https://github.com/user-attachments/assets/f32ffe4f-94df-4d04-8c87-e008d7bcb481)

**Comment by Vangaorth** [comment]
Ciao @fabiosanto, vedi [6111](https://github.com/pagopa/io-app/issues/6111)

**Comment by fabiosanto** [comment]
Immaginavo.
Grazie
