### ISSUE TITLE
La app non rileva la CIE tramite NFC

### ISSUE THREAD

**Issue by sirtao** [pagopa/io-app#6284]
EDIT: aggiunto piccolo video che mostra il messaggio di errore

**Descrivi il problema**
L'applicazione non intercetta l'NFC su telefono Motorola Edge 50 Ultra

**To Reproduce**
1. Installare l'applicazione
2. Aprire l'applicazione
3. Selezionare "Entra con CIE"
4. Selezionare "Continua con l'accesso rapido" oppure "Entra con SPID o CIE oogni 30 giorni"
5. Inserire PIN della CIE
6. Appoggiare la CIE sul sensore
7. appare messaggio "Nessuna app supportata per questo tag NFC" e la procedura non prosegue

**Expected behavior**
La CIE viene rilevata e la procedura di login continua.

**Versione dell'app**
2.72.00

**Smartphone (please complete the following information):**
 - Device: Motorola Edge 50 Ultra (XT2401-1)
 - OS: Android 14 (kernel 6.1.57, aggiornamento di sicurezza 1 settembre 2024)

**Additional context**
Le applicazioni dedicate alla CIE(CieID e CieSign) sono installate e funzionano, rilevando correttamente la CIE quando necessario.

https://github.com/user-attachments/assets/f6efefde-e3bb-40b8-af9a-b14c240d695a

**Comment by Stefano-Luin** [comment]
Ho lo stesso problema con un moto g84 5G...

**Comment by sirtao** [comment]
Aggiornamento: 

- App vers. 2.78.0.11
- OS: Android 14 (kernel 6.1.57, aggiornamento di sicurezza 1 ottobre 2024)
- Versione aggiornamento: U3UVS34.26-101-16-2

ora apre correttamente l'app della CIE per l'accesso.

...però ho dovuto resettare l'applicazione perché si bloccava alla schermata di benvenuto("Ciao Nome!").
E adesso mi dice che non ha i requisiti di sicurezza. Aprirò bug dedicato.

**Comment by biccio** [comment]
ciao @sirtao, vuoi menzionare qui dove hai segnalato il secondo bug così chiudiamo la issue?

**Comment by sirtao** [comment]
> ciao @sirtao, vuoi menzionare qui dove hai segnalato il secondo bug così chiudiamo la issue?

È il problema dei requisiti di sicurezza non rilevati già aperto in #6525 e #6520 . 

Chiudo l'issue con questo commento.
