### ISSUE TITLE
Problemi con la verifica mediante CieID per l'attivazione dell'IT Wallet

### ISSUE THREAD

**Issue by giovannifil-64** [pagopa/io-app#6323]
**Descrivi il problema**
Durante la verifica dell'identità per l'attivazione dell'IT Wallet, selezionando CieID come metodo di verifica, viene aperto Safari esternamente rispetto all'app, a differenza dell'accesso con SPID che mostra invece la pagina come Modal View.
Una volta effettuato il login non si viene reindirizzati all'app, ma si rimane nel browser e compare semplicemente il testo `eid-web`.

**To Reproduce**
1. Nella schermata di verifica dell'Identità, selezionare CieID
2. Si aprirà Safari (o il browser di default selezionanato)
3. Accedere con le proprie credenziali
4. Apparirà la schermata allegata, senza redirect o altro

**Expected behavior**
N/A

**Screenshots**
<img src="https://github.com/user-attachments/assets/c683e92a-bd44-4855-bbb6-58f760fc115d" width="450">

**Versione dell'app**
2.73.0.3

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 18.0

**Comment by Marlowess** [comment]
Io con iPhone 16 Pro, Firefox come browser di default e iOS 18.0.1 nessun problema utilizzando CieID come metodo di verifica per IT-Wallet.
