### ISSUE TITLE
REQUEST_ATTESTATION_FAILED

### ISSUE THREAD

**Issue by PeraDev7** [pagopa/io-app#6328]
**Descrivi il problema**
Quando provo ad inserire i documenti su app IO, ho questo errore.

**To Reproduce**
1)Portafoglio
2)Documenti su IO - Inizia
3)Continua
4) Errore

**Screenshots**
![Immagine WhatsApp 2024-10-24 ore 10 35 07_293b510e](https://github.com/user-attachments/assets/c0e0672f-f361-4ac9-bb5c-33ba90b9ca1a)

**Versione dell'app**
2.73.0.3

**Smartphone (please complete the following information):**
 - Device: Nothing Phone (1)
 - OS: Android 14

**Additional context**
Dispositivo con permessi di root, ma non trovati dall'applicazione.

**Comment by biccio** [comment]
Grazie per il riscontro, il tema è simile ad altre segnalazioni ricevute. Stiamo lavorando per risolvere questo e altri problemi analoghi.
