### ISSUE TITLE
Mappatura tra rotte e help contestuale

### ISSUE THREAD

**Issue by sbronzolo** [pagopa/io-app#637]
Ho creato i testi delle pagine di help contestuale mediante pull request
Riporto qui la relazione tra pull request e le rotte
--> vedi screenshot
<img width="1044" alt="schermata 2018-10-09 alle 17 23 17" src="https://user-images.githubusercontent.com/24827270/46679919-3e20fa80-cbe8-11e8-83ea-c8e6ad5aa4cb.png">
@matteodesanti

**Comment by fabriziofff** [comment]
Issue no longer valid in the current implementation
