### ISSUE TITLE
Nuovo documento da inserire

### ISSUE THREAD

**Issue by Stef2024-lab** [pagopa/io-app#6374]
Buongiorno, oltre all'inserimento della patente dell'app che è molto utile, si potrebbe un giorno poter aggiungere anche il libretto di circolazione del proprio veicolo? Sarebbe davvero il completamento di un funzionamento geniale dell'app Io.  Grazie

**Comment by Teo230** [comment]
Anche la relativa assicurazione

**Comment by certevol** [comment]
Grazie per il contributo, stiamo già lavorando per ampliare l'offerta di documenti digitali e prenderemo in considerazione il tuo feedback. Continua a seguirci per restare aggiornato sulle prossime novità.
