### ISSUE TITLE
Update microcopy

### ISSUE THREAD

**Issue by sbronzolo** [pagopa/io-app#638]
**Descrivi il problema**
La revisione fatta al microcopy della app è al momento qui 
https://github.com/sbronzolo/italia-app/commit/362ef444b421bf1c871e87aec3f1bd7c42b2b02f
@matteodesanti

**Comment by pietro909** [comment]
Da un controllo veloce le linee da 76 a 116 non esistono piu' nell'app, e la linea 39 risulta corretta.
Chiudo perche' non piu' applicabile.
