### ISSUE TITLE
Full Dark mode

### ISSUE THREAD

**Issue by ImperatoDavide** [pagopa/io-app#6467]
**Qual è il problema che vorresti risolvere?**
L'app è troppo bianca; ad oggi tutti i sistemi operativi mobili hanno una "modalità scura" per risparmiare batteria e vista.
Per come è attivabile attualmente 2.78.0.8 è inutile:
- non rimane salvata l'impostazione in riapertura dell'app;
- pagina di caricamento app bianca;
- molti tasti/icone sono con uno sfondo bianco che le fa stonare con il resto del template scuro:
-- menu principale "Messaggi/MESSAGES_HOME" il banner "Cerchi il profilo? [...]"
-- menu principale "Portafoglio/WALLET_HOME" il banner "Novità in arrivo [...]"
-- menu principale "Portafoglio/WALLET_HOME", le carte aggiunte risultano quasi illeggibili per l'effetto contrasto.
--- schermata "PAYMENT_METHOD_DETAILS_SCREEN" illegibile per contrasto chiaro/scuro.
- menu principale "BARCODE_SCAN" -> "Carica" e "Digita", menu illeggibile.

**Quale soluzione proponi?**
Propongo l'aggiunta di una modalità scura, magari con la possibilità di correlarne l'attivazione con l'impostazione in quel momento attiva sul sistema.

Grazie,
Davide

**Comment by dmnplb** [comment]
Ciao @ImperatoDavide,
L'attuale modalità scura è un _work in progress_, quindi non ancora pronta per il rilascio pubblico. È il principale motivo per cui non si può ancora impostare all'interno delle sezioni pubbliche dell'app.

Siamo consapevoli dei limiti da te evidenziati, sia per quanto riguarda la modalità di attivazione che per la mancata uniformità a livello di componenti e schermate, e sono aspetti tecnici per noi imprescindibili prima dell'eventuale rilascio.

Intanto grazie per questi primi riscontri.

**PS**: se vuoi seguire gli avanzamenti della modalità scura, il mio consiglio è di buttare un occhio ogni tanto alla [lista delle PR filtrata con l'etichetta **Dark mode**](https://github.com/pagopa/io-app/pulls?q=sort%3Aupdated-desc+is%3Apr+label%3A%22Dark+mode+%F0%9F%8C%9D%22)
