### ISSUE TITLE
s24 ultra non ha i requisiti di sicurezza

### ISSUE THREAD

**Issue by raizer88** [pagopa/io-app#6492]
**Descrivi il problema**
Provo a caricare documenti di identità, ma l'app mi dice che non ho i livelli minimi di sicurezza.
Il device è stock (acquistato 1 settimana fa da samsung.com) niente root o bootloader sbloccato.

**To Reproduce**
1. apri l'app
2. login con CIE
3. inizia a caricare documenti
4. fail

**Expected behavior**
Vorrei caricare i documenti

**Screenshots**
 
 
![Screenshot_20241204_110920_IO](https://github.com/user-attachments/assets/addac9d2-9195-4a8d-90c0-ebfb5aed3b98)

**Versione dell'app**
2.78.0.11

**Smartphone (please complete the following information):**
 - Device: S24 Ultra
 - OS: Android 14
![Screenshot_20241204_111011_Settings](https://github.com/user-attachments/assets/3b227683-3c19-44c0-8e99-d88352ae8f4c)

**Additional context**

![Screenshot_20241204_152511_Play Integrity API Checker](https://github.com/user-attachments/assets/c7b10998-9128-41de-8945-6f94d7a543fb)

**Comment by Princeofthebow** [comment]
I have the same exact problem on Google Pixel 3a.  I have of course read the FAQ 12 but the reason provided is still from satisfactory. My phone is **not** rooted and the IO app works perfectly with the exception of IT wallet.

**Comment by mcallegari** [comment]
Aggiungo anche il mio Xiaomi 14, non rootato, passa tutti i controlli di sicurezza.
OS Xiaomi HyperOS 1.0.24.0

**Comment by Princeofthebow** [comment]
> I have the same exact problem on Google Pixel 3a. I have of course read the FAQ 12 but the reason provided is still from satisfactory. My phone is **not** rooted and the IO app works perfectly with the exception of IT wallet.

Nel mio caso il problema, dopo un po di ricerca, non era ne il telefono ne il sistema opertivo. Bensi avevo lasciato abilitato la possibilita' di installare app di origini sconosciute. Appena l'ho disabilitato ha preso a funzionare. @raizer88 

Suggerirei comunque di indicare questo fatto nella faq.

**Comment by mcallegari** [comment]
Nel mio caso invece un reboot del telefono ha risolto il problema.

**Comment by ale-mazz** [comment]
Ciao @raizer88, stiamo analizzando la problematica e avremo bisogno di più informazioni: hai impostato un metodo di sblocco del dispositivo tramite il riconoscimento del volto? Hai più modalità di sblocco del dispositivo impostate? Grazie.

**Comment by raizer88** [comment]
> Ciao @raizer88, stiamo analizzando la problematica e avremo bisogno di più informazioni: hai impostato un metodo di sblocco del dispositivo tramite il riconoscimento del volto? Hai più modalità di sblocco del dispositivo impostate? Grazie.

Ciao, 
ho fatto qualche tentativo random durante sti giorni e alla fine ho passato il controllo di integrità. Lato mio non ho fatto niente. Forse è un problema di saturazione dell'api dietro e se non risponde in tempo da ko di default?

In ogni caso io ho attivo riconoscimento del volto, simbolo e impronta digitale. In genere entro con l'impronta.

**Comment by Ivymike1952** [comment]
> > Ciao @raizer88, stiamo analizzando la problematica e avremo bisogno di più informazioni: hai impostato un metodo di sblocco del dispositivo tramite il riconoscimento del volto? Hai più modalità di sblocco del dispositivo impostate? Grazie.
> 
> Ciao, ho fatto qualche tentativo random durante sti giorni e alla fine ho passato il controllo di integrità. Lato mio non ho fatto niente. Forse è un problema di saturazione dell'api dietro e se non risponde in tempo da ko di default?
> 
> In ogni caso io ho attivo riconoscimento del volto, simbolo e impronta digitale. In genere entro con l'impronta.

Quindi hai provato ad entrare e oggi ti ha fatto mettere i documenti?
A me continua sempre a dare lo stesso messaggio

**Comment by raizer88** [comment]
Si ho provato ogni 6-7 ore, e alla fine me l'ha fatti mettere. Non so se è legato al traffico, prova a farlo in orario serale tardi e vedi se risolvi.

**Comment by Ivymike1952** [comment]
beh mi sembra una procedura affidabile.... roba da matti

**Comment by ale-mazz** [comment]
Grazie per i vostri feedback, abbiamo identificato una possibile causa al problema segnalato da @raizer88 relativa allo sblocco con il volto. Una soluzione temporanea potrebbe essere quella di sbloccare il dispositivo attraverso il pin (quindi senza utilizzare lo sblocco biometrico con impronta digitale o volto) e provare ad attivare Documento su IO. Una soluzione alternativa è quella di riavviare il dispositivo in quanto obbliga l'inserimento del PIN per lo sblocco.

**Comment by Ivymike1952** [comment]
Quindi l'app è volta alla sicurezza e per farla andare occorre togliere 2 accessi considerati sicuri come impronta e volto?

Adesso provo.... e vi do feedback!

**Comment by Ivymike1952** [comment]
Appena provato a disabilitare impronta e viso, riavviare e fa uguale!

**Comment by SalvatoreNoschese** [comment]
L'hanno resa talmente sicura che praticamente non può usarla né chi ha os non stock, né chi ha Samsung, né chi ha root o semplice bootloader sbloccato, né chi ha uno smartphone senza servizi Google e Google store, né chi non ha uno smartphone o ha uno smartphone non android/ios (Linux, per esempio) e magari vorrebbe semplicemente usare il PC o il notebook per accedere a simili servizi.
Insomma, sicurissima e inutilissima al momento.

**Comment by Ivymike1952** [comment]
No ma sul serio. A parte che io farei una causa se trovassi gente che è d'accordo contro le aziende che bloccano il root.
Dato che si parla sempre di libertà... così facendo limitate la libertà della gente a fare col telefono quello che vuole.
Io ho sempre usato telefono root per necessità, e sono cavoli miei se mi rubano credenziali o soldi.
Credo che la storia della sicurezza sia una balla solo per avere un controllo da parte delle grosse aziende. Non è complottismo sia chiaro ma che dicano che fanno così per la sicurezza è una balla.
Fino adesso i portafogli sono sicuri? Basta perderlo o scordarselo o farselo rubare dato le brave zingare che mostrano nei video e cosa cambia?

Detto questo sarebbe meglio togliessero questi controlli e rendessero l'app fruibile a tutti..... almeno a quelli col telefono originale e che ha tutti i requisiti in regola.
Io al momento ho fatto quanto detto da @raizer88 ma continua a non andare niente.
Poi se non sarà così amen continuo a usare i documenti fisici tanto non potranno obbligare nessuno e se dovessero obbligare.... rifiuterei.

**Comment by Ivymike1952** [comment]
Qualche novità sulla vostra App? Io provo da giorni a caricare giorno e notte e sempre la stessa storia.

**Comment by Ivymike1952** [comment]
Ho appena scaricato l'ultima versione! 
Leggo: "Abbiamo risolto un problema che impediva ad alcuni utenti di attivare Documenti pur avendo un dispositivo compatibile.

BoH! a me impedisce tuttora di caricarli..... direi ottimo! 👎

**Comment by SalvatoreNoschese** [comment]
Ritrovato anch'io giusto adesso. Niente è cambiato.

**Comment by Ivymike1952** [comment]
Io insisto nel dire che il problema è la parte che loro mettono per verificare se i dispositivi sono certificati.

Premesso che ribadisco questa sicurezza non serve a niente, la scusa che se ti rubano i documenti è futile, dato che oggi non c'è nessuna differenza a chi rubano il portafogli o chi se lo dimentica da qualche parte. La responsabilità è sempre del proprietario, pertanto aver messo un controllo magari del root ok ma qui si è esagerato.

**Comment by biccio** [comment]
Ciao, per dispositivi stock confermiamo che è necessario disinstallare e reinstallare app IO ora in versione 2.79.0.9, su cui è stato introdotto un fix relativo a questa issue.

**Comment by Ivymike1952** [comment]
Disinstallata l'app, reinstallata l'app e ancora da:

"Il tuo dispositivo non supporta Documenti su IO"
Il tuo dispositivo non ha i requisiti di sicurezza necessari.

Vabbè dai io lascio perdere!

**Comment by Ivymike1952** [comment]
Chi ti ha risposto? Chi hai contattato?

Beh direi che per essere un'app istituzionale chi la progetta e da queste risposte invece di cercare di renderla compatibile a tutti è una cosa molto bella!

**Comment by SalvatoreNoschese** [comment]
Da app, punto interrogativo a dx, apri richiesta.

**Comment by Ivymike1952** [comment]
Fatto... vediamo cosa mi rispondono

**Comment by SalvatoreNoschese** [comment]
Teniamoci aggiornati 💪

**Comment by Ivymike1952** [comment]
A me non hanno risposto..... direi molto bene
