### ISSUE TITLE
[iOS] Transizioni non a 60fps

### ISSUE THREAD

**Issue by pupaxxo** [pagopa/io-app#6501]
La transizioni fra le varie pagine dell'applicazioni (menu, funziona "inquadra", etc.) arrivano a massimo 60 fps. 
Su iPhone 14/15/16 con schermo a 120hz è evidente la differenza fra lo scrolling e le transizioni.

**Comment by mastro993** [comment]
Ciao @pupaxxo, il nostro obiettivo è fornire l'esperienza più fluida possibile, siamo consapevoli dei limiti tecnici dell'attuale navigazione e abbiamo già inserito in roadmap il suo perfezionamento. 
Ti ringraziamo per il tuo feedback!
