### ISSUE TITLE
[iOS] Integrazione con Apple Wallet

### ISSUE THREAD

**Issue by pupaxxo** [pagopa/io-app#6502]
https://learn.wallet.apple/id

Apple ha già predisposto tutte le API per caricare i propri documenti all'interno del Wallet, sarebbe bello che una volta aggiunti i documenti all'interno dell'app IO si potessero portare anche su Wallet. 
Se non sfruttando le API dei documenti, sfruttando quelle generiche sempre di Wallet, così che i documenti siano comodamente disponibile all'interno delle funzioni native di iOS. 

https://github.com/premieroctet/react-native-wallet

**Comment by biccio** [comment]
Ciao, grazie per il contributo. Consideriamo molto importante l’accesso ai documenti offline e l'attività è già in roadmap e verrà rilasciata nei prossimi mesi. L’integrazione con i wallet nativi è un tema molto rilevante ed è attualmente in studio.

**Comment by hollow-frenk** [comment]
Mi accodo alla richiesta e non vedo l'ora che sia possibile... renderebbe il tutto più immediato. Se poi ci si aggiunge anche la CIE sarebbe top, ma questo è un'altro discorso.
