### ISSUE TITLE
I documenti devono poter essere visualizzati anche se il telefono non è collegato ad internet

### ISSUE THREAD

**Issue by pupaxxo** [pagopa/io-app#6504]
Perchè la funzione dei documenti sia affidabilie deve essere possibile vedere i propri documenti anche quando il dispositivo non è collegato ad internet.

Se dovessi essere fermato in un passo di montagna con poca / senza connettività devo poter essere in grado di mostrare la patente.

Sfruttando l'integrazione con Apple Wallet (e l'equivalente di Google) si potrebbe facilmente risolvere questo problema.

![immagine](https://github.com/user-attachments/assets/9619d536-4316-4c18-ba8b-9977b0f6ad8b)

**Comment by certevol** [comment]
Ciao  e grazie @pupaxxo, l’accesso ai documenti offline (vedi risposta #6502)  è parte integrante della roadmap e verrà rilasciato nei prossimi mesi
