### ISSUE TITLE
Aggiungere compatibilità per GrapheneOS

### ISSUE THREAD

**Issue by MisterEskere** [pagopa/io-app#6507]
**Qual è il problema che vorresti risolvere?**
I documenti digitali non supportano GrapheneOS (https://github.com/grapheneos), un sistema operativo molto sicuro, moltissime feature di sicurezza di android vengono prese direttamente da loro.

**Quale soluzione proponi?**
Hanno una guida su come fare ad aggiungere il controllo hardware del loro OS in parallelo al sistema di play inegity di google. 

https://grapheneos.org/articles/attestation-compatibility-guide

**Comment by Maxsi90** [comment]
Seguo la richiesta, GrapheneOS merita di avere le stesse possibilità concesse a Google. Inaudito che sia tagliato fuori.

**Comment by fph** [comment]
Duplicato di https://github.com/pagopa/io-app/issues/6327

**Comment by Pietro395** [comment]
Discussione su forum Italia per chi vuole partecipare:
https://forum.italia.it/t/grapheneos-e-documenti-su-io/43232

**Comment by certevol** [comment]
In merito lasciamo aperta la issue #6327 per aggiornamenti futuri
