### ISSUE TITLE
Feedback dopo richiesta inviata alla Motorizzazione 

### ISSUE THREAD

**Issue by marco-tuzza** [pagopa/io-app#6509]
L'assenza di feedback dopo aver inviato una richiesta d'inserimento della patente alla Motorizzazione crea abbastanza confusione negli utenti. Inoltre è possibile inviare la richiesta un numero indefinito di volte.

Consiglierei di creare un feedback visivo di conferma e di rendere il bottone dell'invio della richiesta non cliccabile se vi è già una richiesta attiva.

**Comment by certevol** [comment]
Grazie per il contributo, abbiamo ricevuto sui nostri canali di assistenza altre segnalazioni simili, stiamo lavorando ad una soluzione che rilasceremo al più presto
