### ISSUE TITLE
Assurdo richiedere certificazione strong

### ISSUE THREAD

**Issue by SalvatoreNoschese** [pagopa/io-app#6518]
Ci sono tanti motivi per cui uno possa avere difficoltà ad ottenere una certificazione strong:
Os non stock (lineage os, graphene os, crdroid e tanti altri), root, bootloader sbloccato giusto per sicurezza in caso di brick.

E niente, con bootloader sbloccato e non avendo la strong, funzionano le app bancarie, quelle di investimenti, quelle istituzionali (come cieid, Ipatente, la stessa io.app, er.salute), ma non c'è verso di fare funzionare il wallet per i documenti sull'app io perché richiede la STRONG.

Sullo store si sta riempiendo di recensioni 1stella.

Al momento avete un'app che castra (non funziona a dovere) sviluppatori e smanettoni che vogliono semplicemente far funzionare meglio e più a lungo i loro telefoni.

Ci sono anche raccolte firme su Change.org.
Android era libertà, adesso sta diventando peggio di iOS.

**Comment by Aquathing** [comment]
> Ci sono anche raccolte firme su Change.org.

Assolutamente inutile. Change.org serve solo a fare data scraping degli utenti. Esiste una petizione che è stata portata all'attenzione della commissione europea, che ha ricevuto anche risposta: https://www.europarl.europa.eu/doceo/document/PETI-CM-757267_EN.pdf

Le petizioni di change.org non hanno valore, quelle sui siti istituzionali sì.

**Comment by Aquathing** [comment]
Comunque è un duplicato di https://github.com/pagopa/io-app/issues/6327

**Comment by biccio** [comment]
In merito lasciamo aperta la issue #6327 per aggiornamenti futuri
