### ISSUE TITLE
"Il tuo dispositivo non supporta documenti su IO" anche se la Strong Integrity è presente

### ISSUE THREAD

**Issue by enricozoia** [pagopa/io-app#6520]
**Problema**
Quando si tenta di aggiungere i documenti nell'app IO appare la schermata che dice _"Il tuo dispositivo non supporta documenti su IO. Non ha i requisiti di sicurezza minimi"_ anche se:
- È presente la Strong Integrity di Google
- Il bootloader è bloccato
- È presente lo sblocco con biometria
- Le opzioni sviluppatore sono disattivate
_(Le ultime due non sembrano essere dei veri e propri requisiti...)_ 
Nello specifico, attivando la modalità di debug, l'errore è ERR_IO_WALLET_INSTANCE_INTEGRITY_FAILED. Sembra che non riesca a fare la verifica dell'integrità.

**Screenshots**
![Screenshot_20241208-135241](https://github.com/user-attachments/assets/686cbc84-7c83-4c7b-a233-31ed82b933fc)
![immagine](https://github.com/user-attachments/assets/5b08b7f3-b7e5-48b7-ad5b-45b679a551d7)

**Versione dell'app**
2.78.0.11

**Dispositivo**
 - Device: Realme C21Y
 - OS: Android 11
 - Patch Sicurezza: 5 Febbraio 2024

**Comment by italia1971luca** [comment]
posso chiedere come hai fatto il play integrity check?

**Comment by XAlboX** [comment]
> posso chiedere come hai fatto il play integrity check?

Apri il Play Store -> Vai nelle impostazioni -> espandi l'ultima categoria (Informazioni) -> Clicca tante volte sulla versione del play store (sbloccherà le opzioni sviluppatore del play store) -> clicca nella prima categoria delle impostazioni (Generali) -> clicca "Opzioni Sviluppatore" -> Clicca "Verifica l'integrità".

**Comment by italia1971luca** [comment]
> > posso chiedere come hai fatto il play integrity check?
> 
> Apri il Play Store -> Vai nelle impostazioni -> espandi l'ultima categoria (Informazioni) -> Clicca tante volte sulla versione del play store (sbloccherà le opzioni sviluppatore del play store) -> clicca nella prima categoria delle impostazioni (Generali) -> clicca "Opzioni Sviluppatore" -> Clicca "Verifica l'integrità".

Superato; mi resta il problema del key attestation che non capisco se è legato alla versione di Android (14 nel mio caso) o alla particolare versione (Magic os 8) installato sul mio honor 200

**Comment by SalvatoreNoschese** [comment]
No tranquillo. Stessa cosa con P7P e patch dicembre.

È talmente sicura che non funziona a nessuno.
Tra Google con le sue stupide api e gli sviluppatori che si complicano la vita usando simili stupide api, davvero non so chi è peggio.

![Screenshot_20241210-012143](https://github.com/user-attachments/assets/d83b3ff0-afdf-42e8-b141-ba7a4ae48fbf)

![Screenshot_20241210-012209](https://github.com/user-attachments/assets/cba59c01-d324-437f-a310-2c1e0fafa1b1)

![Screenshot_20241210-012304](https://github.com/user-attachments/assets/e8c7b54a-1b67-4985-a79a-a5cc212863c2)

![Screenshot_20241210-012627](https://github.com/user-attachments/assets/3c85b703-9e38-4d15-86db-59f78d571eb5)

![Screenshot_20241210-012637](https://github.com/user-attachments/assets/67c7f5f2-8455-4e4f-9cab-c1ec93734f62)

![Screenshot_20241210-012104](https://github.com/user-attachments/assets/84d401cb-b99b-491a-a16e-ef99614294b5)

![Screenshot_20241210-012118](https://github.com/user-attachments/assets/a759f28f-c77b-4164-8461-023121264f6f)

![Screenshot_20241210-012125](https://github.com/user-attachments/assets/b15ca24f-f741-4f3b-9640-e127b357afb6)

**Comment by sirtao** [comment]
mi accodo:

- Mototola Edge 50 Ultra 
- App IO vers. 2.78.0.11
- OS: Android 14 (kernel 6.1.57, aggiornamento di sicurezza 1 ottobre 2024)
- Versione aggiornamento: U3UVS34.26-101-16-2
- STRONG_INTEGRITY (vedi allegato)

sospetto che il colpevole possa essere l'aggiornamento di sicurezza del telefono di qualche giorno fa, non credo di aver aperto l'app da allora e mi sono ritrovato a doverla resettare per accedervi e con questo simpatico problema.


<img src="https://github.com/user-attachments/assets/64df9b26-090a-437a-bcea-c1e6573e48f9" width=40% height=40%>



Beh, è pur sempre ancora in beta, nominalmente.

**Comment by italia1971luca** [comment]
Almeno per il momento, ma credo di aver risolto. Ho fatto reset alle impostazioni di fabbrica ed è andato tutto a posto. Non so cosa possa aver rovinato i certificati

**Comment by gabriele2000** [comment]
> Almeno per il momento, ma credo di aver risolto. Ho fatto reset alle impostazioni di fabbrica ed è andato tutto a posto. Non so cosa possa aver rovinato i certificati

Con tutto il rispetto: resettare il telefono per una cosa simile mi sembra una cosa a dir poco vergognosa.
Non resettare il telefono per una cosa simile.

**Comment by italia1971luca** [comment]
> > Almeno per il momento, ma credo di aver risolto. Ho fatto reset alle impostazioni di fabbrica ed è andato tutto a posto. Non so cosa possa aver rovinato i certificati
> 
> Con tutto il rispetto: resettare il telefono per una cosa simile mi sembra una cosa a dir poco vergognosa, arriviamo quasi ai livelli del supporto tecnico della Microsoft. Non resettare il telefono per una cosa simile.

Hai ragione, non è bello anche perché non si arriva alla radice del problema. Per fortuna avevo installato da pochi giorni ed è stato relativamente facile e veloce rimettere tutto a posto. Non avessi avuto necessità di avere la versione elettronica dei documenti probabilmente avrei lasciato perdere

**Comment by sirtao** [comment]
Non credo che la Strong Integrity sia stata compromessa in qualsivoglia maniera: ne consegue che è un problema risolvibile lato App.   
Realisticamente il problema è una qualche variabile o file usati solo da IO(perchè null'altro ha problemi) che persiste dopo la disinstallazione della APP.   
Se non hanno fatto cazzate apocalittiche(improbabile) "basterà" aspettare che identifichino e risolvano il problema con un aggiornamento della app che gestisca\pulisca detta variabile\file.

**Comment by SalvatoreNoschese** [comment]
Provato, sempre stesso identico problema.

**Comment by sirtao** [comment]
Per quel che conta 2 giorni fa si è aggiornato "Private Computer Service" e stanotte "Google Partner Setup".
Non ho idea se possano avere influito.

**Comment by biccio** [comment]
In merito lasciamo aperta la issue #6327 per aggiornamenti futuri

**Comment by SalvatoreNoschese** [comment]
Boccio è inconcepibile chiudere senza alcun supporto.
Noi qui abbiamo la strong. Funziona tutto. Non funziona io. Io problema è io e voi chiudete lavandosene le mani
Immagino quest'app sia costata un patrimonio e questo è il risultato.

**Comment by sirtao** [comment]
Il problema è ritornato sul mio dispositivo dopo l'aggiornamento a Android 15 (V1UV35H.5-34-11)

@biccio capisco accentrare le discussioni a una sola per argomento, ma spostare la discussione di _un bug specifico_ nel thread _generico_ sui criteri di sicurezza non mi pare il massimo... o, in alternativa, è una ammissione che i criteri di sicurezza scelti sono il bug lol.
