### ISSUE TITLE
GrapheneOs non supporta i Documenti

### ISSUE THREAD

**Issue by ilveropera** [pagopa/io-app#6524]
Uso il sistema operativo opensource https://grapheneos.org/ nel telefono per rinforzare la mia protezione della privacy e per usare un sistema snello.
L'applicazione funziona ma la nuova sezione dei documenti non e' supportata.

Dopo eventuali verifiche dell'OS Graphene, credo dovrebbe essere messo nella whitelist per permetterne l'uso a chi ha fatto questa scelta.

![photo_5961052812144133639_y](https://github.com/user-attachments/assets/d9423e08-f0c6-472e-81f5-54f73370e338)

**Comment by Aquathing** [comment]
Duplicato di https://github.com/pagopa/io-app/issues/6327

**Comment by certevol** [comment]
In merito lasciamo aperta la issue #6327 per aggiornamenti futuri
