### ISSUE TITLE
non é possibile richiedere documenti su Huawei p60 pro 

### ISSUE THREAD

**Issue by andrew-ld** [pagopa/io-app#6533]
su p60 pro non é possibile richiedere i documenti per motivi di sicurezza, non é stata apportata nessuna modifica al sistema operativo, ne sblocco di bootloader, ne root o simili.

**Comment by andrew-ld** [comment]
unico problema qua é aver deciso che solo i telefono che hanno fatto un accordo commerciale con google possiano accedere a un servizio pubblico.

non vedo come un telefono aggiornato ma senza accordi commerciali con google sia meno sicuro di un telefono non aggiornato da anni ma "approvato"

**Comment by djechelon** [comment]
@andrew-ld Il problema è il concetto di servizio pubblico abbinato a tutte le problematiche **antitrust**. Non è una questione di sicurezza, ma di concorrenza. Le altre discussioni ne parlano approfonditamente
